ARM-software/lisa

- ipynb/devlib/examples/cgroups.ipynb
- ipynb/sched_dvfs/smoke_test.ipynb
- ipynb/trappy/example_custom_events.ipynb
- ipynb/utils/testenv_example.ipynb
- ipynb/wlgen/rtapp_examples.ipynb
- ipynb/wlgen/simple_rtapp.ipynb
- libs/utils/env.py
Minor: Some notebooks had trivial misspellings.
Mod: Port specifications in target configs were being ignored.
> Fixups: Misc spelling fixups + port specification mod

- libs/wlgen/wlgen/rta.py
Proper implementation of delayed task activation is requires "delay" label
in rt-app json grammar (where we currently have "sleep").
Fix that.
Signed-off-by: Juri Lelli <juri.lelli@arm.com>
> libs/wlgen/wlgen/rta: delay phase has to be named delay

- tests/eas/rfc.py
EnergyMeter.getInstance() returns None if there is no energy meter for
the platform.  Therefore, env.emeter is None for platforms that don't
have an energy meter and rfc.py fails with an AttributeError when it
tries to do things like cls.env.emeter.reset()
Check that emeter is not None before calling any of its methods.
> tests/eas/rfc: Only use the energy meter if the platform supports it

- libs/utils/filters.py
- libs/utils/trace.py
- libs/utils/trace_analysis.py
This series is almost just a cleanup of the Trace module to align its code the most recent versions of TRAPpy.
The series removes the internal trace_data dictionary, which was previously used to map DataFrame to a short and handy name. We use now standard tarcepoint names to access DataFrames collected from a trace, which can be obtained via Trace.df() not before having checked that they exists via Trace.hasEvents().
Appreciated if @JaviMerino can give it a look. Maybe a better interface can be used to wrap the TRAPpy FTrace module? Consider that technically all the features in that Trace module can be migrated directly to TRAPpy. What we do here is mainly DataFrame post-processing, sometimes on events which are not pre-registered in TRAPpy.
> Update trace to match the new APIs available in recent TRAPpy versions

- tests/eas/rfc_stune.config
4e2673a38945 ("libs/utils/env: move modules definition into board
specific section") trimmed down the list of modules defined for each
testsuite.  For STune, it trimmed it too much, removing the cgroups
module which is needed by the test.  Add it back.
> rfc_stune: Add the cgroup module back

- .gitmodules
- init_env
That patch should setup submodules for TRAPpy and BART to track mainline versions available on ARM-Software. I've pinned the two projects to that tags:
TRAPpy: v5.1.0
BART: v1.5.0
I expect that, once this patch is merged, we can simply "source init_env" and everything is fine.
To test it that branch:
``` bash
$ git fetch http://github.com/derkling/lisa.git track_arm_software
$ git checkout FETCH_HEAD
$ source init_env
```
If these commands are successful than check that the submodules are checked out in the proper commit:
```bash
$ git submodule status
290caafb3675103f8ee91b71245a7aba0f2b0c2c libs/bart (v1.5.0)
6586d8b10454fad4299ded9f9f31058fa6d66549 libs/devlib (v0.0.3-38-g6586d8b)
26cf414f6b6c5eca30ef12822bc03e06cb1adc34 libs/trappy (v5.1.0)
```
Signed-off-by: Patrick Bellasi …
> submodules: tracking ARM-Software versions of TRAPpy and BART

- tests/stune/smoke_test_ramp.py
We avoid the first period of the rtapp task in the boosted utilization
signal test because of the initial high load.  The period we read from
the parameters is expressed in milliseconds but the index of the
dataframes returned by trappy is in seconds.  Convert rtapp_period to
seconds before adding it to task_start to correctly add the two
variables in the same unit (seconds).
> test/eas/rfc: fix calculation of the first period of the task

- README.md
Fixes about tools dependencies, ipython version needed for JSON nbformat version 4 and link to the quickstart tutorial.
> README.md: fixes to the README file

- libs/utils/env.py
- target.config
When rebooting, the reboot function repeatedly pings the target.
However, rebooting might require some seconds and in order to avoid
pinging the machine before it actually reboots, we can set the
ping_time option in target.config to tell the function how long to
wait before pinging.
Also, a comment has been added in target.config to specify what the
file represents and to highlight that commented parameters are
optional.
> Add ping_time parameter to target.config and reboot

- libs/utils/executor.py
This series allows each workload of a experiment to override the default CGroup defined by a target configuration. This can be obtained by specifying the cgroup in which a workload has to be executed under. For example, the following workload configuration fragment:
```json
"rta" : {
"type" : "rt-app",
"loadref" : "big",
"cgroup" : "/tg1",
"conf" : {
"class"  : "profile",
"params"  : {
"p20" : {
"kind"   : "periodic",
"params" : {
"duty_cycle_pct" : 20,
},
},
},
},
}
```
will configure the "rta" workload to run under the "/tg1" cgroups.
**NOTE:** the specified cgroup has to be configured in each target configuration the workload will run, otherwise a run-time error will be generated.
**NOTE:** to use control groups the "cgroups" module has to be listed among the "modules" to load in the …
> Fix cgroups per workload

- libs/utils/executor.py
- libs/utils/test.py
- tests/eas/rfc.py
- tests/sfreq/smoke_test.py
- tests/stune/smoke_test_ramp.py
This series should fix the multiple execution of the experiments when more than one test function is defined by a nosetest. If @deggeman can give it a try with it's configuration as well (maybe using a reduced set of confs and wloads) it would be great.
If it works as expected, please @deggeman could you merge that PR as well?
> Fix lisa tests

- libs/wlgen/wlgen/workload.py
Devlib provides a specific method for running a command in background which is
not what it was used in LISA. Before, LISA was calling execute() with a
background parameter set to True; now it just calls the background() function
which does the job.
This change only works after [this PR](ARM-software/devlib#25) is merged.
> workload: fix background run of a workload

- libs/wlgen/wlgen/workload.py
By means of a start and an end pause parameter it is now possible to set a
period of time to wait after starting collecting traces and before the
execution of workload (for example to allow something to settle down). In
addition, you can also set a period of time to wait after the workload has
executed and before stopping the trace collection.
The two parameters are optional and their default value is zero.
> workload: add possibility to set pauses before and after executing a workload

- .gitmodules
This patch updates the tracked devlib repository to be the
official one available on github. This should foster the
mainlining of patches and new features for devlib.
> submodules: track mainline devlib repository

- README.md
python-nose is necessary for running nosetests.
close #64
> README.md: add python-nose dependency

- src/shell/lisa_shell
When running lisa-help from directories other than the LISA home
directory, the help information were not printed because the command was
looking for LisaShell.txt in the current directory. This adds the
absolute path to that file so that the help is printed from anywhere in
the filesystem.
> lisa_shell: fix lisa-help command run from anywhere in the filesystem

- libs/wlgen/wlgen/workload.py
This should fix an issue related to the background execution of tasks which are also moved into a CGroup. We slightly update also the semantics of the run() call which allows to collect an ftrace for a background task by using the recently added end_pause_s parameter to specify for how long a trace must be collected while the task runs in background.
> Fix cgroups background

- src/shell/lisa_shell
Change "nosetest" to "nosetests" so can correctly launch lisa-test.
> lisa_shell: fix typo for "nosetests"

- tests/eas/rfc.config
Add a few helpful comments to eas test rfc.config describing how to enable ftrace.
> eas test rfc.config comments for ftrace

- libs/utils/env.py
- libs/utils/trace.py
This series integrate the support for SysTrace which is now provided by TRAPpy.
It adds also a board definition for a Nexus 5X device, which is not properly identified as a big.LITTLE system by devlib because of the old format used for "/proc/cpuinfo" in its default kernel.
Being a standard device we can however easily defined the devlib::Platform to be used when this target
is in use.
NOTE: this series depends on trappy HEAD being advanced to include:
https://github.com/ARM-software/trappy/pull/162
> Add systrace support

- libs/utils/env.py
- target.config
When multiple Android devices are connected to the host machine, the user must specify the ID of the device he wants to connect to. This series shows an example of usage in the `target.config` file and fixes a bug when passing the device ID to the test environment.
> Usage of device ID in target configuration for Android devices

- libs/utils/trace.py
Pass normalize_time down to trappy.  Sometimes it's useful to have the
same time between kernelshark and trappy.  Trappy supports this with
normalize_time but the Trace class doesn't allow you to specify it.  Let
Trace accept this parameter and pass it down to trappy.
close #57
> libs/utils/trace: add support for normalize_time

- libs/wlgen/wlgen/workload.py
This track the most recent version of devlib which provides a critical fix for CGroups usage on Android targets.
> Update devlib cgroups

- src/shell/lisa_shell
0bb8438f0157 ("lisa_shell: add support for multiple instances") introduced a third parameter to lisa-ipython.  After the network interface you can set the port.  Document it in lisa-ipython's usage.
> lisa_shell: document the PORT parameter of lisa-ipython

- src/shell/lisa_shell
When running inside vagrant with the default VirtualBox configuration, the host accesses the vm using a virtual ethernet link.  `lisa-ipython start` uses loopback as the default interface, which makes the ipython server bind only to loopback and refuse connections from the host.
Make `lisa-ipython start` bind to eth0 by default, which is the more sensible default in that environment.
Reported by @raw-bin
> lisa_shell: bind ipython server to eth0 when run from a vagrant environment

- libs/utils/energy.py
- libs/utils/env.py
- target.config
The names of the nodes for energy have changed - they are no longer
of the form 'a53_energy' for the CPU clusters, but are now called
'BOARD_LITTLE_ENERGY'. Likewise, all the other sensor names are different
but we don't monitor those in lisa.
In order to support those, add a new device named juno2. Once both types
are no longer in circulation, the names can be changed.
Signed-off-by: Chris Redpath <chris.redpath@arm.com>
> lisa: Add support for new Hwmon node names with 'mainline' driver

- libs/utils/trace.py
If the user does not want the time to be normalized we need to compute the plot
window range boundaries.
Also, the user could specify a window tuple with start and end times. These
values are relative to the basetime of the trace and therefore the plot window
boundaries are computed accordingly.
> libs/utils/trace: compute time ranges for plot window

- ipynb/android/Android_Workloads.ipynb
- libs/utils/android/__init__.py
- libs/utils/android/screen.py
- libs/utils/android/workload.py
- libs/utils/android/workloads/jankbench.py
- libs/utils/android/workloads/youtube.py
A set of common functionalities are usually required to run workloads on an Android target.
Some workloads are so simple which can be automated with few ADB commands.
However, the precise sequencing of these commands can affect the experiment. For example, remembering to tune specific Screen settings or start/stop energy sampling once specific events happens are simple functionalities which however are easy to forget if coded from scratch each time.
This patchset adds an initial set of Android related modules which have to goal to factorize some of the most common setting for few interesting workloads.
> Android utils and workloads

- libs/utils/trace_analysis.py
trace_analysis automatically saves image for method
trace_analysis::plotTasks(), which conjunct task name for saving image
file. But sometimes task name has special characters (like ':', '/'), so
Linux cannot support these characters for file name.
So this patch is to fix this failure to convert special characters to
underline '_'.
> libs/utils/trace_analysis: fix for image file name

- src/shell/lisa_shell
In patch 3f5553ffb2 "lisa_shell: teach lisa-update to update itself" it
search "ARM-software/lisa.git" to generate "remote_name".
But in some case, for example clone LISA's repo with below command:
git clone https://github.com/ARM-software/lisa; so finally it cannot
find out "ARM-software/lisa.git" due without suffix ".git".
To compatible both cloning methods, change to search
"ARM-software/lisa".
> lisa_shell: fix lisa-update failure

- libs/utils/env.py
TestEnv only creates one object per session.  When you are
experimenting, sometimes you need to change target_conf or test_conf and
create a new TestEnv.  Add a force_new flag to force TestEnv to
reinitialize the platform with the new values.
> libs/utils/env: Pass a force_new flag to force the creation of a new TestEnv

- libs/utils/trace_analysis.py
The current version of plot tasks is broken in case a task name matches
multiple PIDs. In that case a plot:
1. report in the title just the first PID
2. mix data for all PIDs in the same plot
This patch fixes this issue by actually producing a set of plots for each
different PIDs which match a specified task name.
Moreover, it is now possible to define the list of tasks to plot by specifying
either task names and/or PIDs.
> Fix plot tasks

- libs/wlgen/wlgen/rta.py
Successive conf() calls were making rta accumulate delay parameter
(since the scaled values was saved in the internal dict). This was also
causing the value to eventually overflow.
Fix it by always using the dict parameter directly to initialize phases.
> rta: do not accumulate delay

- ipynb/examples/trace_analysis/TraceAnalysis_FunctionsProfiling.ipynb
- libs/utils/trace.py
- libs/utils/trace_analysis.py
Since this commit:
082a82c7c ftrace: add support to report function profiling data
devlib provides support to profile a list of specified kernel functions
by specifying them in the TestEnv configurations, e.g.
```python
my_conf = {
#... other settings ...
"ftrace" : {
"functions" : [
"select_task_rq_fair",
"pick_next_task_fair",
],
},
}
```
This patch adds the required support from the LISA side to parse the
functions profiling data and return a data frame for a specified list
of functions.
With such a configuration, functions profiling data can be collected using
this API:
```python
stats_file = os.path.join(te.res_dir, 'trace.stats')
te.ftrace.get_stats(stats_file)
```
This series adds the required LISA support in Trace and TraceAnalysis to:
1) build a DataFrame out of kernel functions …
> Add API and example Notebook for Kernel functions profiling

- .gitignore
- Vagrantfile
This series addresses the following issues:
* Avoiding warnings with locales
* Installing Android SDK under `lisa/tools` if not yet present and setting `ANDROID_HOME` properly
Solves one of the warnings reported in #102.
close #117 
> Vagrantfile: update virtual machine creation

- tests/eas/hmp_parity.py
The hmp parity tests don't have descriptions and are very cryptic for those that have no previous experience with EAS.  Add a simple description.
> tests/eas/hmp_parity: Add descriptions for tests

- Vagrantfile
The latest devlib depend on wrapt.  Install it.  This fixes #145.
> Vagrant: install wrapt

- Vagrantfile
There are some failures with the Android SDK installation in Vagrant: the PATH is not correctly set and devlib complains that the build-tools are missing.
> Vagrantfile: fix PATH for Android and install Android SDK build tools

- tests/stune/smoke_test_ramp.py
Similar to 55eee3cb6f1f ("tests/eas/hmp_parity: Add descriptions for tests") but for `tests/stune/smoke_test_ramp.py`.  Improve the description so that people don't have to read the code to have an idea of what the test does.
> tests/stune: Document the stune smoke_test_ramp test

- ipynb/examples/energy_meter/EnergyMeter_ACME.ipynb
- libs/utils/energy.py
While reviewing #121 I ended up collecting so many mods which at the end the code has completely changed. This is the new version of the ACME EnergyMeter I would be (reasonably) happy to get merged. Main updates are:
- More abstract configuration interface which allows also to give a custom name to each channel
- Run-time check for required dependencies (i.e. iio-capture)
- More robust code to stop eventually already running iio-capture instances
- Using "standard" energy.json file to report just the energy of each measured channel
- Renaming and cosmetics to match the rest of the file
By merging this PR we can close both #121 and #72
> Add ACME EnergyMeter

- Vagrantfile
Since 6bfc3ba409b7 ("libs/utils/energy: add support for remote IIO energy
probing") you need psutil if you want to import `TestEnv`.
Install it in the vagrant box to avoid the following error when running
tests:
```
[LISAShell lisa] \> nosetests -v tests/eas/hmp_parity.py:ForkMigration
Failure: ImportError (No module named psutil) ... ERROR
======================================================================
ERROR: Failure: ImportError (No module named psutil)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName
addr.filename, addr.module)
File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
return …
```
> Vagrantfile: install psutil

- libs/utils/env.py
- libs/utils/platforms/nexus5x.json
This is a first set of small modifications to support a more generic interface to defined boards configurations. It still does not completely support a custom number of clusters but should be a nice starting point to merge, especially to simplify the description of new boards integration.
TODO: add support functions required to have a complete "more than two clusters" support.
> Add generic boards support

- libs/wlgen/wlgen/workload.py
Commit 655e3f03767c ("libs/wlgen/rtapp: fix calibration for versions of Android >=N") added an innocent 2>&1 at the end of the rt-app command.  When running rt-app with cgroups enabled on an Android system this gets executed as the following monstrosity:
```
adb -s 10.1.210.35:5555 shell '(echo '\''/data/local/tmp/bin/shutils cgroups_run_into / '\''\\'\'''\''/data/local/tmp/bin/rt-app /data/local/tmp/devlib-target/run_dir/mixprof_00.json 2>&1'\''\\'\'''\'''\'' | su); echo "$?"
```
The fact that the `2>&1` has a host of `'` after it ends up confusing the shell, which tries to redirect the stderr to file descriptor `1'` , which doesn't exist and it fails (but crucially, devlib doesn't see that it
failed, `echo $?` returns 0).
If we add a space between `2>&1` and its single quotes, we avoid …
> libs/wlgen/workload: fix rt-app execution when using cgroups

- ipynb/tutorial/UseCaseExamples_SchedTuneAnalysis.ipynb
The bart check of util estimation in the UseCaseExamples_SchedTuneAnalysis notebook starts with code to add the sched_boost_task event filtered by comm back to the trappy `FTrace` object
which is a hack.  This is needed because trappy's grammar module couldn't do it when the notebook was originally written.  trappy learned to apply filters in its `Parser()` object in version 5.7.0, which led to
the simplification of the similar SchedTune test in b9d488f58ab2 ("tests: simplify stune's boosted utilization signal test").
Apply a similar change to the UseCaseExamples_SchedTuneAnalysis ipython notebook.  This way the test is simpler and we educate our users on the ability to use filters with the Analyzer :heart:
> ipynb: remove the add_parsed_event() hack in the UseCaseExamples notebook

- libs/wlgen/wlgen/workload.py
This is a series of updated related to wlgen workload executions which mainly:
- simplify the code to run commands in foreground/backgroud
- allows to specify different CPUs and/or CGroups at each run (without need to reconfigure the workload)
This series should also fix and close #162
> Update workloads execution

- src/shell/lisa_shell
A "lisa-update all" command fails if submodules are not pointing to
the current tracked head. This can happen if you worked on a submodule's
branch.
This patch ensure that all submodules are reset to point the current
tracked head just before doing an update all. This should ensure to:
1) the submodules reset fails in case there are not commited changes
2) update all checks just for pending modifications in the main project
> lisa_shell: ensure submodules are in sync

- tests/eas/hmp_parity.config
- tests/eas/hmp_parity.py
A number of improvements to fix tests failing when they shouldn't. The new "Offload migration and idle pull" test needs an updated bart.  Trappy also has a new version, so update both modules while we are at it.
> EAS HMP-parity test improvements

- tests/eas/acceptance.config
- tests/eas/acceptance.py
90% is too forgiving for EXPECTED_BIG_BUSY_TIME_PCT, it allows traces to
pass the "Bug cpus are fully loaded" test even when 100% tasks have run
on LITTLE CPUs while big CPUs are idle for significant periods.
Since traces contain a perdiod of inactivity at the beinning, to require
99% busy time it's necessary to adjust the trace window over which
assertions apply. Instead of starting at t=0 we use
SchedMultiAssert.getStartTime to find the time at which the first task
started, and use that as the start of our window.
> tests/eas/acceptance: Increase required busy time for idle pull test

- tests/eas/acceptance.config
- tests/eas/acceptance.py
The window for `test_little_cpus_run_tasks()` was loosely defined as just the migrator delay, which doesn't take into account the time it takes for rt-app to spawn and create its tasks.  After fa4bce7359ec ("tests/eas/acceptance: Increase required busy time for idle pull test"), the test is more strict, so increase the accuracy of the window to meet the new restrictions.
> tests/eas/acceptance: increase accuracy of little cpus test in the Offload Migration testcase

- tests/eas/acceptance.py
An EXPECTED_BIG_BUSY_TIME_PCT got missed out from the recent renaming commit.
> tests/eas/acceptance: fix missed rename of config value

- tests/eas/acceptance.config
- tests/eas/acceptance.py
Where this sysctl is present, if it isn't enabled the EAS wake path
views the CPUs as a flat list, so that LITTLE CPUs are not necessarily
preferred over big when selecting CPUs for a low-load task. Set it, so
that the WakeMigration and other tests can pass.
Since this flag isn't used by the mainline-integration version of EAS,
we only attempt to set it if the procfs file is present.
> tests/eas/acceptance: enable sched_is_big_little sysctl

- Vagrantfile
Let Android SDK Manager decide what to update.
Apparently with filters the build-tools are not installed. This seems to
solve the issue.
> vagrant: do no apply filters to update Android SDK

- tests/eas/capacity_capping.config
- tests/eas/capacity_capping.py
Add a simple test to verify that if the maximum frequency of the big cpus is reduced, busy threads are moved from the bigs to the littles.  When the maximum frequency is allowed to go back to the absolute
maximum, check that the threads are migrated back to bigs.
> tests/eas/capacity_capping: Add a capacity capping test

- libs/wlgen/wlgen/rta.py
rt-app uses pthread_setname_np(3) to set the names of tasks on the
target [1]. This interface limits thread name length to 16 characters
including the null '\0'.
Although rt-app prints a message on the target, the workload execution
goes ahead when the provided task names are too long, and the tasks are
named "rt-app". This means they are not found when later examining the
trace.
Therefore, raise an exception on the host to prevent this situation
arising.
[1] https://github.com/scheduler-tools/rt-app/blob/dcaf5a04aa63b69d8b5e174d10a9e459f88772cf/src/rt-app.c#L152
Fixes https://github.com/ARM-software/lisa/issues/200
> libs/wlgen/rta: Limit task name to 15 characters

- libs/utils/env.py
For Linux targets you need a 'host' parameter to set up the SSH
connection. If it's missing, the error appears at the end of a deep dark
call stack.
Add an explicit check before constructing the LinuxTarget so it's
more obvious what you did wrong when this param is missing.
> libs/utils/env: Explicitly check 'host' setting is present for Linux

- Vagrantfile
`ln` fails if the link already exists. Since 7cbc9233 (Vagrantfile: Bail
out of provisioning if anything fails) this breaks re-provisioning a VM
with `vagrant reload --provision`.
Check if /home/vagrant/lisa already exists and if it does, leave it
alone.
> Vagrantfile: Don't try to create extant link

- libs/utils/executor.py
- libs/utils/test.py
- tests/eas/acceptance.py
- tests/eas/acceptance_fork_migration.config
- tests/eas/acceptance_offload_idle_pull.config
- tests/eas/acceptance_small_task_packing.config
- tests/eas/acceptance_wake_migration.config
This is a successor to https://github.com/ARM-software/lisa/pull/197
Differences from v1:
- Numerous minor changes and cleanups I won't list
- Split the changes into more commits
- In Executor, the `experiments` dict was changed to be a NamedTuple-
- Removed `test_first_cpu` from `EasTest` and replaced it with a helper method, subclasses must explicitly call it
- `experiment_test` decorator moved to `utils.test` (where `LisaTest` is)
- Added missing `is_big_little` logic to `EasTest`
- Fixed the logic `EasTest` that attaches trace file locations to test failure messages
----
- Refactor/enhance the Executor class; most importantly enable the "experiments" to be saved so that test objects can refer back to them in `test_` methods
- Add an EasTest class abstracting the common operations for …
> Rework EAS acceptance tests to inherit from LisaTest  v2

- libs/utils/test.py
We don't need to validate the config; Executor already does
that. Therefore we don't even need to parse it - just pass it blindly on
to Executor. That way we can use raw dicts instead of JSON files.
> libs/utils/tests: Don't look at Executor config in LisaTest

- libs/utils/trace.py
If no cpu_idle events are reported for a particular CPU (but there are
cpu_idle events for other CPUs), assume that the CPU was never used
during the period of trace event collection.
> libs/utils/trace: Fix getCPUActive signal for fully-idle CPUs

- libs/utils/analysis/idle_analysis.py
Not too sure if this is the best approach.. maybe we should come up with a more generic solution (`Trace._sanitizeCpuIdle`?). I haven't investigated whether `_dfg_cluster_idle_state_residency` is affected by the same issue (in my brief tests it didn't seem to be but good chance that's coincidence).
This is kind of a similar issue to this: https://github.com/ARM-software/lisa/pull/220
> idle_analysis: Fix idle residency when idle events are sparse

- tests/eas/acceptance.config
- tests/eas/acceptance.py
This tunable is required to use the "sched" cpufreq governor (schedfreq)
Note that this isn't required right now - the acceptance tests use the performance governor - but we should expect people to want to change that.
> tests/eas/acceptance: set sched_initial_test_util

- libs/utils/platforms/pixel.json
Source of info: arch/arm/boot/dts/qcom/msm8996.dtsi in Android MSM
kernel, tag android-7.1.0_r0.3 (76cdcfd5b0c3)
https://android.googlesource.com/kernel/msm.git/+/android-7.1.0_r0.3/arch/arm/boot/dts/qcom/msm8996.dtsi#157
> platforms: Add JSON config for Google Pixel

- libs/utils/executor.py
I looked [here](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security-Enhanced_Linux/sect-Security-Enhanced_Linux-Working_with_SELinux-Mounting_File_Systems.html) to try and figure out if there's a mount option that could let us fix this properly. It sounds like adding `context=u:object_r:shell_data_file:s0` to the mount options should fix the issue but it gives me:
```
'schedtest' is read-only
mount: 'schedtest'->'/data/local/tmp/devlib-target/run_dir': Permission denied
```
I decided to be pragmatic about it - rather than reading great dusty tomes of SELinux documentation to figure out incantations I suggest we just put it in permissive mode.
> Fixes for Executor

- libs/utils/trace.py
I'm not really sure what the original intention for these methods in `Trace` were so I might be off the mark here, but this seems to basically be the behaviour I'd expect from trace. That is I would expect to be able to have a trace parsed and then simply call `getTasks` to see which tasks were found.
This should make it more convenient for tests to figure out PIDs of tasks run during workload experiments so that they can do analysis. 
For example: https://github.com/ARM-software/lisa/blob/2f1eef3bdbd539380684472eb2e02b58584551cd/tests/eas/load_tracking.py#L111
> Trace: Automatically populate the task/PID map when sched_switch enabled

- src/shell/lisa_shell
So we don't mess up the terminal too much for people with pale backgrounds.
> lisa_shell: Reset terminal colours in PS1

- libs/utils/analysis/frequency_analysis.py
- libs/utils/analysis/idle_analysis.py
- libs/utils/trace.py
Some people have been using a later trappy version than the one specified in the submodules. That version contains a commit by me that breaks LISA's idle analysis module, so here's a fix for it.
> Update trappy and fix cpu_idle

- libs/utils/env.py
- libs/utils/executor.py
With this commit, tests that use rt-app workloads need not explicitly
specify 'rt-app' in the 'tools' field of the TestEnv test configuration.
This adds an `install_tools` method to the TestEnv class.
---
This might be considered a bit of a hack? The generic solution would probably be to fix this in the workload class(es) by passing a TestEnv (rather than a Target) to their `__init__.py` that they can use to install the required binary.
> executor/env: Install rt-app automatically if required

- libs/utils/executor.py
- tests/eas/acceptance.py
Note that if you manually stopped services before running the LISA tests, this will re-start them after running the workload. We could modify this to actually look at the services that are running before we run `stop` to determine if we should re-`start`, but I don't want to add that complexity unless it's definitely necessary.
> executor: add flag to freeze userspace while running experiments

- tests/eas/preliminary.py
This introduces a test suite that provides early-warnings that the
platform does not have the preliminary setup necessary to support EAS
---
supersedes https://github.com/ARM-software/lisa/pull/235
CC @credp
> tests/eas/preliminary: Add initial EAS suitability check

- libs/utils/env.py
Seems I failed to test my previous commit that changed this code.
By the way, 'wloads' doesn't go in the target config any more so this is sort of redundant, but I'm not going to fix that here.
> env: Fix check for rt-app calibration requirement

- libs/utils/env.py
As I noted in my [previous PR](https://github.com/ARM-software/lisa/pull/267), the 'wloads' field doesn't belong in the TestEnv config, it's an Executor thing. So fix that here. This fixes issues where calibration doesn't get run.
> TestEnv: fix calibration check again

- libs/utils/energy.py
ACME energy meter supports multiple channels and initialization
of such channels uses a map that associates a channel id with a
human understandable name.
The current code translate this information to a fixed length array
and this causes a problem if devices ids are not contiguous or if not
all devices are in use, e.g.
"channel_map" : {
"Device1" : 1, # iio:device1
}
Keep the map association as is by using a dictionary instead of an array.
> libs/utils/energy: fix initialization of ACME

- Vagrantfile
- install_base_ubuntu.sh
This provides an installation script that can be used to set up VMs and containers on Ubuntu-like systems. Then modifies the Vagrantfile to use that script.
I've kept this as 3 commits so that I can keep track of the changes from the script I was given by another team, but I'm happy to squash before merging.
> Factor out dependency installation script

- libs/wlgen/wlgen/workload.py
- This parameter should be a Devlib object for collecting traces, not a Trappy
object for parsing them.
- Add note to say where you can get one of these things from.
> Workload: fix docstring for `ftrace` param

- libs/utils/energy.py
For the ACME energy probe the init funtion call of the superclass
did not specify the results directory so the sample file would go
by default to /tmp/, where it might be overwritten if two tests are
ran at the same time, where the channels used have the same channel
descriptors.
For safety, pass the res_dir to the init call and have the output
file stored there before being moved to the specified output folder.
> utils/energy.py: call superclass init with res_dir

- src/shell/lisa_shell
This allows extra arguments to be passed to nosetests to customise its behaviour
beyond what LISA provides.
> lisa_shell: Pass all arguments to nosetests in lisa-test

- libs/utils/env.py
Some cleanups and simplifications for TestEnv.
Generally:
- Simplify a load of conditionals by 
- Removing the unnecessary case where `conf`/`test_conf` is `None`
- Using `d.get('foo')` instead of `if 'foo' in d and...`
- Use set operations to simplify stuff
I think this also has a sneaky bugfix for installing rt-app dependencies via `install_tools` but I haven't replicated that presumed bug.
> Env cleanup

- libs/utils/test.py
- src/shell/lisa_shell
- tests/eas/acceptance.py
- tests/eas/heavy_load.py
- tests/eas/rfc.py
- tests/sfreq/smoke_test.py
- tests/stune/smoke_test_ramp.py
This adds some stuff to the LisaTest API so that test classes can be instantiated in notebooks, the tests can then be run and the results interactively analysed to figure out the causes of test failures. An example of such a notebook will be submitted separately.
Summary of the changes:
Awkwardness to allow instantiating `LisaTest` objects:
- Add `$LISA_HOME` to `$PYTHONPATH` so the `tests` package gets discovered
- Add an empty `LisaTest.runTest` method so that `__init__` ([inherited from `TestCase`](https://docs.python.org/2/library/unittest.html#unittest.TestCase)) can be called without the 
`methodName` parameter.
- Rename the "abstract" EasTest base class to avoid it being detected as a test class by nosetests
API additions
- A "public" `LisaTest.runExperiments` method to trigger …
> LisaTest API additions for running tests from Notebooks

- tests/lisa/test_wlgen.py
- tests/lisa/test_wlgen_perf.py
- tests/lisa/test_wlgen_rtapp.py
This provides simple tests that use a localhost target to test running workloads and ensuring that the required output was produced. Although this certainly isn't an in-depth test of the wlgen system it should provide us at least a basic canary to check things aren't totally broken.
> Wglen self-tests v2

- libs/utils/executor.py
- libs/utils/test.py
- tests/eas/rfc.py
- tests/sfreq/smoke_test.py
- tests/stune/smoke_test_ramp.py
Existing SchedTune and SchedFreq tests are now working again with the mods to use the new interfaces required by the executor module.
This fixes also the executor's recent support to spawns moultiple tasks with a single wload spec.
> Fix some tests broken by recent executor refactoring

- ipynb/tests/Frequency_Invariance_Test.ipynb
- tests/eas/load_tracking.py
See [commit message](https://github.com/ARM-software/lisa/commit/3224f5a344ddd8f16967fd6163289bd160d3f63e).
This test is quite simple so I've tried to make it an example of how we could design tests so that they can be used both from the command line as automated tests, and via notebooks as diagnostic/analysis tools. That means I've also added a couple of commits to make instantiating tests from notebooks easier. The interface for doing that is a bit bizarre (instantiate then `setUpClass`) but it works. The test/target configuration is also not inline in the notebook, instead the config comes from `target.config`. I personally like that, but it might be confusing invisible magic to someone new to LISA.
> Add frequency invariant load tracking test 

- .travis.yml
- src/shell/lisa_shell
This adds a barebones YAML config for Travis and a fix that allows travis to detect failures from `lisa-test`. You can see an example run against my repository here: https://travis-ci.org/bjackman/lisa/builds/201980373 (running the wlgen tests that were recently meged).
> Add support for Travis CI

- libs/utils/analysis/latency_analysis.py
- libs/utils/analysis_module.py
We have pretty old issues, like #7, which should address the cleanup of the codebased to remove any hardcoded dependency on bL platforms. This is not such a big refactoring but still these are small fixes for parsing of SMP generated traces which needs to be merged to get new APIs like
https://github.com/ARM-software/lisa/pull/302
working properly for example using systrace on Pixel phones.
> Fix platform parsing

- libs/utils/trace.py
There is a new format for the sched_energy_diff trace event in EAS code in the
Android common kernel:
https://android.googlesource.com/kernel/common/+/6aab3e4a9266fb661638e37ad4745573aff6de5c%5E%21/
Add support for parsing this format in Trace, by translating equivalent field
names and making unmatched fields optional.
-----
I have only done the bare minimum to allow me to use LISA to parse traces from kernels containing these events. I haven't checked that the result of this method makes any sense, neither with the existing events nor the new.
> trace: Handle new field format for sched_energy_diff

- .travis.yml
- ipynb/tests/Generic_EAS_Tests.ipynb
- libs/utils/energy_model.py
- libs/utils/env.py
- libs/utils/platforms/hikey_energy.py
- libs/utils/platforms/juno_energy.py
- libs/utils/platforms/pixel_energy.py
- tests/eas/__init__.py
- tests/eas/acceptance.py
- tests/eas/generic.py
- tests/lisa/test_energy_model.py
See the commit messages for the [first](https://github.com/ARM-software/lisa/commit/399cdfff3c112836408f03346832df52008779d7) and [fourth](https://github.com/ARM-software/lisa/commit/37918fade84d389a6df2183ac02892fe3fef898d) commits for more detail on what this PR aims to introduce. In short, this aims to allow automatically running tests for any given synthetic workload and platform. 
This looks like an enormous PR, and it is... but a lot of the added lines are `.ipynb` noise or boilerplate in the [provided](https://github.com/ARM-software/lisa/commit/399cdfff3c112836408f03346832df52008779d7#diff-6a86319666706547b6bb03baf38e4916) [platform](https://github.com/ARM-software/lisa/commit/399cdfff3c112836408f03346832df52008779d7#diff-ac2a5c8c78e008f3791e81447c911ca6) …
> Energy model-based tests, RFC v2

- libs/utils/__init__.py
- libs/utils/android/__init__.py
- libs/utils/android/benchmark.py
- libs/utils/android/workload.py
- libs/utils/android/workloads/jankbench.py
- libs/utils/android/workloads/uibench.py
- libs/utils/android/workloads/youtube.py
- logging.conf
- tests/benchmarks/android_jankbench.py
Here is a series which improves the current support for Android workloads execution to easy the
customisation of their execution as well as the integration with a possible CI back-end.
Main modifications are:
1. refactoring of `libs/utils/android/workloads/*` to support both energy sampling and trace events
2. introduction of a new base class `libs/utils/android/benchmark.py` which allows to wrap and customise the execution of one of the supported Android worklaods
3. addition of an initial example of Jankbench benchmark customisation to evaluate how different CPUFreq governors affect energy and performances
The newly introduced benchmark can be executed from a local LISA shell using for example this command:
```shell
[LISAShell lisa] \> python tests/benchmarks/android_jankbench.py \ …
```
> Android benchmark refactoring

- libs/utils/energy_model.py
- tests/eas/load_tracking.py
- tests/lisa/test_energy_model.py
- Adds some handy members to the `EnergyModel` class
- Make the existing load_tracking test code more generic
- Add a test that runs a workload on each different type of CPU in the system and checks that the utilisation signal from the scheduler is scaled according to each CPU's capacity.
> Add test for CPU invariant load tracking

- ipynb/examples/android/benchmarks/Android_UiBench.ipynb
- ipynb/examples/android/workloads/Android_Workloads.ipynb
- libs/utils/android/workloads/uibench.py
- tests/benchmarks/android_uibench.py
test_name had a forced suffix of 'Activity' with the assumption that all
test names would have this appended at the end in the app. This is not
true for two activities; ActivityTransition and
ActivityTransitionDetails.
As such, the suffix has been removed and the user now must specify the
full name of the test name. In addition, the default list of tests have
been updated to reflect this.
> uibench: test_name suffix broke Transition tests

- libs/utils/test.py
`runTest` is detected and run as a test by nosetests, since it has 'Test' in the
name. We just added it so that we could instantiate LisaTest objects
easily (like `t = FreqInvarianceTest()`). Instead, remove it and override
`__init__` with a default `methodName` that doesn't have 'test' in the name.
Fixes https://github.com/ARM-software/lisa/issues/306
> LisaTest: Replace runTest with overridden __init__

- libs/utils/android/system.py
- libs/utils/android/workload.py
Systrace expects either a time argument to know how long it has
to record traces, or an <enter> keystroke to end the tracing.
Added a 'fake' <enter> keystroke so tracing may be started
and stopped without a predefined duration.
> libs/utils/android: Add systrace timeless support

- tests/eas/generic.py
None of the tests are big.LITTLe specific any more, they can all usefully be run
on any target, so remove this flag.
Also note that the `and not test_env.nrg_model.is_heterogeneous:` is broken
because `test_env` is not defined here, as..
Reported-by: Valentin Schneider <Valentin.Schneider@arm.com>
Fixes: 113ce343beab "tests/eas: Un-factorise code that is no longer shared"
> tests/eas/generic: Remove unused skip_on_smp flag

- libs/utils/energy_model.py
- libs/utils/env.py
- libs/utils/platforms/hikey_energy.py
- libs/utils/platforms/juno_energy.py
- tests/eas/generic.py
This parses data out of procfs and sysfs. This data is currently only available in product-codeline EAS (i.e. AOSP common kernel). 
Unfortunately I'm adding 200 lines here without any new tests, because this code depends on having a target, and a localhost target isn't going to have the required data in sysfs. This is a hard thing to test as even mocking the filesystem poses non-trivial problems due to the way the code uses globs. Perhaps the best solution to this is testing with an emulated target using ARM Fast Models or similar.
----
The reason for the tweaks to the Hikey and Juno data are so that I could validate this code by reading the Hikey and Juno models and checking that the result matched the hard-coded one.
> Add feature to extract EnergyModel from target data

- tests/eas/preliminary.py
Just checks if the energy model is exposed in `/proc/sys/kernel` and if it isn't, tells you two possible reasons why not.
> tests/eas/preliminary: Add test for presence of energy model

- tests/eas/generic.py
- Enable `cpu_frequency` event.
- Disable schedutil ratelimiting.
- Automatically pick sched or schedutil governor if it's available, preferring schedutil.
> Tweaks for the Generic test suite

- tests/eas/generic.py
tests/eas/__init__.py was removed.
Fixes: 113ce343beab "tests/eas: Un-factorise code that is no longer shared"
> tests/eas/generic: Fix broken import

- src/shell/lisa_shell
Jupyter notebook 4.3.1 introduces protection from cross-site request forgeries,
requiring API requests to either:
- originate from pages served by this server
(validated with XSRF cookie and toekn)
- authenticate with a token
This patch adds support to generate a random token and report it in the
complete URL thus allowing the user to properly get the complete address
where her server is running.
> lisa_shell: fix reported URL

- libs/wlgen/wlgen/rta.py
RTA.__postrun uses the `tasks` attribute to find the logfiles to pull from the
target. So when using a custom rt-app configuration, set up this attribute in a
similar way to "profile" workloads.
> rta: Detect task names when using custom wload

- libs/utils/env.py
It may happen that a target's EAS energy model is "invalid", e.g. because its
active state power values are not monotonically increasing with frequency (this
is the case with Google Pixel). In this case the EnergyModel construct will
throw a ValueError.
Don't fail to start LISA in that case, just print a warning.
> TestEnv: Don't error if target's energy model is invalid

- libs/utils/executor.py
Freezing init doesn't seem to break anything. Also scenarios have been observed
where Android's init eats CPU while the rest of the system is frozen. Maybe
it's spin-waiting on a lock or mailbox for a frozen process.
> executor: Don't except `init` from freezing on Android

- libs/utils/energy_model.py
If the kernel is exposes a partial sched_domain hierarchy we should raise a
TargetError that can be caught and ignored, rather than a KeyError (which should
indicate a bug in EnergyModel).
> energy_model: Raise TargetError instead of KeyError if sysfs is messed up

- libs/utils/energy.py
For some platforms (e.g., JunoR2) channel labels in the energy report
might differ from channel names, and this raises a runtime error (even
if energy is correctly reported).
Fix it by always use channel labels.
Fixes: a41a48dfabb7 ('libs/utils/energy: Slightly improve error for missing hwmon channel')
Signed-off-by: Juri Lelli <juri.lelli@arm.com>
> libs/utils/energy: Fix error reporting for missing hwmon channel

- src/shell/lisa_shell
Newer versions don't have an ipython command any more.
> lisa_shell: Use jupyter command if ipython command doesn't exist

- tests/eas/preliminary.py
_check_work_throughput() had an unused 'margin' variable. It's now used
to check that each CPU does at least 10% more work at its highest OPP
than at its lowest. This also 'fixes' false positives induced by the
fact that every sysbench run is not quite identical, so we could be
comparing 99 events vs 100 events, which should be a failure.
Also added a list of (freq -> work) in the test output should it fail,
which can help figuring out what is causing the failure
> tests/eas/preliminary: WorkThroughput improvement

- libs/utils/android/benchmark.py
- tests/benchmarks/android_geekbench.py
- tests/benchmarks/android_gmaps.py
- tests/benchmarks/android_jankbench.py
- tests/benchmarks/android_uibench.py
- tests/benchmarks/android_vellamo.py
- tests/benchmarks/android_youtube.py
It is usually handy to be able to run the same benchmark multiple times
(e.g., to do statistics on results).
Add a --iterations command line parameter to implement the feature.
Signed-off-by: Juri Lelli <juri.lelli@arm.com>
> android/benchmark: add iterations command line parameter

- libs/wlgen/wlgen/rta.py
- tests/lisa/test_wlgen_rtapp.py
Currently, under the assumption that the calibration is an int, we don't quote
it. However it may be a string like "CPU0" in which case we _do_ need to quote it.
Also add a test for this case.
> wlgen/rta: Fix calibration value string replacement

- libs/utils/energy.py
numpy.arange() was being used to index the energy-measurements df.
This method has some issues where the 'stop' value may or may not
be included in the returned set, i.e:
arange(0.8, 1.0, 0.1) could return [0.8, 0.9, 1.0]
BUT
arange(0.7, 1.0, 0.1) could return [0.7, 0.8, 0.9]
(not tested for these values but it is the problem being encountered)
This could thus create n indexes for n-1 values, which would cause an
exception.
numpy.linspace() is more predictible than arange(), as the 'stop' value
can explicitly be included or excluded (excluded by default).
This commit introduces linspace().
> libs/utils/energy: Fix df indexing

- libs/wlgen/wlgen/rta.py
Governor tunables are reset to default when switching governors.
This is particularly relevant when using the Executor, which calls
te.calibration() after _setup_cpufreq. If the calibration has not
been done yet, that will result in setting the performance governor
then restoring the previous governor. However if _setup_cpufreq set
up any tunables they are not currently restored. This commit fixes
that.
----
While I'm touching this code, I've also updated it to use the `iter_domains` method I added to devlib.
> Save & restore cpufreq governor tunables for RTA calibration

- libs/utils/trace.py
In some traces it can happen that a CPU wakeup is immediately followed by a CPU idle event (or the other way around) which have the exact same timestamp. Such a condition means that the wakeup time (or sleep time) is essentially null and thus it can be discarded.
Nevertheless, such a condition generates an exception when we try to re-index the active signal, e.g. in HeavyLoadTest::test_tasks_spread.
This fixes these issues by ensuring that the cpu_active time series does not have spurious wakeup/idle events. The number of (eventually) dropper events is reported in output for logging purposes.
> utils/trace: drop spurious wakeup/idle events

- libs/utils/android/workloads/gmaps.py
- libs/utils/target_script.py
This is in response to #329. The example that goes with it is on GMaps, but this uses another PR from devlib (https://github.com/ARM-software/devlib/pull/127), so it cannot be merged yet but is up for comments.
I've looked at the traces on kernelshark, and adbd is running only at the very start & end of the workload, which is a good start.
> Target-side command execution

- libs/utils/energy_model.py
People have energy models with kinks in the data and still need to
use this module. Just print a warning instead of erroring out.
> energy_model: Don't error if energy model data is dodgy

- .gitmodules
The Github Wiki is not easily accessible to users willing to contribute by
adding documentation or fixing typos. Let's pull in the wiki as a local
subproject so that it should be more easily accessible to users willing to
contribute.
> submodules: add LISA wiki as a subproject

- libs/utils/energy_model.py
This helper executes a "cat" command to read a large number of files
in one go. In order to avoid this command becomind too long for ADB
to cope with, it was written to use glob patterns to cat the files,
instead of the explicit paths (which it knows).
However a user has reported an issue with this approach, which I
suspect is because the order of the paths returned by `find` differs
from the order of the shell's expansion.
Fix the cat command to explicitly list the paths to be read. In order
to avoid the command-too-long issue, write the potentially-too-long
command to a file, push it, and execute it via sh.
> energy_model: Fix read-multiple-files helper

- libs/utils/executor.py
- libs/utils/test.py
Currently when you run a LisaTest with experiments_conf['iterations']!=0, the
test assertions are made for every experiment and the test is failed as soon as
any experiment produces a failure. Only the first failure encountered is
displayed.
With this patch all the results for each wload/conf pair are aggregated.
The problem is only solved across iterations: if multiple wloads or confs fail,
only the first wload/conf pair that was found to have failed will be
displayed.
> LisaTest: Improve running tests with multiple iterations

- libs/utils/test.py
- src/shell/lisa_shell
This is a kludge, but I think doing this properly basically requires
implementing our own Nose test runner, or even our own test-running
framework entire. In the short term we really need this feature.
nosetests doesn't provide a way for the user to pass command-line
arguments to the test. To get around this, this commit adds a
parameter to lisa-test that sets an environment variable, which
LisaTest then reads to set or override the iterations count.
---
This will go pretty nicely with https://github.com/ARM-software/lisa/pull/348 but they are technically independent.
> Add feature to set test iteration count from command line

- tests/eas/generic.py
20% is too forgiving, it lets you get away with keeping small tasks on the big
CPUs on some big.LITLE platforms.
> tests/eas/generic: Reduce energy threshold 20%->5%

- tests/eas/generic.py
How "big" a periodic task is depends not only from its duty-cycle but
also from the period.
A 20% periodic task, can be considered "small" from the scheduler time
perspective if it's period is around the scheduler latency. However it's
completely different if its period if of 500ms. In this case indeed the
task runs for 100ms at each activation, thus it should better be
considered quite big.
In our synthetics tests, let's fix the period of all the generated
workloads such that how big a task is can be properly defined by just
setting its duty-cycle. We pick 16ms because it's the most interesting
time constant for a standard Android rendering pipeline.
> tests/generic: use 16ms period for all workloads

- libs/utils/android/screen.py
On some devices I see screen on just takes a tad bit longer, and the MENU
keycode that does the screen unlock is sent too soon. Giving a small delay
seems to fix it for me.
Change-Id: I5f4d258e53e2a6766a3bfb5a92cf073cbcceab59
> screen: Give time for screen on

- tests/eas/generic.py
- Relax energy threshold for ThreeSmallTasks because we don't really know what
the ideal task placement is (don't expect energy model to be very accurate
here), just want to sanity-check the placement (e.g. hopefully fail if tasks
are all on big CPUs).
- Allow RampDown test a larger threshold to allow for hysteresis in
down-migration.
- Remove the energy test from the TwoBigThreeSmall, this is similar to the
ThreeSmall Tasks case but more extreme - let's just check that the throughput
was provided but ignore the energy-aware placement as our estimation is very
likely wrong for this workload.
> tests/eas/generic: Tweak criteria for passing tests

- libs/utils/android/workloads/camera_preview.py
This workload starts the camera app, waits for a few seconds and then starts data collection (trace, energy etc).
I also have a workload that starts the camera app after tracingStart, I call it 'cameraStartup' however I don't know how useful it is for upstream so I dropped it. cameraStartup was useful for me when I was debugging the time it takes from the start of the camera app to the first preview frame.
> workloads: add a new camera preview workload

- libs/wlgen/wlgen/rta.py
BUG: RTA workload property delay_s will cause kernel userspace rt-app segmentation fault.
Configure the correct RTA settings to meet the RT-APP requirement ( up to commit=a9a0c6c )
Signed-off-by: Zhifei Yang <zhifei.yang@arm.com>
> Bug: RTA property delay_s will case kernel segmentation fault #449

- libs/wlgen/wlgen/rta.py
- tests/lisa/test_wlgen_rtapp.py
This example:
wl = RTA(te.target, 'mywl', calibration=calib)
wl.conf('profile',
params = {'t': Periodic(delay_s=3, duration_s=1) +
Periodic(delay_s=2, duration_s=1)).get()})
Should semantically result in
1. 3s delay
2. 1s of periodic behaviour
3. 2s delay
4. 1s of periodic behaviour.
But part 3 (the second delay) will be ignored due to the way we use
the "delay" field.
We could probably fix this using a "sleep" event, but to keep things
simple let's just disallow this type of composition, unless we later
find that we need that feature.
> rta: Disallow invalid composition of delayed tasks

- libs/utils/env.py
We need the cpufreq module to configure rt-app. We don't currently
have an easy way to detect in advance that we need to do this
calibration, so for now just add cpufreq as a default module. This is
already done for all the known boards, this commit just makes it a
default for unkonwn boards too.
> env: Add cpufreq to default modules

- libs/wlgen/wlgen/rta.py
- tests/lisa/test_wlgen_rtapp.py
Need to review this more carefully (maybe I can add a unit test for this) but submitting PR now because otherwise I'll definitely forget about this.
The current code breaks calibration for big.LITTLE systems if the 'bl' devlib module isn't loaded, hence marking this as a bug.
> rta: Fix setting up "calibration" field in rt-app global conf

- libs/utils/env.py
Bug: Fails to install tool file path without ABI prefix
Solution: Append the tool file path with ABI prefix to tools_to_install list.
Signed-off-by: Zhifei Yang <zhifei.yang@arm.com>
> Bug: Fails to install tool file path without ABI prefix #445

- ipynb/examples/android/workloads/Android_Gmaps.ipynb
Some of Trappy's API has been changed, so this brings the notebook
in line with these changes.
> ipynb/examples/android/workloads: Fix Gmaps notebook

- libs/utils/energy_model.py
- tests/eas/preliminary.py
The cpufreq.get_domain_cpus method has been renamed to
get_related_cpus. Update to master to bring in that change and update
LISA's usage of the renamed function.
> subodules: Update devlib to latest master

- libs/utils/env.py
We need this for reading the EnergyModel from the target. Ideally we
would just enable that module when we need to read the EnergyModel
but we can't do that at the moment, so just enable it by default
> env: Add cpuidle to default modules

- libs/utils/trace.py
If the `data_dir` argument is a singe path element (e.g. just 'trace.dat') then
os.path.dirname(data_dir) is ''. When we later attempt to save a plot to a
subdirectory we end up adding '/<filename>.png' to this empty string, which
means we attempt to save a file to the root directory and get a permissions
error.
Fix this by just explicitly preventing self.data_dir from being empty.
> trace: Fix plotting when no data dir specified

- libs/utils/executor.py
Freezing these tasks is causing the kevin chromebook to reboot.
> add two tasks to skip-freeze list for linux

- libs/utils/platforms/__init__.py
- libs/utils/platforms/juno.json
This lets you parse traces, using platform data, without having to connect to a target.
```
from trace import Trace
from libs.utils.platforms import juno # I don't have a juno board here, but I know my trace was collected from one
trace = Trace(juno, 'trace.dat', ['sched_switch'])
```
> Convenience names for platform data

- libs/utils/trace.py
- tests/lisa/test_trace.py
- tests/lisa/traces/trace.txt
The last event's duration will always be set to NaN, because the time
delta is computed as (next_event time - cur_event time). Since the
plotOverutilized() method uses the time deltas to render the
overutilized flag, this can break things: if the last status event
reports overutilized=1, it won't be rendered (see https://github.com/ARM-software/lisa/issues/433).
This fixes that by 'manually' setting the duration of the last event.
> utils/analysis: Fix overutilized plotting

- libs/utils/analysis/frequency_analysis.py
By default, area_under_curve uses method='trapz' which implicitly
does a linear interpolation of the data. This is not desirable for
cpu_frequency, which changes ~instantly and stays constant until the
next data point.
> frequency_analysis: Fix calculating avg_freq

- libs/utils/trace.py
Some CPUs' active signals may begin earlier than others. In that
case, despite the fillna, we may still have NaNs, which break the
reduce() call. Therefore just drop rows with NaNs.
> trace: Drop NaNs from CPU active signal in getClusterActiveSignal

- libs/utils/trace.py
This fixes an oversight of 3dead2f2b36c589aae2d2f56a573bcac0bc3b8bc:
since we now use absolute windows with normalize_time=False, we must use start_time along with the given window to determine the x time range.
> trace: Fix plotting when normalize_time=False

- tools/wltests/test_series
In the current implementation, the --reboot_timeout parameter is
documented for lisa-wltest-series but cannot be used. This is fixed by
this PR.
> test_series: fix --reboot_timeout parameter

- tests/eas/generic.py
Each test in generic.py has a time duration set to 2s. However,
the "time_s" entry for rt-app ramps is the duration of each step,
and not the duration of the whole ramp. As such, each ramp test
lasts 26 seconds instead of 2.
This commit sets the whole duration of each ramp test to 2s.
> tests/eas/generic: Lower ramp tests duration

- libs/utils/wa_results_collector.py
When run wa_results_collector class, it report the error for log:
AttributeError: 'WaResultsCollector' object has no attribute 'log'
This is caused by the typo "self.log.warning", so fix typo to
"self._log.warning".
> utils/wa_results_collector: Fix typo for log

- tools/wltests/README.md
Fix README file for kernel path option to "--kernel_src".
> tools/wltests: README: Correct kernel path option

- tools/wltests/platforms/hikey620_android-4.4/build_images
- tools/wltests/platforms/hikey620_android-4.4/definitions
- tools/wltests/platforms/hikey620_android-4.4/flash_images
- tools/wltests/test_series
Tested using Jankbench with the bootloader provided with the following AOSP factory image: [https://developers.google.com/android/images-preview#hikey](https://developers.google.com/android/images-preview#hikey)
More recent bootloaders require a UEFI-specific boot.img and won't be compatible with this implementation.
Instructions to set-up the board:
[https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Installation/LinuxFactoryImage.md](https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Installation/LinuxFactoryImage.md)
Userspace image (and ramdisk) from the latest linaro AOSP build supporting the 4GB EMMC Hikey620:
[http://builds.96boards.org/snapshots/hikey/linaro/aosp-master/509/](http://builds.96boards.org/snapshots/hikey/linaro/aosp-ma …
> wltest: add support for Android 4.4 on Hikey 620

- tools/wa_user_directory/config.yaml
The correct section name to configure trace-cmd should
have a "-" instead of a "_" so let's fix that.
> wltest: fix trace-cmd parameters

- tools/wltests/agendas/sched-evaluation-full-traced.yaml
- tools/wltests/agendas/sched-evaluation-full.yaml
- tools/wltests/agendas/sched-evaluation-small.yaml
Without an ID being explicitely set, WA3 will generate a generic wkNNN lable
for each test, where NNN is their position in the agenda file.
Let's set a meaningful name for each workload so that logs and output
folders are more easy to read.
> tools/wltests: set a valid ID for each test

- libs/utils/test.py
- libs/wlgen/wlgen/utils.py
- tests/eas/load_tracking.py
This PR adds a couple of tests for making sure PELT signals (right, util_avg_task only is tested) works as expected.
The tests rely on the PELT simulator that @derkling is adding to bart (see https://github.com/mdigiorgio/bart/tree/pelt_simulator). As a consequence, we should have that merged before we accept this.
I'm posting this now to get some initial feedback on the approach, that's why I set it as WIP.
> Add tests for PELT

- libs/utils/analysis/latency_analysis.py
This can be useful to look at the behaviour of a task (or from another point of view, the behaviour of the scheduler regarding this task) and to have an overview of how much time a task has spent on each CPU.
I'm not entirely too sure about with task states should be considered in the runtime sum - from my understanding, anything but sleeping should be accounted, but I could be wrong on that.
> Analysis/latency: Add task CPU residency utilities

- libs/utils/energy_model.py
- tests/lisa/test_energy_model.py
This allows using the data in the EAS energy model to estimate the
power usage of the system at any given moment. The hope is that this
can be used as a weak proxy for power performance on systems where
measuring real power consumption is not possible.
CC: @joelaf
---
This is another PR that looks huge but it's pretty much all docstrings, comments, and test..
I had some performance issues, and rather than doing any 'real' optimisation I just memoized away the slow code. That got me to 20s for a 78Mb trace on my slow laptop (2nd gen i5), so let's see if that's fast enough. If not I can optimise it. Unfortunately there isn't really a single critical component that's slowing it down (I've profiled it), the whole module is just full of slow code.
> Add estimation of energy from trace

- tools/wltests/test_series
The ADB device name passed to test_series is currently used to flash and
reboot the board using ADB and Fastboot. However, it is not yet passed
to WA3 which then complains whenever several ADB devices are connected.
This commit fixes this behaviour by making the config fragment currently
used for the ACME more general and appending a "device_config" section
to it.
> test_series: fix WA invocation with multiple devices

- libs/utils/analysis/latency_analysis.py
Trace::getTaskByPid() returns task name with 'str' type, if use join()
to apply for the string, it inserts comma between every chars and the
task name is not readable.
This patch is to directly use name string from Trace::getTaskByPid();
and rename variable 'task_names' to 'task_name'.
> latency_analysis: Fix task name

- tools/wa_user_directory/config.yaml
These might or might not be set as default by workload-automation.
Make sure they're selected by making them default in the LISA
config.
> config.yaml: add csv and status as default result processors

- libs/utils/env.py
There are checks like if "nrg_model" in platform but they return True if
a None value is present. So make such that such a value is never
present.
Signed-off-by: Leonard Crestez <leonard.crestez@nxp.com>
> TestEnv._init_platform: Remove nrg_model key from platform if None

- libs/utils/analysis_module.py
This makes stuff like plotClusterFrequencies work even if no nrg_model
is available, all that is required here is a list of big and small cpus.
Signed-off-by: Leonard Crestez <leonard.crestez@nxp.com>
> utils/analysis_module: Initialize _big/little_cpus even w/o nrg_model

- ipynb/wltests/sched-evaluation-full.ipynb
The energy plots should enable users to quickly see whether their new
feature under test saved energy or not. Although defining "saving
energy" can be tricky, looking at the average value is often a sensible
option to do that, so let's use it by default.
> ipynb/wltests: sort energy plot by average instead of 99% percentile

- libs/utils/android/system.py
- libs/utils/android/workloads/pcmark.py
It started off from @ionela-voinescu's #321 but ended up quite different.
So far only the "work" benchmark is supported, as I haven't found a clean way (yet) to start the other benchmarks.
Once the benchmark is done, a .zip archive is pulled from the device, scores are extracted from a .xml file and finally dumped in a .json file.
> libs/utils/android/workloads: Add PCMark workload

- libs/utils/target_script.py
- logging.conf
- tests/eas/cpuhp.py
The CPU hotplug procedure changes many data structures used by the scheduler and interferes with the task placement, hence resulting in all sorts of bugs. This PR enables testing under CPU hotplug stress as an attemp to trigger those bugs. CPUs are plugged in and off in a random (but repeatable) way while a workload is running. For now, the test is considered passing if the workload simply completes its work and if the system doesn't halt.
One thing worth discussing about the current implementation: the hotplug stress starts at the very beginning and stops at the very end. It does not stop nor restart between iterations of the test, which means that iteration `n` and `n+1` are not assessed over the same hotplug sequence. Not sure if this is a problem or a feature ...
One last thing, I'm …
> test/eas: add test under CPU hotplug stress

- tools/wltests/test_series
The current implementation of test_series checks out a kernel based on
the first 7 characters of its sha1. However, this truncation creates an
ambiguity whenever 7 characters aren't enough to identify a unique kernel.
In this case, an error is raised.
This commit fixes this behaviour by removing the hardcoded truncature
and cutting the sha1 to be checked out up to the first space found in
the series file.
> test_series: fix checkout with ambiguous sha1

- libs/utils/executor.py
Freezing this process wouldn't cause any critical crash, but it would
make the tests last much longer than needed (e.g. 1 minute for a
5 seconds rt-app task).
> utils/executor: Don't freeze 'dbus' on Linux targets

- tools/wltests/platforms/hikey620_android-4.4/flash_images
- tools/wltests/platforms/hikey960_android-4.4/flash_images
A typo was introduced in d32f7592544190beb11bbbaacf5fa67834fc5ff6, which
would prevent the flashing from happening, but the rest of wltest would
still run. As such we'd end up comparing the exact same kernels.
> wltests: Fix flashing for hikeys 960/620

- tools/wa_user_directory/config.yaml
By default, WA's list of events to collect is the following:
['sched*', 'irq*', 'power*', 'thermal*']
As a result, the trace files are generally massive. This becomes an
issue when sched-evaluation-full-traced is in use as the result folder
can be > 25GB per kernel, mostly because of the trace files.
To avoid this, let's select by default a list of trace events we care
and drop all the others. This global parameter can be overridden in each
agenda if needed by setting 'trace_events' in the global section.
> wa/config: specify the list of default trace events to collect

- libs/utils/executor.py
- libs/wlgen/wlgen/rta.py
- tests/eas/load_tracking.py
This patches add support for new tests where the tasks can migrate from one cpu to another during different phase. The goal is to ensure that the utilization is migrated at the same time as the task.
It adds also two scenarios of cpu migration tests.
> Cpu migration

- libs/utils/android/system.py
For workloads with collect='systrace', systrace can now be
configured in a similar manner to ftrace. Simply add a systrace
dict in the TestEnv conf like so:
"systrace" : {
"events" : [
"gfx",
"view",
"sched",
"freq",
"idle"
],
"buffsize" : 100 * 1024
}
> libs/utils/android: Add systrace configuration

- libs/utils/wa_results_collector.py
Sometimes, the power measurement file is null. Just skip it in this case
because panda doesn't correctly handle that case
> skip null size power file

- tests/stune/smoke_test_ramp.config
- tests/stune/smoke_test_ramp.py
Negative boosting is used to reduce the performance of a task
by running it at a lower frequency. It is supported in the kernel
and hence adding this patch for validation.
Signed-off-by: Divya Lingaiah <divya.lingaiah@intel.com>
> tests/stune/smoke_test_ramp: Add negative boost test for schedtune

- tools/wltests/test_series
Now that we have Pixel2 sopport on WLTests, here is an initial working support for the Monsoon EM, which
can benefit all our friends using that energy meter to benchmark Google phones ;-)
> Add (initial) MONSOON support to WLTests

- tools/wltests/test_series
Since a signed tag has a SHA1 that differs from the one associated with
the commit to which it is referring, this was causing false negatives
when verifying the correspondence between the current kernel version of
the device and of the local repository.
This patch, when there is no correspondence between the current SHA1 of
the repository and the kernel of the device, verifies if there is a tag
pointing to the same SHA1 and performs the comparison with it.
It also inverts the substirng checking: it checks if the SHA1 of the
kernel is contained in the SHA1 of the repo, since this last should be
longer.
In order to do this, the following steps are followed:
- take the kernel release (uname -a), e.g.
"4.4.88-g0e6b355-00003-g36e8d7f";
- take the last element, considering '-' as separator, …
> Check for kernel SHA1 to match also signed tags'

- libs/wlgen/wlgen/utils.py
- tests/eas/load_tracking.py
These patches add tests and support for tests where tasks are migrated from one cgroups to another during their execution and control that the utilization of each cgroups is migrated with them.
> cgroups migration test

- libs/wlgen/wlgen/rta.py
Fix: The cpus of the phase of a task was never assigned in the
case where the cpu was given as an int and has the value 0.
Signed-off-by: Elieva Pignat <Elieva.Pignat@arm.com>
> rta.py: fix phase cpus assignment

- tests/eas/generic.py
Change the task utilization so that the optimal placement agrees with
EAS placement. 50% was high enough for EAS to move the task to a big
CPU, but the optimal placement was expecting a little CPU. With 70%,
they both agree that it should be on a big CPU.
> generic.py: fix EnergyModelWakeMigration

- tests/eas/load_tracking.py
The task affinity is overidden when the task is moved into another
cpuset cgroup. To avoid the task being migrated on another random CPU,
we constrain the cpuset itself instead of the task so we are sure tasks
of the involved groups will always run on the same CPU.
> load_tracking.py: fix cgroups migration

- libs/utils/analysis/frequency_analysis.py
- libs/utils/trace.py
- tests/lisa/test_trace.py
Allows the plotting of clocks using the linux common clock tracing
infrastructure tracing. Chart shows the periods the clock is on or
off, as well as frequency information.
Test: run examples/android/workloads/Android_YouTube.ipynb, which
Test: now has a plotPeripheralFrequencies() example
> libs/utils: add frequency plotting for peripheral clocks

- libs/wlgen/wlgen/rta.py
- tests/eas/load_tracking.py
The file that contains the description of the tasks was written before
the test are launched and read back after the tests run to control the
that the result of the test are coherent.
The problem is when the test is run for several platforms in parallel
the file containing the json description may have been overwritten by
another platform test and may not contain the description of the test anymore.
To avoid the problem of sharing this file, the tasks descritpion is saved in
a variable in the test class and the file containing the json is no more read.
Signed-off-by: Elieva Pignat <Elieva.Pignat@arm.com>
> CPU Migration test: fix parallelism issue

- libs/utils/env.py
- target.config
- tests/lisa/test_executor.py
Allow the user to collect extra trace events that are not strictly required to run the test but are useful to support investigation of test failures.
> Debug trace events

- libs/utils/trace.py
Events name must be ascii strings. Unicode strings will break trappy, so
encode them to ascii first.
> trace.py: Fix events name type

- src/shell/lisa_colors
- src/shell/lisa_shell
When LISA_SHELL_DISABLE_COLORS environment variable is set to some
value, LISA shell won't use colours. This feature is useful when using
LISA in automated environment where shell colours are not supported.
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>
> shell: allow disabling colors

- libs/utils/analysis/latency_analysis.py
Right now, the plotLatency method returns a DF with statistics for the
latencies of a specified task. However, sometimes we could be
interested in getting these stats without necessarily plotting all the
data.
Let's move the statistics DF generation into an internal _get_latency_df
method, which can then be used by the plotLatency but also from an
additional DF gatter: _dfg_latency_stats_df.
Thus, this will make available a new:
trace.data_frame.latency_stats_df()
which just return the overall latency stats for the specified task.
> latency_analysis: add statistics getter method

- libs/utils/target_script.py
- tests/eas/cpuhp.py
The CPU hotplug test is full of useless dependencies which silently talk
to the target (rt-app, freezing userspace, ftrace, ...). When the target
crashes during the hotplug stress, requests sent to the target because
of the above modules can hang indefinitely, or fail miserably. That is
an issue since, in the specific case of the hotplug test, we would like
to classify these crashes as test failures.
Remove all the dependencies by overwritting the runExperiments method of
LisaTest in order to avoid using an Executor. The test spawns a bash
script on the target that plugs CPUs in and out, and does _nothing_ on
the host side during a (configurable) amount of time before checking if
the target is alive.
> Fix cpuhp test

- tests/eas/preliminary.py
Recent EAS versions (with the simplified EM) do not rely on the
SD_SHARE_CAP_STATES flag to be set anywhere. As a result, the
preliminary test checking its presence fails, although the kernel
configuration is fine.
Fix this by making preliminary.py check the kernel version to skip
the test if it doesn't make sense.
> tests/preliminary: Skip SD_SHARE_CAP_STATES test when applicable

- libs/utils/energy_model.py
The v5 of the simplified EM doesn't expose the 'capacity' file in sysfs.
Fix this by checking if the file exists, and re-compute those values
form within LISA if not.
> WiP: energy_model: Fix loading simplified EM from target w/o 'capacity'

- tests/eas/st_hold.py
Use the frequency behaviour when running rt and cfs tasks
to determine if the schedtune hold functionality is working
properly.
Signed-off-by: Chris Redpath <chris.redpath@arm.com>
> Add schedtune hold synthetic test

- tests/eas/generic.py
The RampDown test happens to fail on TC2 with a 16% or 17% energy delta,
while the behaviour is clearly correct. This happens because of the
overutilized band. The exact location of that band depends on the
capacity ratio of CPUs of the platform, but the RampDown test
configuration is hardcoded, without taking the platform's topology into
account. As a result, the test is hitting more sensible part of the
power-perf curve on some targets than others, and that is the cause of
the problems observed on TC2.
Fix this by tweaking the threshold at a level that should suit TC2
better. A proper fix would be to compute the threshold depending on the
EM of the target, but this is difficult to do in the current state of
the test framework. The new test framework should handle these scenarios
a lot …
> tests/eas/generic.py: Tweak RampDown energy threshold

- src/shell/lisa_shell
modern linux systems don't have /sbin/ifconfig installed by default (but /sbin/ip, instead)
> error message in lisa_shell is not very instructive, /sbin/ifconfig might not be installed

- tools/wltests/agendas/example-exoplayer-simple.yaml
- tools/wltests/agendas/example-rich.yaml
- tools/wltests/agendas/sched-evaluation-full-traced.yaml
- tools/wltests/agendas/sched-evaluation-full.yaml
- tools/wltests/agendas/sched-evaluation-small.yaml
1. pcmark needs internet access, so disable airplane mode
2. use v2.4 of exoplayer inline with sched-evaluation-full.yaml
3. s/test/test_ids/ in jankbench attributes
> Update wa agendas to fix several breakges

- libs/utils/wa_results_collector.py
If no kernel path has been defined, kernel_refs is empty and
df['kernel_sha1'].replace(kernel_refs) fails
Add sha1 as kernel ref in case no kernel path is provied
Signed-off-by: Vincent Guittot <vincent.guittot@linaro.org>
> WaResultsCollector: fix no kernel path case

- src/shell/lisa_shell
ifconfig returns
inet adr:172.17.0.1
instead
inet addr:172.17.0.1
when language is set to fr-FR
update the sed command to support it
Signed-off-by: Vincent Guittot <vincent.guittot@linaro.org>
> lisa-ipython: shell support fr-FR language

- lisa/env.py
- lisa/exekall_customize.py
- tools/exekall/exekall/engine.py
- tools/exekall/exekall/main.py
Save the work done on all CPUs for a given capacity, and then reduce
that to the minimum work to avoid comparing with sys.maxsize
Also add annotated `from_testenv` method.
> Minor improvements for scheduler/sanity.py

- lisa/env.py
Rename --platform into --platform-info to be consistent with exekall and
avoid confusion with devlib Platform objects.
> env: Align TestEnv.from_cli with exekall

- lisa/energy_model.py
- lisa/utils.py
Registering the class properly can only be done in a metaclass, which
would complicate the use of abc.ABC for example.
Also, not all classes are required to inherit from Serializable, which
means that many classes would not get the tag stability provided by
registering the class explicitely. Instead, the dotted name of the
classes are used.
Therefore, we avoid registering the class altogether, and will rely on
keeping stable class names when backward compatibilty is needed. That
can be done by keeping the old name available.
Existing yaml_tag class attributes are removed since they are no longer
exploited by ruamel.yaml
> utils: Avoid registering the class in ruaml.yaml

- doc/kernel_tests.rst
- lisa/exekall_customize.py
- lisa/tests/kernel/scheduler/eas_behaviour.py
- lisa/tests/kernel/scheduler/load_tracking.py
- lisa/tests/kernel/scheduler/misfit.py
- lisa/tests/kernel/test_bundle.py
* Refactor TestBundle and RTATestBundle to split the test aspects from
the from_testenv aspect. This is needed for some tests that create a
collection of bundles.
* Refactor the *Invariance test in load_tracking to enable test_slack
and avoid code duplication
> tests: Refactor TestBundle and LoadTracking

- doc/doc_requirements.txt
Commit f3c2fbc13a9b ("bisector: add dbus dependencies") added an
apt dependency that RtD cannot satisfy, so let's make a minimal
requirements file just for doc building.
> doc: Add a doc_requirements.txt for ReadTheDocs

- doc/conf.py
Not only is this no longer needed, it broke ReadTheDocs.
> doc/conf: Remove path setting

- doc/conf.py
e67cb1b31607 ("Merge pull request #658
from douglas-raillard-arm/lisa-next") broke ReadTheDocs, and while it
looked like it was due to some misuse of sys.path (which was removed
in ac2765933156 ("doc/conf: Remove path setting")), it looks like we
do need to play with sys.path to keep ReadTheDocs up and running.
> doc/conf: Reintroduce sys.path setting

- lisa/tests/kernel/scheduler/eas_behaviour.py
Reduce to 25% of a LITTLE CPU instead of 50% to match more closely the
lisa legacy version of the test.
> eas_behaviour: Make TwoBigThreeSmallTask small task smaller

- lisa/env.py
Use the current utils.MutliSrcConf API instead of an old one that has
been replaced.
> env: Fix TargetConf.to_map()

- lisa/tests/kernel/scheduler/load_tracking.py
Make it available to run under exekall, in addition to
FreqInvarianceItem.test_task_load_avg.
> tests: load_tracking: Annotate FreqInvariance.test_task_load_avg

- tools/exekall/exekall/_utils.py
Correctly import the enclosing package of __init__.py instead of trying
to import it as a regulard module. That can happen when using "**.py"
wildcard on a whole python package.
> exekall: Allow user to point to package/__init__.py

- lisa/utils.py
Since it had a missing parameter and no implementation on super(), just
remove it. We can revisit that if state lost during serialization is not
acceptable when doing deep copies.
> utils: Remove Serializable.__deepcopy__

- lisa/env.py
- lisa/platforms/platinfo.py
- lisa/tests/lisa/test_conf.py
- lisa/utils.py
* Remove redundant information exposed in `YAML_MAP_TOP_LEVEL_KEY` and the actual top-level key descriptor in `STRUCTURE`
* Add self tests for `utils.MultiSrcConf` (along with `TargetConf` and `PlatformInfo`)
> Cleanup and add self tests for utils.MultiSrcConf

- setup.py
- tools/exekall/setup.py
Since we removed a workaround that has been merged upstream, we need to
bump the required version of ruamel.yaml.
> setup.py: Update needed version of ruamel.yaml

- tools/bisector/bisector/bisector.py
Sanitize default values to match what really happens in the common case.
> bisector: sanitize early-bailout defaults

- lisa/conf.py
- lisa/tests/lisa/test_conf.py
- lisa/utils.py
* Allow using a key that is purely defined in term of other keys. That key cannot be added from a source, and is not shown when iterating over the `MultiSrcConf` instance. This avoids inconsistencies when adding it back as a source for example.
* minor cleanup in conf-related classes
> conf: Introduce derived configuration keys

- ipynb/wltests/sched-evaluation-full.ipynb
- lisa/wa_results_collector.py
- shell/lisa_shell
- tools/wltests/agendas/example-exoplayer-simple.yaml
- tools/wltests/agendas/example-rich.yaml
- tools/wltests/agendas/sched-evaluation-full-traced.yaml
- tools/wltests/agendas/sched-evaluation-full.yaml
- tools/wltests/agendas/sched-evaluation-small.yaml
I had a geekbench wltests folder somewhere, so I used that to test the collector & notebook.
While at it, carry over the last few fixes that went into master that we didn't get in next.
closes https://github.com/ARM-software/lisa/issues/702
> Fix wa_results_collector + wltests notebook, get last master changes

- shell/lisa_shell
Warn if PYTHONPATH is not empty, since it can interfere with venv. In
the worst case, it can lead to using a wrong version of e.g. bart that
would be installed somewhere else, leading to strange failures in LISA.
> lisa_shell: Check PYTHONPATH

- doc/overview.rst
- shell/lisa_shell
LISA_PYTHON can be set to any binary name prior to sourcing init_env.
This allows choosing the version of python to use, in case multiple
versions of python are installed on the system, especially for testing.
Cleanup the LISA banner to contain useful information only.
Also change the default name of LISA's venv so it includes the version
name.
NOTE: Since the default name of LISA's venv has changed, it will
reinstall pip packages when sourcing init_env. To avoid this, you can
run the following script before fetching the new version:
ver=$(python3 -c 'import sys; print("{}.{}".format(*sys.version_info))')
old_venv=.lisa-venv3
new_venv=.lisa-venv-$ver
mv "$old_venv" "$new_venv"
ln -s "$new_venv" "$old_venv"
> shell: Allow choosing Python version

- tools/post-checkout
post-checkout hook can break interactive rebase when returning a
non-zero code.
Still need to investigate a bit why this happens, since it's not clear from the git documentation (after quick reading, I may have missed some details):
https://git-scm.com/docs/githooks
> [RFC] tools: post-checkout: Fix git hook

- tools/check-setuppy
This allows tracking the installation "date" (git sha1) per-venv, so
multiple venv can cohexist without any interference.
In order to keep the currently recorded install commit:
cp "$LISA_HOME/.lisa-install-commit" "$LISA_VENV_PATH"
> check-setuppy: Record one install date commit per venv

- doc/conf.py
- external/devlib/devlib/bin/scripts/shutils.in
Since RTD fails to import lisa for unknown reason, even if it shares the
same venv, move the sys.path update before `import lisa`.
> doc: Make conf.py friendlier to RTD

- external/devlib/devlib/bin/scripts/shutils.in
- external/devlib/devlib/module/hwmon.py
- external/devlib/devlib/target.py
- external/devlib/doc/target.rst
- external/workload-automation/wa/framework/target/info.py
- external/workload-automation/wa/framework/workload.py
- external/workload-automation/wa/output_processors/postgresql.py
- external/workload-automation/wa/workloads/manual/__init__.py
- lisa/energy_model.py
The recent change to devlib's read_tree_values() API involve to fix the debugfs EM loader we have in Lisa. This PR does both at the same time.
> Update devlib and the EM debugfs loader

- .travis.yml
- install_base_ubuntu.sh
- shell/lisa_shell
- tools/scripts/travis_tests.sh
This still allows merge commits touching that location. The squashed
commit produced by git subtree is fine since it does not refer to
"external/" (path rewriting is done in the merge commit).
Also fixes various Travis issues.
> travis: check for commits touching external

- tools/exekall/exekall/engine.py
Propagate adaptor_cls when pruning a ValueDB.
> exekall: fix propagation of ValueDB.adaptor_cls

- tools/bisector/bisector/bisector.py
Since that DB is typically not reused a lot, it is pointless to spend
time optimizing it, as it can take a non-negligible amount of time.
> bisector: do not optimize Pickle output for -oexport-db

- tools/exekall/exekall/engine.py
Since there is nothing specific to ComputableExpression, move it into
the base class.
> exekall: move cloning to ExpressionBase

- lisa/tests/scheduler/eas_behaviour.py
Rename "slack" metric to "bad activations", since that metric is not a
mesure of time, but the proportion of bad activations.
> tests: eas_behaviour: Rename test_slack metric

- lisa/utils.py
- lisa/wlgen/rta.py
Make sure we get the expected number of steps, even if the `delta_pct` is not an exact divider of `(end_pct-start_pct)` but is slightly too large instead.  If the `delta_pct` is not an exact divider of `(end_pct-start_pct)`, we'll end up with a final phase that has a duty cycle that does not match `end_pct`. Force the last phase to have a duty cycle of `end_pct`.
Also add a debugging aid.
> Fix wlgen Ramp

- install_base_ubuntu.sh
Since we don't make rational use of the exit status, let's make it 0 for
now. This way, the infrastructure can be written to catch non-zero, and
everything will fall into place if we actually give it a meaningful
value.
> install_base_ubuntu: use 0 exit status

- doc/users_guide.rst
- lisa/trace.py
This was a useless alias to Trace.df_events().
Also update the transition guide.
> lisa.trace: Remove Trace.df()

- ipynb/examples/typical_experiment.ipynb
- lisa/analysis/latency.py
- lisa/analysis/tasks.py
- lisa/tests/scheduler/misfit.py
The current df_task_states forces the user to use the
```python
df[df.curr_state == TaskState.TASK_*.char]
```
pattern since we store the state's character into the dataframe to be
readable. Analysis code shouldn't have to deal with this, and using
pure ints will make filtering a bit faster.
Change the existing `df_task_states` to use pure ints, and add a
stringified sibling that uses the char representation of `TaskState`.
> analysis/tasks: Create an explicitly human readable df_task_states

- lisa/exekall_customize.py
- lisa/tests/scheduler/load_tracking.py
Unify CPU invariance and frequency invariance. The rational is:
* simplify the hierarchy of class in the test, and simplify the signature of functions by removing some defaults that are not always used depending on the execution path.
* Avoid misleading assumptions: if CPU invariance fail, that could just mean that invariance is broken for the highest frequency, since working freq invariance is a hardcoded assumption in the CPU invariance test. The new layout allows unbiased access to data.
* Allow running the test for any combination of CPU and frequency without arbitrary constraint
* The previous point also means that some duplicated was removed
Also, make sure only one set of InvarianceItem is collected and use that for both the aggregated and non-aggregated version of each test …
> Unify invariance tests

- tools/bisector/bisector/bisector.py
Calling the script directly imports it as __main__, which breaks
references to classes expected to be hosted in a module called bisector.
That behavior is normal for a python application and handled by a shim
create by pip in a PATH location, so bisector needs to be called through
it.
> bisector: disallow importing as __main__

- tools/lisa-buildroot-update-kernel-config
Use KConfig fragments, which are not trying to detect features of GCC
when merged. Using make oldconfig can break the configuration if the
host version of GCC is wildly different than the one used to
cross-compile. KConfig fragment also has the added benefit of reporting
what was modified in the config.
> buildroot: fix lisa-buildroot-update-kernel-config

- lisa/git.py
In find_shortest_symref() the subprocess command we use to get the list
of git branches returns a byte string. We then split this into byte
string 'name' and 'sha1' where this last will never match the SHA1
parameter passed in as a string.
Fix it be always decoding the strings we get as output of the subprocess
command.
> git: Decode branch names and sha1

- lisa/env.py
Since we need it in all cases, let's do it in LISA rather than having to
do it manually.
> lisa.env: Issue adb root when connecting to AndroidTarget

- lisa/energy_model.py
Since commit 9001b8f1a,
"ANDROID: sched: Add support for frequency/power energy model"
android-4.14 has been able to load a frequency-based energy model.
Adding this extended the capacity_state structure in
sched_group_energy with a new frequency member. This is automatically
reflected in the energy model tuples printed in procfs and so Lisa can
no longer load sensible Energy models from any target running
android-4.14 later than the above commit, although the error is not
detected so you do get an EnergyModel object which contains junk
capacity and power values.
We can figure out which kind of kernel we have by reading the number
of capacity states for a cpu and check how many items are in the
cap_state tuples so that we can handle 2 or 3 values per state
transparently.
Signed-off-by: …
> utils/energy_model: Fix loading EM from recent android-4.14 targets

- lisa/utils.py
- tools/bisector/bisector/bisector.py
Use yaml.representer instead of yaml.Representer, and the same for
Constructor. That avoids touching the class directly, and multiple YAML
loaders and dumpers can coexist in the same process.
> lisa/bisector: improve yaml init code

- libs/utils/env.py
Since all commands part of the systemd package are named
systemd-<something>, we need a more refined pattern in order to properly
freeze systemd-journald process for example.
> env: Freeze all systemd-* cmd except PID 1

- init_env
- shell/lisa_colors
- shell/lisa_shell
Sourcing init_env basically provides a set of bash functions (the lisa-*
commands) to the user and activates the python venv. However, that also
changes the PS1 and the colorscheme of the current shell, although this
isn't strictly necessary.
In order to give users the option of keeping their original shell
configuration, make the Lisa PS1 and colors depend on $LISA_SHELL_QUIET
not being set. While at it, list the env variables exported by init_env.
This results in:
queper01@queper01-lin:~/lisa$ LISA_SHELL_QUIET=1 source init_env
Activating LISA Python 3.6 venv (/data/work/lisa-next/.lisa-venv-3.6) ...
LISA version:
/data/work/lisa-next
branch: heads/lisa-shell-quiet
commit: 7f07c99ecec
Python version: 3.6
JupyterLab v0.35.4
No installed extensions
Environment variables: …
> shell: Introduce LISA_PRESERVE_SHELL

- doc/index.rst
- doc/internals.rst
- doc/pedantic_build.sh
- doc/users_guide.rst
- lisa/regression.py
- shell/lisa_shell
- tools/bisector/bisector/bisector.py
- tools/lisa-test
Add user-guide style documentation on synthetic tests workflows using bisector and exekall. That is meant to be a kind of reference flow, with documentation and command line examples, and without too much advanced content. More details about the concepts of exekall and bisector will be documented in their own documentation to come.
> document testing workflows

- lisa/conf.py
- lisa/env.py
- lisa/platforms/platinfo.py
- lisa/tests/base.py
- lisa/tests/scheduler/eas_behaviour.py
- lisa/tests/scheduler/load_tracking.py
- lisa/tests/scheduler/misfit.py
- lisa/tests/staging/load_tracking.py
- lisa/wa_results_collector.py
- tests/traces/plat_info.yml
- tests/traces/sched_load/plat_info.yml
- tests/traces/sched_load_avg/plat_info.yml
Avoid using TestEnv when not necessary, since it forces a live
connection to a target. For example, getting the RTapp profile of a test
only requires accessing PlatformInfo, and we should be able to get it
without any live connection to a target.
> lisa: Use PlatformInfo directly instead of TestEnv

- lisa/tests/scheduler/misfit.py
Remove now useless memoization that broke when passing a PlatformInfo.
> lisa.tests.scheduler.misfit: remove some memoization

- doc/users_guide.rst
- ipynb/examples/typical_experiment.ipynb
- ipynb/profiling/kernel_functions_profiling.ipynb
- lisa/tests/base.py
- lisa/trace.py
- lisa/wa_results_collector.py
- tests/test_trace.py
Make it clear that Trace() takes a path to a trace file as a parameter, and not a folder. The folder of the trace is still used by default for saving plots, so that does not really introduce any breakage.
> lisa.trace: Make API slightly clearer

- tools/bisector/bisector/bisector.py
CLI command line can be put in a file (one option per line), and the
file referenced using @myfile syntax:
https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars
> bisector: Learn @file CLI syntax

- doc/conf.py
- lisa/exekall_customize.py
Add an undocumented option to LISA's exekall glue to avoid having to
create a temp file with dummy content.
> doc: Cleanup creation of test list

- lisa/exekall_customize.py
- tools/exekall/exekall/customization.py
- tools/exekall/exekall/main.py
Allow arbitrary pretty printing of the list of expressions by the
exekall Adaptor.
Use that to list trace events used for each test.
> exekall: Add --list-trace-events

- setup.py
Issues with Python 3.5.1 have been resolved, see
https://github.com/tornadoweb/tornado/issues/2604
> setup.py: Drop tornado version requirement

- tools/bisector/bisector/bisector.py
Allows having a private bind mount of /tmp for the process tree, that is
then cleaned up when the scope unit is deleted.
> bisector: Use PrivateTmp=true with systemd-run

- setup.py
This time it's Jupyter that breaks, see
https://github.com/jupyter/notebook/issues/4439
> setup.py: Don't use tornado >= 6.0 (again)

- tools/bisector/bisector/bisector.py
Python 3.5 does not allow trailing comma in parameter list of function
definitions.
> bisector: Fix syntax issue on Python 3.5

- tools/extract-platinfo.py
Introduce a dummy CLI tool to get a plat_info.yml file suitable for
loading using either:
* PlatformInfo.from_yaml_map('plat_info.yml')"
* exekall run --conf plat_info.yml"
The CLI is a bit crippled as it does not allow using a different file
name than plat_info.yml, and it does not give the choice to evaluate
deffered values or not (i.e. RTapp calibration will be run, which can be
lengthy and useless depending on the use case).
We may want to introduce a `Target.add_argparse_args(parser)` function that would add the same arguments as `from_cli()`, but on an existing parser. That would allow simple scripts to be built on top of that, giving a chance to register a couple of parameters like the ones missing here.
Also, we may want to change the default log-level, to avoid having to specify …
> tools: Introduce extract-platinfo

- shell/lisa_shell
Print relevant environment variable when sourcing LISA shell, even in
colorful mode.
> shell: Always print relevant env var

- lisa/tests/scheduler/eas_behaviour.py
The big tasks in TwoBigThreeSmall are 80%. Because of this, EAS is kept
overutilized consistently, hence not giving the small tasks an
opportunity to be placed appropriately on little CPUs.
Although this is arguably something that could be improved on the kernel
side, it should also be noted that these tasks used to be 70% in the old
Lisa implementation, hence avoiding the problem altogether. Since the
change to 80% was not intended, and since the current test failures
don't teach us anything that we didn't know before, let's revert to 70%
tasks and avoid unnecessary pain.
> tests: eas_behaviour: Fix TwoBigThreeSmall duty cycle

- shell/README.txt
The lisa-report command is long dead. Don't mention it in lisa-help.
> lisa-help: Remove reference to lisa-report

- lisa/conf.py
- lisa/trace.py
- lisa/utils.py
When running under Sphinx, generate a reStructuredText docstring,
otherwise generate a plain text docstring.
EDIT: added also:
* key description placeholder in FtraceConf's docstring
* improved display of DEFAULT_SRC in Sphinx doc by using a dict instead of a MultiSrcConf instance
> lisa.conf: Adapt generated docstring to usage

- lisa/analysis/__init__.py
- lisa/target.py
- lisa/utils.py
Import submodules under their right full name, to avoid having clones of
the same module flying around, leading to unexpected issues.
> lisa.analysis: Fix import of submodules

- lisa/utils.py
inspect.stack() can sometimes raise IndexError under IPython for unclear
reasons. Since get_call_site is mainly used for debug logging, just
ignore that and report unknown call site.
> lisa.utils: Make get_call_site more robust

- lisa/tests/scheduler/load_tracking.py
The margin was recently reduced from 15% to 1% however it turns out that
this is a little bit too tight as minor shifts in time and interference
from kthreads regularly causes the 1% margin to be breached. 1.5% should
be sufficient to accommodate for those inaccuracies.
> lisa/test: Adjust PELTTask.test_{util,load}_avg_range margin

- tools/exekall/exekall/engine.py
* Allow getting a parent of an ExprVal by its type
* minor cleanup
> exekall: Add ExprVal.get_by_type()

- lisa/tests/scheduler/load_tracking.py
Do not rescale the signal specifically when it is the load.
> [RFC] lisa.tests: load_tracking: Invariance: Treat load like util

- lisa/target.py
Looks like we missed this in restructuring these classes. Remove the
superfluous target from the call.
Signed-off-by: Chris Redpath <chris.redpath@arm.com>
> lisa/target: fix specifying tools to install in target conf

- lisa/conf.py
Always return deepcopy of values when accessed through
`get_key`/`__getitem__`. That ensures that the configuration object is not
modified unexpectedly by one of its client in any way.
> lisa.conf: Use deepcopy in MultiSrcConf.get_key()

- doc/workflows/wltest.rst
- tools/wltests/test_series
So it turns out `repo sync -l` _can_ rebase stuff behind your back ... I'm a bit tired of playing around with this so I took the decision to stop messing around with `repo sync` and to just use proper repo branches (which is what I should have done from the start). That makes it a bit harder to test different toolchains and things like that, but that actually works properly for what we really want to do, that is, testing kernel changes.
I understand this whole thing is becoming more confusing than necessary (since I change my mind every week or so), so this PR also creates some basic wltest doc to explain how to use it for 'repo' targets.
For the future implementation of wltest we should drop the support for !repo targets I think -- Google now ship build scripts for all platforms we have …
> Fixes for wltests on P3

- tools/bisector/bisector/bisector.py
Avoid matching on 'http' URL scheme, which excludes https even though it
can work as well.
> bisector: Fix HTTPS handling

- lisa/target.py
Provide better dir() implementation, so that non-jedi ipython
autocompletion will list attributes of the underlying devlib Target
object.
> lisa.target: Implement __dir__

- lisa/conf.py
- lisa/exekall_customize.py
- lisa/platforms/platinfo.py
- lisa/target.py
- lisa/trace.py
Currently, using --conf multiple times will override user-specified keys from in the first files by the value found in the last file, or the default value if one exists. Fix that by ignoring default values when stacking configurations.
> exekall: Fix multiple uses of --conf

- tools/batch-rebase
Skip commits that are made empty by a previous equivalent commit instead
of failing.
> batch-rebase: Skip emtpy commits

- tools/bisector/bisector/bisector.py
- tools/bisector/setup.py
Avoid depending on external CLI tool, use the well-known "requests"
package for network HTTP operations.
> bisector: use requests package instead of curl

- shell/lisa_shell
Allow modifying them before source init_env like other variables, so
it's easy to pre-configure an environment.
> shell: Make LISA_CONF and LISA_RESULT_ROOT modifiable

- tools/bisector/bisector/bisector.py
Summar footer line for each step displays a number of pass test that
is not in line with the number of "passed" lines. Fix that by counting
the number of tests that had not other results than "passed".
> bisector: fix number of passed tests in summary line

- lisa/tests/base.py
- lisa/tests/scheduler/eas_behaviour.py
- lisa/tests/scheduler/load_tracking.py
- lisa/tests/scheduler/misfit.py
* Move get_rtapp_profile as an abstractmethod of RTATestBundle instead
of EASBehaviour
* Turn it into a property, to clean up __init__ signature, since it only
depends on plat_info attribute. That will make it clear what is part of
the minimal state of the object, and what is just derived information.
> lisa.tests: Turn rtapp_profile in a property

- tools/exekall/exekall/engine.py
Make sure tags do not contain [ or ] since that will break regex parsing
done on IDs.
> exekall: Strip [ and ] from tags

- tools/exekall/exekall/_utils.py
pickle.dumps() seems to also raise AttributeError sometimes, in addition
to pickle.PickleError:
AttributeError: Can't pickle local object 'SpawnBase.__init__.<locals>.write_to_stdout
> exekall: Make serialization test more robust

- lisa/tests/scheduler/eas_behaviour.py
This is where it would've been nice to operate on an instance of a class, so that we could use e.g. `self.{min,max}_cap_cpus[0]`, but we
have to live with classmethods (or
`cls.get_{min,max}_cap_cpus(plat_info)[0]`, which is too wordy for me).
> lisa/tests: eas_behaviour: Make rtapp profile construction less obfuscated

- tools/batch-rebase
Fix typo that made it delete the source repository instead of the temp
one.
> tools: batch-rebase: Fix typo

- lisa/regression.py
Correctly deduplicate both new and old FrozenValue lists so swapping
parameters will work as expected.
> lisa.regression: Allow swapping old and new list

- lisa/analysis/load_tracking.py
- lisa/exekall_customize.py
- lisa/tests/base.py
- lisa/tests/scheduler/load_tracking.py
- lisa/tests/scheduler/misfit.py
- lisa/trace.py
- tools/exekall/exekall/main.py
Introduce a metaclass for RTATestBundle that makes sure that the `ftrace_conf` of each subclass get at least all the events that are needed by their methods when they are decorated using `@requires_events`.
That avoids duplication of that information and also avoids writing it explicitly in docstrings, since sphinx will add the list of required events using the same information. That also allows setting the required events deep in the analysis functions that actually use it, and then pointing to that through the call chain using `@the_analysis_method.used_events`.
Also, use that for --list-trace-events that has been revamped and removed at the occasion (removed=there is no CLI option anymore since it is always done by default).
In this PR, I've "ported" synthetic tests to use that system, …
> ftrace events: use @requires_events on top of hand-specified ftrace_conf

- tools/wltests/android/mkdtimg
As reported in https://github.com/ARM-software/lisa/issues/853, the
current shebang can cause issues on systems where `python` defaults to
`python3`.
Make it obvious that this is a python2 script.
> tools/wltests: Fix mkdtimg python shebang

- lisa/trace.py
While we're not supposed to get duplicate timestamps (see
trappy.utils::handle_duplicate_index), these seem to still happen and
they throw pandas.DataFrame.loc[] off balance.
Use diff() + shift() instead of handcrafted equivalents. Performance
difference is insignificant, but at least we rely on a standard pandas
API.
> trace: Improve/fix add_events_deltas()

- lisa/trace.py
When a function is decorated mutlitple times with required events,
accumulate all the information in the top-level wrapper and discard
inner levels of wrappers.
> lisa.trace: Avoid stacking event checker wrappers

- doc/transition_guide.rst
- lisa/conf.py
- lisa/energy_meter.py
- lisa/utils.py
Use one configuration class per type of EnergyMeter, so that all keys
are properly described, and each of them will get an independent
configuration format to be used with `EnergyMeter.from_conf()`
Disclaimer:  that is untested code
Disclaimer 2: the change has only been done for HWMon as an example, the same would need to be done for the other classes as well.
Using it would give:
```
target = ...
res_dir = ...
conf = HWMonConf.from_yaml_map('path/to/hwmon_conf.yml')
emeter = HWMon.from_conf(target, conf, res_dir)
```
With `hwmon_conf.yml`:
```
hwmon-conf:
channel-map: ...
```
OR 
```
target = ...
res_dir = ...
emeter = HWMon(target, channel_map=..., res_dir=res_dir)
```
`HWMonConf` documentation would describe the available keys just like `FtraceCollectorConf` does.
> lisa.energy_meter: Cleanup EnergyMeter configuration

- doc/man1/bisector.1
- doc/workflows/automated_testing.rst
- tools/bisector/bisector/bisector.py
- tools/bisector/doc/man/man.rst
* Remove support for xUnit-based nostest output of LISA legacy
* Keep class aliases around for a while to be able to reload old reports
(both pickle and YAML)
* Reuse "LISA-test" step name for the exekall LISA test step, since the
old behavior (lisa legacy) of that name was not widely used.
> bisector: Remove support for LISA legacy

- doc/index.rst
The rst documentation now includes much more than just the API, so let's
rename the front-page title accordingly.
> doc: Update the name of the documentation

- tools/bisector/bisector/bisector.py
LISA-test can now be used as the support for legacy has been removed,
but still allow to use "exekall-LISA-test".
> bisector: Still allow exekall-LISA-test step name

- tools/bisector/bisector/bisector.py
bisector report -oexport-logs -odownlad=no may create symlinks pointing
to URLs. If -oexport-logs is later used with -odownlad=yes, the symlink
is followed when downloading into the file, which breaks. Fix that by
removing broken symlinks before trying to open the file for writing.
> bisector: Fix -oexport-logs

- lisa/target.py
Since all commands part of the systemd package are named
systemd-<something>, we need a more refined pattern in order to properly
freeze systemd-journald process for example.
This commit is ported from LISA legacy:
263dec9685b79351ff16020130fc67e99c82e166
> lisa.target: Update the cricital tasks list

- tools/bisector/bisector/bisector.py
Export the stdout/stderr logs even when -oignore-non-issue is used.
> bisector: Fix -oignore-non-issue + -oexport-logs

- lisa/conf.py
inspect.getdoc() makes use of inspect.cleandoc() which is specialized in
cleaning up docstrings, rather than textwrap.dedent() that may not
handle well some docstring styles (when the first line is not indented).
> lisa.conf: Use inspect.getdoc() instead of textwrap.dedent()

- doc/man1/exekall.1
- lisa/regression.py
- tools/exekall/doc/man/man.rst
- tools/exekall/exekall/engine.py
- tools/exekall/exekall/main.py
Only include values used in re-computed expressions in the ValueDB created when calling `exekall run --load-db`.
> Trim down ValueDB produced by exekall run --load-db

- lisa/energy_model.py
- lisa/tests/scheduler/eas_behaviour.py
- tests/test_energy_model.py
The Linux scheduler always tries to provide at least 20% of idle time to
all CPUs by not placing big tasks on small CPUs, and by selecting
appropriate frequencies. This is implemented by the 'capacity_margin'
coefficient in CFS, and schedutil's map_util_freq() (from 5.0 onwards).
However, this is not yet reflected in Lisa's optimal placement algorithm
which will assume a 39% task fits on a 40% CPU, for example. This
difference is the root cause for many task_task_placement failures on
some boards (TC2) although there is not much we can actually do to 'fix'
the kernel. One possibility would be to make the energy margin larger,
but that would lower the bar for all platforms so an alternative
solution is preferable.
In order to solve this, reflect the kernel's 80% capacity margin in
Lisa's …
> energy_model: Reflect 80% capacity margin in optimal placement

- doc/man1/exekall.1
- lisa/exekall_customize.py
- tools/exekall/exekall/_utils.py
- tools/exekall/exekall/main.py
Adaptor's custom CLI options can now be specified before positional arguments for `exekall run`. The issue is still present for `exekall compare`, but `--help` now exhibits a parameter group, and also tells that these options should come last.
> exekall: improve CLI option parsing

- lisa/tests/scheduler/load_tracking.py
- lisa/utils.py
Correctly propagating a path of the right type (ArtifactPath) for res_dir is
important to allow relocating the res_dir of the TestBundle when
deserializing its instances.
When a sub-res_dir must be created to be passed to another TestBundle,
make sure to correctly join the paths together to not loose information.
> lisa.tests: load_tracking: Correctly join res_dir

- doc/man1/bisector.1
- doc/workflows/automated_testing.rst
- lisa/regression.py
- tools/bisector/bisector/bisector.py
- tools/check-test-fix.py
- tools/exekall/exekall/_utils.py
- tools/exekall/exekall/engine.py
- tools/exekall/exekall/main.py
tools: Add check-test-fix.py
Add a tool to re-run a given test against data collected using bisector,
like for the fortnightly integration. It will show a
regression/improvement table at the end to compare the reference data in
the bisector report with the new ones that were just generated. It can
be called as follow to check that a fix to a
RampDown:test_task_placement has been fixed on the first 10 available
traces:
$ check-test-fix.py -s 'RampDown:test_task_placement' bisector_report.yml.gz -oiterations=1-10 --only behaviour
Note: this will spawn one `exekall run` per CPU to speed up the
computation. That means the logs are output only when `exekall run`
command finishes to avoid interleaved output.
> tools: Add check-test-fix.py

- tools/lisa-test
Call it last to avoid any issue with variable number of arguments.
> tools: lisa-test: Move --select-multiple position in CLI

- lisa/exekall_customize.py
- tools/exekall/exekall/customization.py
- tools/exekall/exekall/main.py
exekall run on LISA will return with exit code 20 if an exception was
raised during execution of any expression, and 10 if any of the
ResultBundle.result is Result.FAILED.
> exekall: Allow customization of run exit code

- lisa/exekall_customize.py
- tools/exekall/doc/index.rst
- tools/exekall/doc/self_tests.rst
- tools/exekall/exekall/_utils.py
- tools/exekall/exekall/customization.py
- tools/exekall/exekall/main.py
- tools/exekall/exekall/tests/exekall_customize.py
- tools/exekall/exekall/tests/suite.py
- tools/exekall/exekall/tests/utils.py
- tools/scripts/travis_tests.sh
Add some tests for the engine of exekall, to help catching any tricky regression that could be introduced when modifying the engine.
To run it:
```
exekall run $LISA_HOME/tools/exekall/exekall/tests
```
> Exekall self tests

- lisa/tests/base.py
Avoid storing the parsed trace forever, to avoid consuming too much
memory in processes manipulating a large number of TestBundle. Most of
these kind of scripts will only process a bundle once and then go to the
next one anyway.
> lisa.tests.base: Use LRU cache for TestBundle.trace

- doc/workflows/automated_testing.rst
- lisa/exekall_customize.py
- lisa/regression.py
Compute the number of iterations required to observe the effects of a
fix to a test case, compared to the new failing rate. This gives an
indication on how many iterations are needed to have `exekall compare`
answer the question "is my fix fixing this regression ?", assuming that
you actually fixed it. If `exekall compare` says that there is no
significant change after that number of iterations, chances are that the
fix is only partial (or not fixing anything at all).
> lisa.regression: Add Regression.fix_validation_min_iter_nr

- lisa/conf.py
- lisa/tests/base.py
inspect.getdoc()/cleandoc() are better suited to handle docstrings than
textwrap.dedent(), since they handle properly lack of indentation on the
first line.
> lisa: Use inspect.getdoc() instead of textwrap.dedent

- doc/lisa_shell/man/man.rst
- doc/man1/lisa.1
- tools/lisa-test
This will share the same lisa.target.Target for all iterations, if more
than one iteration is requested (with -n). That avoids reconnecting to
the target at every iteration, which is likely to be the expected
behaviour for usual use cases.
More advanced users will use exekall directly instead of lisa-test if
sharing the Target between iterations is not desired.
> tools: lisa-test: Use --share '*Target'

- doc/lisa_shell/man/man.rst
- doc/man1/exekall.1
- tools/bisector/doc/man/man.rst
- tools/exekall/doc/man/man.rst
The man page builder of Sphinx already takes care of that to align with
man pages conventions, and the non-capitalized output looks better in
html doc.
> doc: Remove capitalization in man page headings

- lisa/tests/base.py
- lisa/trace.py
- lisa/utils.py
Allows using requires_events() decorator without enabling the runtime check.
This fixes the infinite loop with the `trace` property and `trace_window()` method exposed in https://github.com/ARM-software/lisa/pull/829
> unchecked @requires_events(check=False)

- lisa/energy_meter.py
Mirror what is done in TargetConf. Avoid having an extra "conf" level in
the expected YAML format, which is useless in this kind of
configuration.
> lisa.energy_meter: Use SimpleMultiSrcConf for conf classes

- lisa/conf.py
- lisa/energy_meter.py
- lisa/target.py
- lisa/trace.py
Make sure that all mandatory args have a value, and raise an exception
is it's not the case with the path in the configuration.
For example, if `kind` key is missing in `TargetConf`, the following message will appear when running with `exekall`:
```
EXCEPTION (KeyError): 'Missing mandatory keys: target-conf/kind'
```
> lisa.conf: Check for mandatory args in check_init_param()

- lisa/exekall_customize.py
There is no case where an FtraceCollector is requested to exekall
by a TestBundle subclass without providing any events to collect.
Therefore, it currently indicates a design issue, that would otherwise
trigger a cryptic error in trace-cmd itself.
Such design issue can arise for aggregation+item class pairs, where
exekall only knows about the aggregation class, but this class is an
empty shell and does not provide a useful FtraceConf. In that case, the
link must be manually made by adding ftrace_conf class attribute equal
to the one from the item class.
Catch the issue when we can display relevant context and raise an
exception.
> lisa.exekall_customize: Error for empty TestBundle.ftrace_conf['events']

- lisa/trace.py
Make sure to always add the delta column, even on empty dataframe. The
caller can then manipulate the dataframe in the same way wether empty or
not, and only operations like plotting will fail, with an explicit
error.
> lisa.trace: Fix Trace.add_events_deltas() on empty dataframe

- setup.py
- shell/lisa_shell
Allow using "%matplotlib widget" magic in jupyter lab notebooks, which
gives what used to be enabled by "%matplotlib notebook" in legacy
notebooks. This allows zooming and panning on the plots interactively.
> jupyter lab: Enable %matplotlib widget

- tools/exekall/exekall/engine.py
Return an empty ValueDB, which allows calling code to assume a ValueDB
will always be created.
Also make the None adaptor compatible with any other adaptor, so
everything will work as expected.
> exekall: Fix ValueDB.merge() on empty list

- doc/man1/exekall.1
- lisa/exekall_customize.py
- lisa/tests/base.py
- lisa/utils.py
- tools/exekall/doc/man/man.rst
- tools/exekall/exekall/_utils.py
- tools/exekall/exekall/customization.py
- tools/exekall/exekall/engine.py
- tools/exekall/exekall/main.py
Allow showing the content of a ValueDB and exporting serialized objects:
```
$ exekall --debug show VALUE_DB.pickle.xz --show UUID_OF_A_RESULT.attribute
$ exekall --debug show VALUE_DB.pickle.xz --serialize UUID_OF_A_RESULT.attribute PATH
```
> Add exekall show subcommand

- lisa/analysis/tasks.py
Allow getting the CPUs on which the given tasks executed. This is useful
to convert the tasks names of the rtapp profile into list of CPUs to
feed to plotting functions that need to know what CPU to look at. Since
the trace is usually already cropped around the execution of rtapp,
this allows spotting the relevant pieces of data.
> lisa.analysis.task: Add TaskAnalysis.cpus_of_tasks() 

- lisa/tests/scheduler/load_tracking.py
Load tracking tests rely on having a quiet system, so it makes for
them to check for noisy tasks.
I wanted to validate this on an integration run, but I can't get exekall to re-run on the computed values:
```
bisector report TC2.report.yml.gz -oexport-db=VALUE_DB.pickle.xz
exekall run /data/work/lisa/lisa/tests/ --load-db VALUE_DB.pickle.xz --load-type '*TestBundle' -s '*util_task*'
[EXEKALL][2019-05-24 16:55:10,455] INFO  Nothing to do, check --help while passing some python sources to get the full help.
```
I also trying without any `select` statement and got the same output :(
> tests: load_tracking: Decorate test methods with check_noisy_tasks()

- lisa/analysis/tasks.py
Align TaskAnalysis.plot_tasks_total_residency() that was forgotten when
porting all plot functions to forward kwargs to do_plot().
> lisa.analysis.tasks: Use kwargs in all plot methods

- tools/exekall/exekall/engine.py
Fix ID generation of non-factory-method operators.
> exekall: Fix engine.Operator.get_name()

- shell/lisa_shell
An extra line-return escape character was preventing lisa-install to
complete.
Signed-off-by: Alessio Balsini <balsini@android.com>
> lisa-install: Fix typo in install-nbextensions

- tools/bisector/bisector/bisector.py
Avoid raising exception when the user has not specified --notif.
> bisector: fix monitor-server when --notif not used

- lisa/analysis/base.py
- lisa/analysis/proxy.py
- lisa/tests/base.py
- lisa/trace.py
- lisa/utils.py
Load all the events that are useful to analysis classes from the trace, so that they can be manipulated without any manual settings.
> Make RTATestBundle.trace useable for by analysis methods

- lisa/analysis/tasks.py
Add nonlocal declaration since the variable is assigned to in a closure,
while refering to a name bound in an outer scope.
> lisa.analysis.tasks: Fix TaskAnalysis.plot_task_activation()

- tools/lisa-buildroot-update-kernel-config
cd to the kernel tree before calling merge_config.sh
> lisa-buildroot-update-kernel-config: Fix call from arbitrary folder

- Vagrantfile
This allows using `vagrant up` command to validate a LISA change, including full installation from a bare Ubuntu system.
> Vagrantfile: run the Travis tests after setup

- lisa/utils.py
Since object.__copy__ does not work, fall back on some __dict__ copy
behavior if super().__copy__ does not exist.
> lisa.utils: Fix Serializable.__copy__

- doc/conf.py
This extension provides the syntax-highlighted HTML pages containing
plain Python code, which clutters the search box results. Since nobody
is really using that feature, disable it.
> doc: Disable sphinx.ext.viewcode

- lisa/tests/base.py
- lisa/utils.py
When used on methods, this avoids keeping a reference over the instances
alive forever even when nothing else apart from the cache needs it
anymore.
> utils: Make memoize() use a weakref for the first parameter

- lisa/target.py
"info" level is needed for most of LISA output and advancement messages,
so let's make it the default.
> lisa.target: Target.from_cli() defaults to info log level

- lisa/trace.py
Pandas Series' ix indexing is deprecated in favor of iloc/loc. Replace
our use by "loc" which provides label-based indexing.
> lisa.trace: Remove deprecated use of "ix" Series indexing

- lisa/energy_model.py
Turn a stylistic "-" into an ":" so it is not confused with some kind of
substraction.
> lisa.energy_model: Disambiguate exception message

- lisa/__init__.py
- lisa/analysis/load_tracking.py
- lisa/tests/scheduler/load_tracking.py
- lisa/trace.py
- lisa/utils.py
- lisa/version.py
* Add may_use_events() decorator to supplement requires_events() and requires_one_event_of()
* Add `LoadTrackingAnalysis.df_(cpus|task)_signal` to replace `df_(cpus|task)_signals()`
* Allow plotting `util_est_enqueued` signals in `LoadTrackingAnalysis.plot_(cpus|task)_signals`
* Allow selecting signals to plot in `LoadTrackingAnalysis.plot_cpus_signals` to mirror the `task` variant of the method
EDIT:
* Add `utils.deprecate()` decorator and treat deprecation as errors in `lisa`  and warnings in `__main__`
> Allow plotting utilest signals

- lisa/analysis/load_tracking.py
Drop columns that are existing and ignore when the column we try to drop
does not exist.
> lisa.analysis.load_tracking: Fix column dropping

- lisa/exekall_customize.py
- tools/bisector/bisector/bisector.py
Avoid counting NoValue as a failure, since we don't want exceptions to
pollute the regression tables.
> lisa.exekall_customize: Fix NoValue handling in exekall compare

- lisa/analysis/base.py
- lisa/analysis/rta.py
Use the analysis name instead, so the default file naming does not
depend on where the class is defined, and so that we don't have file
name clashes if there is more than one class in a module (it's Python,
not Java).
> lisa.analysis: Remove use of __module__

- lisa/analysis/frequency.py
- lisa/tests/scheduler/eas_behaviour.py
- lisa/tests/scheduler/load_tracking.py
Since pylab is actually a re-export of matplotlib.pylab, itself
re-exporting names from other matplotlib and numpy modules, let's refer
to the modules the functions are actually defined in. In our case, it's
only `savefig()` defined in matplotlib.pyplot.
> lisa: remove imports of pylab

- lisa/tests/base.py
- lisa/tests/scheduler/eas_behaviour.py
- lisa/tests/scheduler/load_tracking.py
- lisa/tests/scheduler/misfit.py
- lisa/tests/staging/sched_android.py
Make the client code more easilyu understandable than relying
rtapp_profile dict structure, and allow easier decoupling if needed.
> lisa.tests.base: Introduce RTATestBundle.rtapp_tasks property

- lisa/utils.py
- setup.py
Calling utils.show_doc() from a Jupyter notebook opens an IFrame with
online LISA documentation.
EDIT: ReadTheDocs exposes the intersphinx inventory, so no need to build anything locally.
> doc: Add utils.show_doc()

- lisa/utils.py
Since they many not be installed, only try to import them if they are
available.
> lisa.utils: Make sphobjinv and IPython import optional

- lisa/trace.py
Handle the case where no cpu_frequency event is available.
> lisa.trace: Fix cpu_frequency sanitization

- lisa/analysis/tasks.py
Use Trace.has_events() (or trace.available_events) instead of using
trace.events.
> lisa.analysis.tasks: Fix event checking

- lisa/analysis/frequency.py
- lisa/trace.py
- tests/test_trace.py
Move domain-specific functions into the corresponding analysis, where it
is used.
> lisa.trace: Move Trace.get_peripheral_clock_effective_rate() into frequency analysis

- .gitignore
- doc/setup.rst
- tools/kmodules/.gitignore
- tools/kmodules/build_module
- tools/kmodules/clean_module
- tools/kmodules/sched_tp/0001-sched-add-a-module-to-convert-tp-into-events.patch
- tools/kmodules/sched_tp/Makefile
- tools/kmodules/sched_tp/sched_events.h
- tools/kmodules/sched_tp/sched_tp.c
Add some infrastructure to allow building, installing, loading and unload a module and add a new sched_tp module which would be required to run Lisa tests against mainline kernel when the new bare tracepoints (ie: don't have TRACE_EVENTs on top/associated with them) land there.
> Tracepoints module

- tools/batch-rebase
Avoid an infinite loop when a cherry pick would lead to an empty commit at the
boundary of the cherry-picked range.
> Fix batch-rebase

- lisa/energy_model.py
- lisa/utils.py
Add `LinuxEnergyModel(EnergyModel)` and `LegacyEnergyModel(EnergyModel)` sublcasses of EnergyModel, so that each of them can implement their own `from_target()` and `check_from_target()` methods. 
`EnergyModel.from_target()` autodetects the appropriate subclass to use, so it's completely transparent.
This split can allow separate implementation of other methods as well, notably the ones dealing with idle states, allowing for potential speed-up in LinuxEnergyModel since this class registers a 0 cost for idle states/
> Cleanup EM loading

- lisa/utils.py
Backport of Python 3.7 contextlib.nullcontext.
> lisa.utils: Add nullcontext manager

- lisa/utils.py
Give a direct link to the doc of the new function to use when issuing a
deprecation warning.
> lisa.utils: Include replacement function doc URL in deprecation warning

- lisa/energy_model.py
@classmethod decorator got lost in a previous refactoring.
> lisa.energy_model: Fix missing @classmethod

- lisa/tests/base.py
The MHU controller interrupts, now threaded, will be detected as noise
that sometimes exceeds the 1% default threshold. This is often not much
higher than 1%, so let's allow 1.5% of time to be spent it its interrupt
handlers.
> lisa/tests: whitelist the mhu noise to a 1.5% threshold

- lisa/conf.py
Allows getting a mapping suitable for storing in a YAML configuration file (as
opposed to YAML as a serialization format).
An intended usage is with `exekall show --show-yaml` or
`exekall show --serialize`.
> lisa.conf: Expose MultiSrcConfABC.as_yaml_map property

- lisa/trace.py
Make sure Trappy actually loaded the trace it was asked for, and not something
else. If that assertion fails, it's probably because a trace.txt was asked for,
and a trace.dat exists in the same folder.
> lisa.trace: Check Trappy behavior

- lisa/trace.py
This variable seems to be now completely unused in the codebase
> lisa.trace: Remove unused NON_IDLE_STATE global

- lisa/analysis/notebook.py
- lisa/datautils.py
Allow writing the following code in a notebook, to give a quick way of adding custom plots:
```
from lisa.trace import Trace
trace = Trace('trace.dat', events=['sched_switch'])
def plot_foo(trace, y, axis):
print('Plotting horizontal line at level: {}'.format(y))
axis.axhline(y=y)
trace.analysis.notebook.plot_foo(3)
```
Also allows easy plotting of signals that may not have a dedicated plot method already:
```
trace.analysis.notebook.plot_event_field('sched_load_avg_cpu', field='util_avg', filter_columns={'cpu': 0})
```
> Add lisa.notebook.analysis

- lisa/analysis/frequency.py
Fix typo in set() operations, leading to no check being carried in the default
case.
> lisa.analysis.frequency: Fix domain coherency check

- lisa/target.py
This allows using the freezing feature on the host, while still being able to
unfreeze at the end. Output usually freezes as well if it comes in a virtual
terminal, but otherwise, things do work.
> lisa.target: Avoid freezing the main process on LocalLinuxTarget

- tools/lisa-plot
By default, do not normalize the time so that the graph can be easily used along
the trace in kernelshark.
Add --normalize-time to restore the other behavior.
> tools: lisa-plot: Add option for time normalization

- doc/man1/lisa.1
- shell/lisa_shell
Refer to the new LISA_USE_SYSTEM_BIN for the priority of tools added to the PATH.
> doc: Fix documentation of LISA_HOST_ABI env var

- lisa/analysis/latency.py
- lisa/analysis/load_tracking.py
- lisa/analysis/tasks.py
- lisa/datautils.py
- lisa/tests/base.py
- lisa/trace.py
- lisa/utils.py
- lisa/wlgen/rta.py
- tests/test_trace.py
- tools/exekall/exekall/utils.py
Fix #926
Make the task selection/resolution methods more consistent and strict when used with task name or task PID. This assumes that the simple comm/PID interface is only meant for non-ambigous cases.
Introduce a new way of selecting tasks by using `TaskID(pid, comm)` named tuples. It allows disambiguation in tricky cases. This include:
* when just specifying a comm or a PID is ambiguous, you can specify both to remove ambiguity
* when a specific PID is of interest regardless its task comm (or the opposit), the irrelevant field can be set to ``None``. This gives an explicit way of avoiding the exception that would be raised when specifying an PID or comm alone (i.e. not in a tuple).
> Rework task selection

- lisa/tests/base.py
- lisa/tests/cpufreq/sanity.py
- lisa/tests/hotplug/torture.py
- lisa/tests/scheduler/eas_behaviour.py
- lisa/tests/scheduler/load_tracking.py
- lisa/tests/scheduler/misfit.py
- lisa/tests/scheduler/sanity.py
- lisa/tests/staging/sched_android.py
- tests/test_test_bundle.py
Add `TestBundleMeta` metaclass to generate the shim automatically, by moving the annotations of `_from_target` to a shim `from_target`
> Remove `from_target` boilerplate definitions

- lisa/tests/base.py
It is sometimes useful to keep the unit displayed (if defined), even if the
value is not something scalar.
> lisa.tests.base: Display Metrics' unit even when the value is a Mapping

- doc/man1/lisa.1
A previous commit updated an env var doc without refreshing the manpage.
> doc: refresh built manpages

- .gitignore
- Vagrantfile
- devmode_requirements.txt
- install_base.sh
- requirements.txt
- shell/lisa_shell
Installing Glib seems to pull a lot of things that are not cleanly packaged,
leading to a range of cryptic errors at install time. Since bisector uses GLib's
DBus bindings, do not install that optional feature by default.
Also allow install_base.sh to register extra requirements for pip, to be installed by lisa-install. This gives a way of enabling an optional feature when running ./install_base.sh, without having to also add a way of specifying that for lisa-install.
> install: Make DBus-related packages optional

- tools/check-setuppy
Parse as an int, since the env var is a string.
> tools: check-setuppy: Fix LISA_USE_VENV usage

- lisa/target.py
Remove wrong return annotation on Target.from_custom_cli.
Restore the explicit parameter list on Target.from_cli so that it can be picked
up by exekall (--allow/--restrict is needed).
> lisa.target: Fix Target.from(_custom)_cli annotations

- lisa/conf.py
- lisa/doc/helpers.py
- lisa/tests/base.py
Record the UTC datetime when creating a ResultBundle, so that time series can be
built out of a collection of them.
> lisa.tests.base: Record creation date in ResultBundle

- lisa/tests/base.py
- lisa/utils.py
Since collections.ChainMap does the same thing but better, remove LayeredMapping.
> lisa.utils: Remove lisa.utils.LayeredMapping

- lisa/tests/base.py
The first mapping given to ChainMap is the one receiving the updates, not the
last, so flip the parameters.
> lisa.tests: Fix ChainMap usage

- lisa/tests/cpufreq/sanity.py
Python < 3.7 is picky on where trailing comma are allowed.
> lisa.tests.cpufreq.sanity: Fix trailing comma

- lisa/tests/base.py
- lisa/utils.py
Keep the __annotations__ and __signature__ in sync for the synthetic from_target
created by TestBundleMeta.
> lisa.tests.base: Fix signature of shim from_target

- lisa/utils.py
- tools/bisector/bisector/bisector.py
ModuleNotFoundError is more precise, but was only introduced in Python 3.6.
> lisa.utils: Replace ModuleNotFoundError with ImportError

- tools/exekall/exekall/main.py
Make sure that only the expected modules are scanned by exekall, and make it
more robust against spurious import errors.
> exekall: Fix module import

- lisa/wa_results_collector.py
Daniel pointed out that passing `parse_traces=True` to
WaResultsCollector breaks horribly on a sad piece of code.
We're attempting to create a PlatformInfo to give to Trace, but we're
only filling it with the kernel version which mostly useless. Just skip
that step, and only pass a non-None platinfo if the user specified one.
Ideally we should collect one platform_info per wa directory, but that
would mean adding a LISA-specific step to lisa-wltest which I think we
all would like to avoid.
> lisa/wa_results_collector: Fix parse_traces=True

- tools/exekall/exekall/engine.py
Ignore annotations using the stdlib typing module rather than raising
exceptions when they are encountered.
> exekall: Ignore non-class annotations

- lisa/tests/base.py
- tools/lisa-test
DmesgTestBundle allows writing tests based on dmesg. It comes with a generic
test that checks that no message more critical than "warn" appeared during the
execution of the test.
Signed-off-by: Douglas RAILLARD <douglas.raillard@arm.com>
> lisa.tests.base: Add DmesgTestBundle

- lisa/tests/base.py
* Use spaces for indentation instead of tabs
* Sort the inner lists of rtapp_tasks_map to have stable output suitable for
display.
* Use a set instead of a list for the comms, so we avoid matching the regex
multiple times against the same comm, and we avoid having duplicates in the
inner list of rtapp_tasks_map.
> lisa.tests.base: Minor cleanup

- lisa/tests/scheduler/eas_behaviour.py
- lisa/tests/scheduler/load_tracking.py
In recent versions of rtapp, the name a task will get during execution is not
the one specified, in order to distinguish between forked tasks.
`self.rtapp_tasks` is a property of RTATestBundle that allows getting the names
as they appear in the trace, which is therefore suitable for filtering.
> lisa.tests: Ban usage of rtapp_profile.keys() to filter traces

- lisa/tests/base.py
> lisa.tests.base: Fix typo in DmesgTestBundle docstring

- lisa/wlgen/rta.py
- lisa/wlgen/workload.py
Make sure that all elements of the shell commands are quoted as they should.
> lisa.wlgen.rta: Correctly quote shell commands

- lisa/tests/scheduler/load_tracking.py
Rewrite get_task_duty_cycle_pct using task analysis methods. It seems
that the Bart method for obtaining a tasks's run time on a CPU
sometimes fails to provide a correct value.
Given that we're using task analysis methods on all other tests with this
function being the only one remaining using a Bart (SchedAssert) method,
rewrite this function to use a more reliable method to obtain a task's
run time.
> load_tracking: rewrite get_task_duty_cycle_pct

- tools/wltests/test_series
When branch names are used instead of SHA1 in a series file, the name is
resolved to a full SHA1 string which is longer then the 12 chars
actually returned by the for-each-ref command we use to lookup names.
Ensure to always compare up to 12 chars of a specified SHA1.
> tools/wltests: fix test_series's branch names resolution

- lisa/analysis/base.py
- lisa/datautils.py
- lisa/regression.py
- lisa/tests/base.py
- lisa/wlgen/sysbench.py
- tools/bisector/bisector/bisector.py
- tools/exekall/exekall/engine.py
Adopt a consistent style for documenting variable keyword arguments
(**kwargs) throughout LISA. Documenting them as "keyword argument" is
misleading since most of the keyword arguments are not covered by that,
only the variable ones.
> doc: Align documentation of all var keyword args

- lisa/wlgen/rta.py
List with order that can vary from one execution to another can easily
creep into user-visible data, with quite annoying consequences like
inability to diff the output between one run and another or other random
presentation artifacts.
> wlgen: Avoid list with unstable order

- tools/exekall/exekall/_utils.py
- tools/exekall/exekall/main.py
Import errors need to be ignored when parsing the command line the first time,
as some positional parameters could just belong to adaptor-specific options.
During that phase, importing must be done with a best-effort policy, so that
specifying a package name will result in importing as many submodules as
possible. This avoids not finding the adaptor just because an unrelated module
of the package failed to import with an ImportError.
Once the command line can be parsed unambiguously, modules can be imported
again. The modules that were imported successfully are reused, but the one that
failed to import will be imported again, and the exception will not be hidden at
this point.
> exekall: Report import error in modules being imported

- lisa/wlgen/rta.py
mlockall requires privileges to succeed, so disable it when running as a regular
user.
> lisa.wlgen.rta: Disable mlockall ("lock_pages") when running as non-root

- lisa/target.py
- lisa/tests/base.py
Couple of things to update in LISA to make use of new devlib features:
* Remove some duplication in dmesg output parsing
* Root adb upon connection before loading the devlib modules. Modules that need root access will work even if the device is not already rooted at the time the target connects.
Depends on https://github.com/ARM-software/lisa/pull/1072
> devlib usage update to use new features

- lisa/tests/hotplug/torture.py
This metric is redundant with the list of CPUs that are online, but can be
easily plotted, unlike the list of CPUs.
> lisa.tests.hotplug: Add number of missing online CPUs metric

- lisa/conf.py
Avoid fancy names that would make it impossible to build new things out of the
names, such as key paths etc.
> lisa.conf: Restrict valid key names

- tools/kmodules/sched_tp/0001-sched-add-a-module-to-convert-tp-into-events.patch
- tools/kmodules/sched_tp/sched_tp.c
kernel/sched/sched_tp.c: In function 'sched_pelt_se':
>> kernel/sched/sched_tp.c:77:22: error: 'struct sched_entity' has no member named 'cfs_rq'; did you mean 'on_rq'?
void *cfs_rq = se->cfs_rq;
^~~~~~
on_rq
> Update tracepoint module and patch to fix some kbuild errors

- lisa/tests/scheduler/misfit.py
Rt-app task naming was changed with the introduction of the fork
functionality, and this was reflected in
5b066eef0578 ("lisa.tests.base: Introduce RTATestBundle.rtapp_tasks property")
The misfit test case uses the name of the task to figure out on which
CPU it is initially pinned, which is somewhat icky (and now broken with
the task naming change). Look at the full fledged profile to figure this
out instead.
Briefly tested on a H960 with the latest integration branch:
```
################################################################################
[EXEKALL][2019-09-18 12:53:26,537] INFO  Artifacts dir: /data/work/lisa/results/20190918_12:49:12_1a273d9cd97c42fab8b7195bee0b317f
[EXEKALL][2019-09-18 12:53:26,537] INFO  Result summary:
StaggeredFinishes[board=hikey960]:test_dmesg …
```
> lisa/tests: misfit: Fix rt-app naming issue

- lisa/wlgen/workload.py
Otherwise, rt-app will try to create a log file wherever it's executing from.
Similar behavior can be expected for other binaries, so let's just cd into the
right directory before executing.
> lisa.wlgen: CD into run_dir when running the command

- lisa/utils.py
object.__init_subclass__ is only available in Python >= 3.6, so do not reference
it when not available
> lisa.utils: Fix deprecate() on classes for Python < 3.6

- lisa/trace.py
trace-cmd sometimes does not show the command name when raw-parsing the
sched_switch and sched_wakeup events. Instead, it reports "<...>".
Make that an illegal value for TaskID.comm, so that we catch the issue as early
as possible, without going through every dataframe created by df_events(). Note
that the issue can appear for other events as well, although it's expected that
it will always appear for sched_switch/sched_wakeup. Checking at this level
should therefore be enough to catch traces with that issue.
trace-cmd bug report: https://bugzilla.kernel.org/show_bug.cgi?id=204979
> lisa.trace: Shield against trace-cmd command name reporting issue

- lisa/wlgen/rta.py
Since rt-app itself generates suffixes based on dashes and numbers, only
allow simple names: chars (upper and lower case), numbers and
underscore.
> lisa.wlgen.rta: Restrict valid rt-app names

- lisa/wlgen/rta.py
Use the attribute, which is guaranteed to be a list rather than the parameter
which could be None.
> lisa.wlgen.rta: Fix rt-app ftrace events JSON building

- lisa/analysis/base.py
Setting up a non-interactive plot fails will make it impossible to save the
figure in old version of matplotlib, so warn and force interactive=True.
> lisa.analysis: Issue UserWarning for old version of matplotlib

- lisa/tests/staging/util_tracking.py
* Avoid interactive plots as they leak memory
* Remove ax=axis from axvline() call since it's redundant with the method call
on the axis itself.
> lisa.tests.util_tracking: Fix debug plotting

- lisa/tests/scheduler/misfit.py
work in __init__ can fail, which means that there will be no serialized object to reproduce the issue easily. This also means that the computation leading to the object state cannot be easily replaced/fixed on a deserialized instance, making it more difficult to debug.
> misfit: avoid doing some work in __init__

- lisa/utils.py
collections.namedtuple() only accepts an undocumented `module` parameter
starting from Python 3.6 or possibly 3.7. Therefore, avoid using it and
set __module__ explicitly on the type.
> lisa.utils: Fix namedtuple(module=...) parameter

- doc/man1/exekall.1
- tools/exekall/exekall/main.py
Avoids saving a VALUE_DB.pickle.xz file, which can save a lot of time/memory
when running a large number of iterations. The drawback is that partial
re-execution of expressions becomes impossible, as well as `exekall compare` and
all the other tools needing programmatic access to the results.
> exekall: Add exekall run --no-save-value-db

- lisa/tests/base.py
Handle when the task was renamed without a sched_switch: use the phase start
time instead of the preceding switch, since there never was a switch-in for that
PID+comm so far.
> lisa.tests.base: Fix trace_window()

- tools/batch-rebase
When cherry-picking a commit already merged in the base branch, the
cherry-picked commit will be empty. Since it should be removed from the topic
branch (as it is merged already), report its sha1 for easier identification.
> tools: batch-rebase: Add empty commit sha1

- lisa/wlgen/rta.py
Isolate the choice of context manager from the rest of the code rather than
copying the code to run in the different paths.
> lisa.wlgen.rta: Use nullcontext() to avoid code duplication

- lisa/doc/helpers.py
Use the analysis name rather than its module to avoid confusion when multiple
analysis are implemented in the same module.
Also make sure the output is sorted.
> lisa.doc.helpers: Fix analysis listing

- lisa/tests/scheduler/load_tracking.py
- lisa/wlgen/rta.py
* Check against the fastest CPU in each capacity class. This CPU is the
one that has been the less impacted by external disturbances, that are
usually random.
* Check that the rt-app calibration values are inversely proportional to
the CPU capacities. When the scaling factor diverges too much for some
CPUs, raise an exception. This indicates that rt-app will be unable to
provide predictable utilizations across different CPUs, which is the
underlying assumption of all wlgen-based code in LISA.
* Use the CPU capacities from plat_info rather than trying to fetch them
directly using devlib. This follows the practice in LISA, allowing the
user to provide the values in a configuration file in order to run as
non-root (it's also faster and uses values printed in the log, for a
consistent …
> lisa.wlgen.rta: Strengthen sanity check on calibration values

- lisa/git.py
- lisa/wa_results_collector.py
* Drop compat for git older than 2.7 as we don't support anything before Ubuntu
Xenial 16.04.
* Raise an exception when no symbolic reference can be found.
> lisa.git: Cleanup find_shortes_symref

- setup.py
Since jupyter has been updated to work with Tornado 6, that constraint is not
needed anymore.
> setup.py: Remove version constraint for Tornado

- lisa/wlgen/rta.py
Disable idle state once before calibrating all CPUs, rather than for each CPU
everytime.
> lisa.wlgen.rta: Speed up calibration

- lisa/__init__.py
- lisa/tests/__init__.py
Avoid forcefully setting the backend of matplotlib, to ease debugging.
> lisa.tests.__init__: Remove matplotlib.use() call

- lisa/target.py
- lisa/wlgen/rta.py
target.freeze_tasks() needs to check if the device is rooted before
looking for the cgroup devlib module. This module is never present in
unrooted devices.
Only run rta as root if the device is rooted.
Fixes: 48db507ca67b4e959f1c835f49f102e58da5a051
> Don't force running rta as root for calibration

- ipynb/examples/typical_experiment.ipynb
This will allow running the notebook in non-interactive environment for testing
it.
> ipynb: typical_experiment: Comment-out !kernelshark call

- lisa/trace.py
Allows creating a Trace object right from a Target, without an intermediate
FtraceCollector.
> lisa.trace: Add Trace.from_target() factory classmethod

- lisa/wlgen/rta.py
Having the capacity values allow tuning a kernel in order to have accurate util
reproduction by rt-app on all cores.
> lisa.wlgen.rta: Display CPU capacities found by rt-app in INFO log

- lisa/datautils.py
- lisa/tests/scheduler/load_tracking.py
Unify Invariance and PELTTask tests, so that:
* duplicated behaviour check is removed (and a fair amount of helpers that come with that)
* PELT tests are carried on all types of CPUs, at multiple frequencies, giving much more coverage to the correctness test.
Note that this *requires* to have access to the PELT clock in the sched_load_se
event, otherwise the simulated signal is completely wrong. The test is able to
catch that though.
Note: Computations in PELT use an inaccurate delta of its clock, leading to some unwanted artifacts that happen to be reduced by other rounding errors. Since the simulator does not suffer from rounding errors, the artifacts become much more visible, which leads to a noticeable between the simulated signal and the one computed by the kernel.
> lisa.tests.scheduler.load_tracking: Unify PELTTask and Invariance

- lisa/exekall_customize.py
- lisa/tests/base.py
- lisa/trace.py
- tools/exekall/exekall/customization.py
Finally get some decent output, such as this exekall summary:
```
################################################################################
[EXEKALL][2019-10-21 18:32:55,548] INFO  Artifacts dir: /home/dourai01/Data/Git/lisa/results/pwrsft-juno-r0-1/20191021_18:32:52_2474a9215fc54e2ca141b6147bfd3da4
[EXEKALL][2019-10-21 18:32:55,548] INFO  Result summary:
OneSmallTask[board=pwrsft-juno-r0-1]:test_dmesg          UUID=968577749bcb4aea817a593d6a3f4ad7 PASSED: dmesg output:
OneSmallTask[board=pwrsft-juno-r0-1]:test_slack          UUID=c92c7d5ae0564db1bab80d12e25f362c PASSED: small-0 delayed activations: 0.0 %
OneSmallTask[board=pwrsft-juno-r0-1]:test_task_placement UUID=1bc2c5fc904f43e58f7f2bfb5754a271 PASSED
energy threshold: 40.16330044843049 bogo-joules
estimated energy: …
```
> exekall: pretty print test metrics

- lisa/utils.py
Just check if the name exists rather than as an attribute of
__builtins__. Hopefully, this should be a bit more robust and work with
more ipython versions.
> lisa.utils: Update check to __IPYHTON__

- lisa/utils.py
- logging.conf
A formatter is needed when logging.conf is not used.
> lisa.utils: Add formatter when setup_logging(level=...) is used

- lisa/utils.py
Iterating over a tuple yields the values it contains, like a list. Iterating
over a mapping must yield the keys, i.e. the field names. Make
lisa.utils.namedtuple comply with the Mapping interface rather than the tuple
one, since that's the most suited for generic introspection of test metrics.
> lisa.utils: Fix lisa.utils.namedtuple Mapping interface

- lisa/trace.py
Use all info given by sched_switch (both for next and prev process) when
establishing the task names/PID mappings.
> lisa.trace: Improve Trace._get_task_maps()

- doc/lisa_shell/man/man.rst
- doc/man1/lisa.1
- tools/lisa-execute-notebook
Execute a given notebook like a regular script using jupyter nbconvert and
ipython. Separate use of IPython is necessary since jupyter nbconvert --execute
is not able to print the output on its stdout like a regular script would.
> tools: Add lisa-execute-notebook

- tools/travis_tests.sh
Commits touching external/ subtrees are not allowed to be merged in master, so
whitelist this subtree removal.
> tools: travis_test.sh: Whitelist BART removal commit

- lisa/trace.py
- tests/test_trace.py
* Correctly handle task renames which was broken by recent use of extra sched_switch fields
* Correctly merge information from multiple events: always preserve trace appearance order across events.
> Fix traces name/PID mapping

- tools/exekall/exekall/_utils.py
- tools/exekall/exekall/engine.py
pypy interpreter seems to sometimes set `__module__` and `__globals__` to
None. Handle gracefully both cases.
> exekall: Handle x.__module__ == None and x.__globals__ == None

- lisa/tests/base.py
- lisa/trace.py
- lisa/wlgen/rta.py
Allow resolving RTA profile names to task names as found in a trace. To avoid
filtering the trace again and again, cache the result in RTA.
> lisa.wlgen.rta: Add RTA.resolve_trace_task_names()

- lisa/tests/base.py
Return a dict(str, list(str)) rather than a dict(str, list(TaskID))
> lisa.tests.base: Fix RTATestBundle.rtapp_tasks property

- tests/test_conf.py
User-provided top-level input can be expected to be mappings. What validation is
really about is checking types of values for each key.
> tests.test_conf: Use more realistic example for test_disallowed_val()

- install_base.sh
On some versions of Ubuntu, installing node-gyp is required.
> install_base.sh: Install node-gyp to allow installing npm

- lisa/tests/scheduler/load_tracking.py
Make sure task activations are displayed with the right scale.
> lisa.tests.scheduler.load_tracking: Fix debug plot

- install_base.sh
Since the nodejs package is basically broken [1] on Ubuntu 18.04, use the
package from snap.
[1] https://bugs.launchpad.net/ubuntu/+source/nodejs/+bug/1794589
> install_base.sh: Fix nodejs install on Ubuntu 18.04

- lisa/tests/base.py
- lisa/tests/scheduler/load_tracking.py
- lisa/wlgen/rta.py
Allow rt-app to run with actual CPU invariant utilization.
TODO: check the CPUMigration test debug plot to make sure there is no change in util value when migrating the same task.
> Update CPU capacities while running rt-app

- install_base.sh
Since it's required by devlib to connect to ssh targets with password
auth.
> install_base.sh: Install sshpass

- tools/bisector/bisector/bisector.py
Speed up compression by using gzip archive instead of xz.
> bisector: Use gzip compression for LISA-test artifacts

- lisa/wlgen/rta.py
Avoid pinning tasks on big CPUs by using a different variable name.
> lisa.wlgen.rta: Fix RTA.run() CPU pinning

- doc/plot_conf.yml
- lisa/analysis/tasks.py
On a standalone plot:
As an overlay on top of util and load signals:
> Plot task activations with one row per CPU (kernelshark style)

- doc/lisa_shell/man/man.rst
- doc/man1/lisa.1
- lisa/conf.py
- lisa/exekall_customize.py
- tools/lisa-conf-cat
Allow evaluating a LISA YAML configuration file, with the help of each key in
the comments and all tags evaluated.
TODO: factorize the conf parsing/merging from lisa.exekall_customize into lisa.conf and use that from lisa-conf-cat.
> tools: Add lisa-conf-cat

- lisa/datautils.py
- tests/test_datautils.py
Allow extracting multiple signals multiplexed in a single events.
A signal can be thought as "something that would make sense to plot with one curve only". For example, `sched_load_se` event multiplexes util signals for all the tasks in the system.
> Add datautils.df_split_signals()

- lisa/doc/helpers.py
- setup.py
Since it's necessary to import some modules, make sure to have it installed to
build the doc.
> setup.py: Add ipython to doc dependencies

- lisa/pelt.py
- lisa/tests/scheduler/load_tracking.py
Remove margin_pct and introduce margin, expressed in PELT units. This restores
the dependency of the result on the init and final values.
> lisa.pelt: Change pelt_settling_time(margin=...) parameter

- lisa/analysis/rta.py
- lisa/tests/base.py
- lisa/tests/scheduler/misfit.py
- lisa/wlgen/rta.py
Add a buffer phase to let PELT signals converge before the tests' wlgen tasks
actually start executing. This phase is then cropped away by
RTATestBundle.trace_window() so it's completely transparent to the tests.
> lisa.tests.base: Add a buffer phase to all workloads of RTATestBundle

- lisa/tests/base.py
This avoids tracing the (lengthy) freezing, thereby shrinking trace.dat by a
sizable amount.
> lisa.tests.base: Freeze target userspace before tracing

- lisa/tests/base.py
> lisa.test.base: Clarify docstring of RTATestBundle.trace

- lisa/tests/base.py
- lisa/tests/scheduler/misfit.py
- lisa/trace.py
I've been hitting some nasty issues with the misfit tests since the introduction of the rt-app buffer phase. Some (most?) of it is due to shady things I wrote in that test, so I only really have myself to blame...
I tested this by keeping tasks pinned in the last phase (IOW forcing a failure scenario), and the detected big CPU idle times were exactly what I expected, so AFAICT this works fine.
> Fix misfit test issues

- lisa/tests/staging/numa_behaviour.py
LISA can be used to test scheduler behavior for task placement on hardware with complex NUMA
topology. I already submitted Pull Request to devlib for NUMA introspection:
https://github.com/ARM-software/devlib/pull/441
This Pull Request has a couple of very basic tests to ensure that tasks with relatively low
utilization do not migrate to different cores.
I am planning to add NUMA related tests in my next Pull Request after some NUMA related changes in rt-app.
> Added new tests for NUMA related behavior of scheduler

- tools/batch-rebase
Forcefully delete the temp clone even when a conflict arises. This allows use in
automated environment that will not be able to fix anything in any case.
> tools: batch-rebase: Add --delete-temp option

- lisa/tests/scheduler/load_tracking.py
The parameters passed to is_almost_equal() functions were swapped. The
target utilization is the *expeted* value not the value from the trace.
Fix that.
> load_tracking: Fix wrong parameters passed to is_almost_equal()

- doc/misc_utilities.rst
- lisa/analysis/base.py
- lisa/analysis/load_tracking.py
- lisa/analysis/tasks.py
- lisa/notebook.py
- lisa/trace.py
That should solve the long standing annoyance of going back and forth between kernelshark and the notebook when one needs to look at the exact events in a dataframe at a given time:
For good measure, also add an easy way to select the task to look at using a dropdown:
And to finish the basic UI, add an "open in kernelshark" button next to every figure that analysis plot methods touch:
Kernelshark can unfortunately not zoom in the trace from the command line, it needs a session file that needs to contain lots of other info, and is a bit picky about what makes it happy and what makes it segfault.
> Allow interactive df display linked to a plot widget

- install_base.sh
Flex is required to be some of the binary assets in LISA.
> install_base.sh: Install flex

- lisa/tests/staging/schedutil.py
Since RTATestBundle now takes care of isolating the test from the
initial conditions with a buffer phase, it's not necessary to do that in
the test anymore.
> tests: staging: schedutil: Remove phase filtering

- shell/lisa_shell
If the user already has a valid Android SDK specified in $ANDROID_HOME,
there is no need to override it.
Make the lisa default path conditional on $ANDROID_HOME not being set.
Signed-off-by: Quentin Perret <qperret@google.com>
> shell: Don't override ANDROID_HOME

- doc/index.rst
Declare the "lisa" package to Sphinx, so that foreign projects can
reference to it using autodoc with :mod:`lisa`.
> doc: Add module declaration for LISA

- lisa/target.py
Using target.disable_idle_states() only disables the idle states for the first CPU of each domain, not for all of them. I assume it is not the intended behavior.
This patch enables and disables the idle states for every CPUs, not only the first one of each domain.
> lisa.target: Fix enable/disable idle states

- lisa/conf.py
- lisa/energy_meter.py
- lisa/platforms/platinfo.py
- lisa/target.py
- lisa/tests/base.py
- lisa/trace.py
- lisa/utils.py
Allow creating typed containers more easily, e.g.: `TypedDict[int, str]` is a typed dictionary with int keys and str values.
> Streamline typed containers

- install_base.sh
I've only tested the apt side of things; with these two extra packages I
can run the install (and even run the tests!) on an Ampere eMAG running
Ubuntu 19.04.
> install_base.sh: Add missing dependencies for arm64

- lisa/trace.py
Since we don't forward class attribute lookup automatically, do it
manually for LOG_LEVELS.
> lisa.trace: Forward devlib.DmesgCollector.LOG_LEVELS

- lisa/tests/scheduler/load_tracking.py
Accurately find the start and end of each rtapp phase using the events
from rtapp, rather than blindly relying on the rtapp profile.
Depends on https://github.com/ARM-software/lisa/pull/1266 since signal convergence is fully delegated to the buffer phase, which means it has to run on the right CPUs to allow run-queue signals to converge.
> tests: load_tracking: CPUMigrationBase: Use rtapp phase event

- lisa/conf.py
- tests/test_conf.py
Improve DerivedKey support:
* Allow base keys outside the current subtree with the "magic" `..` key that goes one level up
* Honor eval_deferred for base keys when computing the value/displaying it
> Improve MultiSrcConf

- lisa/utils.py
Give a resolvable name to the inner collections.namedtuple() class contained in
the lisa.utils.namedtuple() class so that instances can be pickled.
> lisa.utils: Fix namedtuple() serialization

- lisa/utils.py
It currently breaks deserialization in ruamel.yaml due to this bug:
https://bitbucket.org/ruamel/yaml/issues/329/typo-in-constructorpy-prevents-loading
This commit can be reverted once the bug is fixed.
> lisa.utils: Avoid __slots__ use in lisa.utils.namedtuple()

- doc/traces/plat_info.yml
- lisa/analysis/cpus.py
- lisa/analysis/load_tracking.py
- lisa/platforms/platinfo.py
- lisa/tests/base.py
- lisa/tests/scheduler/load_tracking.py
- lisa/tests/scheduler/misfit.py
- lisa/tests/staging/sched_android.py
- lisa/wlgen/rta.py
- tests/assets/plat_info.yml
- tests/assets/sched_load/plat_info.yml
BREAKING CHANGE
The old "cpu-capacities" content can now be found under "cpu-capacities/orig".
> Change PlatformInfo "cpu-capacities" key

- lisa/conf.py
- lisa/target.py
Systemd uses cgroups and using the freezer via devlib breaks a number of
assumptions, since tasks end up being moved around without any care for their
original group.
> lisa.target: Disable freezer cgroup for systemd

- lisa/utils.py
Inventory names might not be unique across domains so check for the py domain as
well:
https://github.com/ARM-software/lisa/issues/1308
#fixes #1308
> lisa.utils: Make get_doc_url() robust against names of other domains

- lisa/tests/scheduler/load_tracking.py
- lisa/tests/scheduler/util_tracking.py
- lisa/tests/staging/schedutil.py
interactive value is now already False in non-interactive context, and True
inside a Jupyter notebook. Having an interactive debug plot in notebooks is
actually useful as it can be considered as part of the output of the test
methods.
> lisa.tests: Remove interactive=False for debug plots

- tools/wltests/helpers
Only remove the files we'll replace by a subsequent push,
not all files under /vendor/lib/modules.
> wltest/helpers: only remove the files we'll push

- lisa/doc/helpers.py
Sphinx seems to dislike this option. Remove it as it's not that useful anyway.
> lisa.doc.helpers: Avoid unsupported "width" option in reST list-table

- lisa/conf.py
Make sure that TypedList[int] is TypedList[int] will always hold. That
is necessary to implement typeclass instances on these container types.
> lisa.conf: Make generic container unique

- lisa/trace.py
Use mmap as it does not seem to harm performance. It might help avoiding
some copies for large dataframes.
> lisa.trace: Read parquet files with mmap

- lisa/trace.py
This name is a placeholder used by trace-cmd when it cannot resolve the task
name, so ignore it as we have our own resolution mechanism.
> lisa.trace: Avoid comm=<...> in Trace.task_ids

- lisa/analysis/base.py
Decouple the length of `markers` and `linestyles`.
> analysis plots: lift restriction on cycler created by markers and linestyles 

- lisa/notebook.py
Add missing reference to ``trace``.
> lisa.notebook: Fix typo in interact_tasks() docstring

- lisa/analysis/rta.py
This decorator can only be used on functions returning a dataframe with string
column names. numpy.float64 or pandas.Series cannot be cached.
> lisa.analysis.rta: Remove unwanted TraceAnalysis.cache

- lisa/analysis/rta.py
- lisa/datautils.py
- lisa/tests/base.py
- lisa/tests/scheduler/misfit.py
Using Series.values can lead to a copy, and is no necessary when all we want is
to index in it. `iloc[N]` is the way to go.
> lisa: Remove unnecessary uses of Series.values

- lisa/trace.py
Allow parsing all and only the events specified in ``events``. This provides
early failure, as well as avoiding lazy loading. This includes lazy loading used
to detect available events, which can result in a significant slow down for
large traces.
> lisa.trace: Add Trace.__init__(strict_events=False) parameter

- lisa/target.py
Accessing the modules via the devlib target instance will bypass module
autoloading provided by lisa.target.Target.
> lisa.target: Access modules on the lisa.target.Target instance directly

- lisa/tests/base.py
- lisa/tests/scheduler/eas_behaviour.py
Instead of rounding down the percentage, return a float. lisa.wlgen.rta will
round the values at the step to avoid precision loss as much as possible.
> lisa.tests.base: Return float in RTATestBundle.unscaled_utilization()

- lisa/utils.py
- lisa/wlgen/rta.py
Similar to builtin range() but works with floats and raises exceptions if
start/stop is not compatible with the sign of step (rather than returning an
empty iterator).
> lisa.utils: Add value_range()

- lisa/git.py
- lisa/wa_results_collector.py
This PR allows to improve the kernel identification into wa_results_collector:
sha1 ref >> commit message >> sha1 >> kernel version
This allow to support kernel version without any sha1.
> wa_results_collector: kernel identifier improvement

- setup.py
The issue encountered for matplotlib widget (at least):
https://github.com/matplotlib/jupyter-matplotlib/issues/193
> setup.py: Force jupyterlab <= 1.2.6 until extensions are fixed

- lisa/platforms/platinfo.py
- lisa/wlgen/rta.py
Latest rt-app supports NUMA memory binding:
https://github.com/scheduler-tools/rt-app/blob/b3a5408c6d9f7eeb1b91d8286757cbd38fefa9cb/doc/tutorial.txt#L287
This will allow testing of kernel NUMA_BALANCING code.
The goal is to be able to bind memory allocations to a set of specific 
NUMA nodes and test that task placement decisions will be correct.
> Support for new rt-app feature (nodes_membind)

- setup.py
This reverts commit cb9dd2f4048cb1369657436be819144705d1fdba.
> Revert "setup.py: Force jupyterlab <= 1.2.6 until extensions are fixed"

- tests/test_wlgen_rtapp.py
Expect the workload to be bound to all NUMA nodes of the target.
> tests: fix rtapp test with NUMA nodes

- lisa/notebook.py
matplotlib < 3.1 does not have the MouseButton Enum, but 3.1 is not
compatible with Python >= 3.6
> lisa.notebook: Fix MouseButton with matplotlib < 3.1

- lisa/analysis/functions.py
- lisa/doc/helpers.py
- lisa/tests/base.py
- lisa/typeclass.py
Rather than str.lower(), str.casefold() is designed to make comparison
against a reference work better with unicode.
> lisa: use str.casefold() to canonicalize strings

- lisa/analysis/rta.py
Remove explicit iteration over rows in favor of DataFrame.apply()
> lisa.analysis.rta: Fix RTAEventsAnalysis.rtapp_tasks

- doc/conf.py
Since some part of the documentation are generated from the git history,
use a non-shallow clone.
> doc: Use non-shallow clone on readthedocs

- lisa/doc/helpers.py
Add a User-Agent header to request since some servers return 403
Forbidden if no header is passed.
> lisa.doc.helpers: Fix check_dead_links()

- doc/man1/exekall.1
- tools/exekall/exekall/main.py
Allow dropping into the python debugger when an exception occur in the
code ran by exekall,
> exekall: Add exekall run --pdb option

- tools/kmodules/sched_tp/0001-sched-add-a-module-to-convert-tp-into-events.patch
- tools/kmodules/sched_tp/sched_events.h
- tools/kmodules/sched_tp/sched_tp.c
util_est is now part of sched_tp
There was a change to a field in struct sched_avg, cater for that.
> tools/sched_tp: Update sched_tp module to include new events

- lisa/conf.py
- lisa/exekall_customize.py
- lisa/target.py
- lisa/utils.py
Since LISA configurations allows for arbitrary code execution, add notes
in various places to inform about that.
> lisa: Add warning about YAML file loading

- doc/man1/exekall.1
- tools/exekall/exekall/main.py
Nested calls to add_argument_group() lead to the nested groups to simply
not be shown in --help. Therefore, avoid nesting such calls.
> exekall: Avoid nested argument groups

- lisa/trace.py
When a list of events is checked, has_events() would always return True.
Fix the typo so it checks the events that were asked for.
> lisa.trace: Fix typo in has_events() leading to returning True

- lisa/trace.py
Save some memory and speed-up selection based on function for the
print/bprint/bputs dataframes.
> lisa.trace: use category for func col of print/bprint/bputs df

- setup.py
Some operations with parquet result in:
TypeError: read() got an unexpected keyword argument 'memory_map'
So temporarily avoid using versions higher than 1.0.3.
> setup.py: Avoid using pandas == 1.0.4

- tools/exekall/exekall/_utils.py
Debug log includes the module name and line number of the code emitting
the log entry. Instead of reporting the helper in _utils, report the
caller of that helper.
> exekall: Display more useful line number in debug log

- lisa/analysis/load_tracking.py
Add linebreak to fix the bullet list in a docstring.
> lisa.analysis.load_tracking: Fix bullet list in docstring

- tools/lisa-execute-notebook
Avoid using colors in IPython output since it ends up being used on
non-terminal stdout/stderr, leading to unreadable logs when redirected
to files.
> tools: lisa-execute-notebook: Remove IPython colors

- ipynb/examples/typical_experiment.ipynb
- ipynb/profiling/kernel_functions_profiling.ipynb
Since "name" has been made optional, it is now after "profile"
> ipynb: Fix RTA.by_profile() calls parameter order

- doc/man1/exekall.1
- tools/exekall/exekall/main.py
Since --replay is used for debugging, make it imply --pdb so that all
users will benefit from that.
> exekall: --replay now implies --pdb

- lisa/energy_model.py
Warn about missing idle states in EnergyModel.from_target() so that we
report missing idle states in the context of a specific target.
This is to be preferred to a warning in __init__ that would trigger on
any object built, even in cases where it could be legitimate, since that
is just a plain mutable data structure.
> lisa.energy_model: Warn when a CPU has no idle states

- shell/lisa_shell
Replace "print" ZSH builtin by POSIX printf (likely a typo)
> shell: Replace print by printf

- lisa/platforms/platinfo.py
- lisa/target.py
Add Target(lazy_platinfo=False) to lazily load the plat_info from the
target, in order to speed up target connection time at the expense of
more useful logging.
> lisa.target: Allow lazy plat_info loading

- tools/batch-rebase
Use -- to separate positional parameters in command involving arbitrary
user input.
> tools: batch-rebase: Use -- in commands

- tools/batch-rebase
git rev-list expects references before -- rather than after for some
reason, even if references are not to be considered as options.
> tools: batch-rebase: Avoid -- with git rev-list

- setup.py
Prepare comming changes that will require Python >= 3.6.
It's time to upgrade now before any such change is merged.
> setup.py: Bump required Python to >= 3.6

- lisa/datautils.py
Add missing signal so that
FrequencyAnalysis.df_cpus_frequency(signals_init=True) can make use of
the userspace events outside of the window.
> lisa.datautils: Add signal for userspace@cpu_frequency_devlib

- lisa/conf.py
- tools/lisa-platinfo-extract
Add MultiSrcConf.eval_deferred(error='raise') parameter to keep going when
exceptions are raised with error='log'. This allows the consumer to
gather as many values as possible, and handle the exception later when
iterating over the object.
> lisa.conf: Improve exception handling of deferred values

- lisa/trace.py
Document that the time-range metadata has to be provided by parsers when
asked for.
> lisa.trace: Improve docstring of TraceParserBase

- lisa/analysis/tasks.py
- lisa/tests/base.py
- lisa/tests/scheduler/load_tracking.py
- lisa/trace.py
Prevent Enum's metaclass to set TaskState.__module__ = '<unknown>' by
providing StateInt.__reduce__
> lisa.analysis.tasks: Fix TaksState.__module__

- lisa/utils.py
Correctly indent the message when it spans multiple lines.
> lisa.utils: Fix deprecate(msg=...) for multilines msg

- lisa/analysis/tasks.py
Pandas dataframes cannot be tested for membership in a container, since
comparison between a dataframe and another object with == returns a
dataframe instead of a boolean.
> lisa.analysis.tasks: Fix use of membership test for dataframes

- tools/bisector/bisector/bisector.py
Previously, results that were neither pass, fail or error were simply
ignored for some processing.
> bisector: Allow -oexport-logs for UNDECIDED results

- lisa/tests/base.py
Ensure we don't fixup twice the res_dir of the toplevel object.
> lisa.tests.base: TestBundle._fixup_res_dir handle reference cycle

- lisa/trace.py
Drop initializing Trace object if specified trace file does not exist.
There is not much point in proceeding if the trace itself cannot be located.
> lisa/trace: Bail out if trace file does not exist

- tests/test_test_bundle.py
When creating a TestBundle instance from a dir, res_dir is
never set. However the variable is required in case of
a new serialization, or to set the res_dir variable of
the TestBundle instances referenced in __children_test_bundles.
> lisa.tests.base: TestBundle: set res_dir in from_dir()

- lisa/tests/scheduler/util_tracking.py
Properly split cases for each rtapp phase, rather than conflating it
with the signal checks that lead to wrong assumptions.
> lisa.tests.scheduler.util_tracking: Fix expectations

- lisa/stats.py
The columns to aggregate can be auto-detected. Make sure the unit column
is not taken as part of it, as it will confuse some methods that expect
the unit to not be part of the aggregation column.
> lisa.stats: Do not use unit column for aggregation

- lisa/trace.py
Add missing group for __cpu to parse the CPU common field of each event.
> lisa.trace: Add __cpu to HRTxtTraceParser.HEADER_REGEX

- lisa/trace.py
BREAKING CHANGE
Since text trace are typically in the human readable format (as opposed
to the semi-machine readable raw output of trace-cmd report), use this
by default for .txt extension.
If the old behaviour is still wanted, traces can be built with:
from lisa.trace import Trace, TxtTraceParser
Trace(..., parser=TxtTraceParser.from_txt_file)
The new behaviour is equivalent to:
from lisa.trace import Trace, HRTxtTraceParser
Trace(..., parser=HRTxtTraceParser.from_txt_file)
As a side effect, this will enable lisa-plot to work out of the box (to
some extent) with such text trace.
> lisa.trace: Use HRTxtTraceParser by default for .txt trace

- tests/test_energy_model.py
- tests/test_trace.py
Explicitly use TxtTraceParser.from_txt_file where appropriate.
> self tests: Fix test_trace.py to use adequate parser

- lisa/trace.py
Meta events (like userspace@... or trace_printk@...) are extracted from
existing dataframes. The text data is expected to be encoded as bytes,
so that parser that can provide bytes out of the box avoid a conversion
(and x4 in memory consumption incurred by str).
That said, some parsers may return string columns, in which case it
needs to be converted, as regexes are written against bytes type.
> lisa.trace: Ensure meta event source df use bytes

- lisa/energy_model.py
Some topologies like the Pixel4 have a single CPU on a cluster. In this
case, the CPU and the cluster are described similarly:
e.g. multiple CPUs cluster:
Single CPU description: (4, )
Cluster description: (4, 5, 6)
e.g. single CPU cluster:
Single CPU description: (7, )
Cluster description: (7, )
This is problematic in _estimate_from_active_time(), as the energy computed
would be overwritten. Ensure a single result table initialization when
several nodes have the same description. This avoid losing the energy
computed for the first nodes of an identical description.
Signed-off-by: Vincent Donnefort <vincent.donnefort@arm.com>
> energy_model: fix single CPU cluster energy estimate

- tools/lisa-plot
Remove extra pyplot.show() call that is likely a left over from a
refactoring.
> tools: lisa-plot: Only use pyplot.show() for interactive

- lisa/conf.py
- lisa/doc/helpers.py
- lisa/energy_meter.py
- lisa/platforms/platinfo.py
- lisa/tests/base.py
- lisa/trace.py
- lisa/utils.py
Configuration classes docstrings can now use the {yaml_example}
placeholder in addition to {generated_help}.
> lisa.conf: Add default conf example to conf class docstrings

- shell/lisa_shell
Minimizing takes a very long time and is not needed since the install is
local, there is no point in minimizing network traffic.
> lisa-install: Avoid minimizing jupyter lab extensions

- lisa/tests/base.py
Make it clearer that the regex only matches the content of the message,
not the header part consisting in facility, timestamp and subsystem.
> lisa.tests.base: Improvde DmestTestConf help

- doc/contributors_guide.rst
- pytest.ini
- setup.cfg
- setup.py
- tests/test_conf.py
- tests/test_datautils.py
- tests/test_energy_model.py
- tests/test_events_checkers.py
- tests/test_target.py
- tests/test_test_bundle.py
- tests/test_trace.py
- tests/test_wlgen_rtapp.py
- tests/utils.py
- tests/wlgen.py
- tools/travis_tests.sh
nose is not maintained anymore and has a number of annoying behaviours,
so replace it with the more widely-used pytest.
PENDING ON:
https://github.com/ARM-software/devlib/pull/514
Otherwise, the tests fail at import time since the SyntaxWarning is turned into an error
> self tests: Replace nose by pytest

- lisa/tests/base.py
Entries with an empty message (or full of whitespaces) are ignored, to
avoid any issue with mulitline messages that might use such empty lines
for formatting.
> lisa.tests.base: Ignore empty dmesg lines in test_dmesg()

- .readthedocs.yml
- lisa/tests/base.py
New numpy pre-release version only supports Python >= 3.7, and for some
reason, pip seems to pick it despite not being told to do so with --pre.
Since we don't really *need* Python 3.6, just bump the version so the
doc keeps building.
https://github.com/numpy/numpy/issues/17909
> .readthedocs.yml: Bump Python version to 3.7

- doc/kernel_tests.rst
- lisa/tests/staging/utilclamp.py
This new test intends to verify basic support for UClamp. A series of 8 phases
sets a UClamp min value for a task whom duty cycle would create a lower
utilization. The test will make sure the actual capacity, allocated for this
task, matches the UClamp min value.
> lisa.tests.scheduler.uclamp

- lisa/stats.py
When giving a Series of NaN to matplotlib for the error bars, it will
trigger a warning from numpy deep down the stack. Avoid that by removing
the error bar altogether in that case.
> lisa.stats: Avoid warning triggered by numpy

- lisa/trace.py
Instead of `x == False`, use more polymorphic `not x and x is not None`.
> lisa.trace: remove comparison with False

- lisa/tests/base.py
Do not modify attributes when they are constant at the instance level.
Do not modify dataframes returned by analysis functions.
> lisa.tests.base: Add missing copies

- lisa/datautils.py
Currently the case where task_ids is empty were not handled. This can
happen since the introduction of:
(54d0639 lisa.tests.base: ignore all threaded IRQs)
> lisa.datautils: Fix df_filter_task_ids() empty task_ids

- tools/bisector/bisector/bisector.py
Artifactorial seems to like corrupting file extensions by adding some
unique string in the middle. Make bisector format detection more robust
against that.
> bisector: Deal with corrupted extensions

- lisa/trace.py
Now that trace-cmd report requires -F to avoid dropping funcgraph_exit
events, we need to ensure that all the events we ask are actually
existing in the kernel that was used to produce the trace. Filter out
all the events that cannot be found in the trace.
> lisa.trace: Prefilter events to only ask trace-cmd for real ones

- lisa/datautils.py
Remove portions of constant signal before taking the envelope, to avoid
getting some points as both part of the local maxima and minima.
> lisa.datautils: Remove bias in series_envelope_mean()

- lisa/analysis/frequency.py
When no cpu_frequency event has been found, df_cpus_frequency will try to
get the devlib ones. In that case, the returned DataFrame won't use 'Time'
as an index. Some tests are relying on this name, so let's harmonize it.
> lisa.analysis.frequency: 'Time' as an index name for df_cpus_frequency

- lisa/tests/staging/utilclamp.py
The test is skipping the first task activation, as the utilclamp values are
set afterward. However, if this first activation is preempted, the
preemption return would be seen as a new activation while it doesn't go
through CPU selection, leading to a test failure.
Ignoring preemption fixes this issue and keeps the test sane.
> lisa.tests.staging.utilclamp: ignore preemption in task activation

- lisa/utils.py
Ensure repeated calls are not ignored by passing force=True to
logging.basicConfig()
> lisa.utils: Fix setup_logging() repeated calls

- lisa/trace.py
Since trace-cmd can now properly report task names with spaces in them,
handle space in the regex.
> lisa.trace: Fix trace-cmd parsing regex

- doc/traces/plat_info.yml
- lisa/wlgen/rta.py
Use (0, 1024) on kernels not supporting clamp removal with (-1, -1)
> lisa.wlgen.rta: Fix uclamp defaults on older kernels

- lisa/pelt.py
- lisa/tests/scheduler/load_tracking.py
The PELT clock is typically not available on task enqueue/dequeue,
but aligning the activations on the preceding PELT events makes the
sleep time inaccurate.
Fix that by providing a fake clock sample based on the ftrace clock
delta, rescaled using the nearest time scaling factor.
> lisa.pelt: Fixup simulate_pelt() clock on task enqueue/dequeue

- tools/exekall/exekall/engine.py
Use the legacy Pickler.dispatch_table API for Python < 3.8
> exekall: Fix exception unpickling for Python < 3.8

- ipynb/examples/typical_experiment.ipynb
Using the workload as a context manager is important to ensure cleanup
and correct process handling.
> ipynb: Add missing use of Workload as a context manager

- lisa/wlgen/workload.py
Similar to Popen, devlib's BackgroundCommand.__exit__ will close
stdin/stdout/stderr of the process before waiting on it. Since this will
usually result in early termination of the workload, wait() on it
explicitly so that we gracefully wait for the command to finish before
closing its streams.
> lisa.wlgen.workload: Add missing wait() call in run()

- lisa/wlgen/workload.py
Re-raise immediately the exceptions of Workload._run() from within
Workload.__exit__(), instead of just raising upon access to the "output"
attribute of the context manager.
> lisa.wlgen.workload: Propagate exception from _run()'s exit path

- doc/kernel_tests.rst
Silence Python warnings while emitting test list to avoid breaking the
reStructuredText output.
> doc: Avoid warnings while emitting test list

- lisa/wlgen/workload.py
Only reinitialize the object if the settings are not None.
> lisa.wlgen.workload: Fix run() parameters compat layer

- lisa/analysis/base.py
Avoid an empty HTML document with an error when the line length is too
long.
> lisa.analysis.base: Fix analysis HTML output

- doc/kernel_tests.rst
- ipynb/examples/typical_experiment.ipynb
- ipynb/profiling/kernel_functions_profiling.ipynb
- lisa/exekall_customize.py
- lisa/test_example.py
- lisa/tests/base.py
- lisa/tests/cpufreq/sanity.py
- lisa/tests/hotplug/torture.py
- lisa/tests/scheduler/eas_behaviour.py
- lisa/tests/scheduler/load_tracking.py
- lisa/tests/scheduler/misfit.py
- lisa/tests/scheduler/sanity.py
- lisa/tests/scheduler/util_tracking.py
- lisa/tests/staging/numa_behaviour.py
- lisa/tests/staging/sched_android.py
- lisa/tests/staging/schedutil.py
- lisa/tests/staging/utilclamp.py
- lisa/trace.py
- lisa/utils.py
- tests/test_test_bundle.py
- tools/tests.sh
Create a composed collector from generic infrastructure to pass to `_from_target`, so that:
* Tests don't have to fiddle with the details of the collector they use, which can then be fully encapsulated in a mixin class.
* Mixin classes like FtraceTestBundle and DmesgTestBundle can register their own collector automatically
* The user can pass a custom collector that will be ran as well
> Improve tests' collector handling

- doc/man1/exekall.1
- tools/exekall/doc/man/man.rst
- tools/exekall/exekall/_utils.py
- tools/exekall/exekall/engine.py
- tools/exekall/exekall/tests/suite.py
- tools/exekall/exekall/utils.py
Support methods polymorphic in their return values in the following
limited case:
import typing
class Base:
ASSOCIATED_CLS = typing.TypeVar('ASSOCIATED_CLS')
def foo(self) -> 'Base.ASSOCIATED_CLS':
return X
class Derived1(Base):
X = 1
ASSOCIATED_CLS = type(X)
class Derived2(Base):
X = 'hello'
ASSOCIATED_CLS = type(X)
In that case, exekall will correctly infer that Derived1.foo() returns an
int and Derived2.foo() returns a string.
> exekall: Add support for associated types

- lisa/energy_meter.py
Devlib instruments should be used, and if there is a need to manage
configuration files on LISA side, we can add wrapping class like we did
for FtraceCollector and DmesgCollector.
The current state of the code would require a deep clean, but testing is
an issue because it requires specific hardware, so best done when it is
actually needed for a task.
> lisa.energy_meter: Deprecate all classes

- lisa/utils.py
Allow lookup of __class__ attribute on partially initialized objects, so
that isinstance() works.
> lisa.utils: Allow PartialInit.__class__ lookup

- lisa/trace.py
Check that the ftrace kernel config is enabled to raise a more explicit
error.
> lisa.trace: Check for CONFIG_FTRACE

- lisa/tests/base.py
- lisa/tests/hotplug.py
During the hotplug sequence it is very likely that some IRQ messages,
related to affinity, will trigger due to the IRQs migration. They are
harmless and we can ignore them.
> lisa.tests.hotplug: Ignore IRQs related Dmesg

- lisa/trace.py
Trace time-range is cast to int which is incorrect as it is float.
> MockParser: Fix time-range trace meta data

- tools/exekall/exekall/engine.py
Use the callable as-is when inspecting the signature, rather than
unwrapping the decorator stack. This allows the decorators to provide a
modified signature. functools.wraps() takes care of propagating the
signature properly for the other cases where the decorator does not
attempt to change the signature.
> exekall: Do not unwrap decorator stack when getting signature

- lisa/trace.py
Do not assume all passed context managers are collectors. If they don't
have a "NAME" attribute, they will just not be accessible using the
Mapping interface, but will still be entered/exited.
> lisa.trace: Allow passing basic CM to ComposedCollector

- lisa/tests/scheduler/load_tracking.py
- lisa/utils.py
- lisa/wlgen/rta.py
Fix possible RecursionError in RTAPhaseTree.children property on deeply
nested trees, such as the ones resulting from repeated accumulation
using + operator.
Computing the children when the object is created fixes the issue since
the recursion will always hit the memoization cache, avoiding an actual
deep recursion that would happen the first time the whole tree is
inspected.
> lisa.wlgen.rta: Fix a RecursionError

- setup.py
Avoid issue:
https://github.com/spatialaudio/nbsphinx/issues/563
> setup.py: Freeze jinja2 version to avoid breaking nbformat

- lisa/wa.py
The example given for lisa.wa.WATraceCollector currently passes an
int to trace.analysis.idle.df_cluster_idle_state_residency(), which
expects a list(int). Because of that, attempts to run the example fail.
Wrapping the cpu id in a list during the function call solves the issue
without changing what the example is supposed to do.
> doc: lisa.wa.WATraceCollector: Fix example error

- .github/workflows/test.yml
- lisa/analysis/functions.py
Speed up the checks and hopefully avoid what seems to be github
throttling in the number of jobs.
> github: Only test on Pytohn 3.6 and 3.9

- lisa/wlgen/rta.py
phase_default, not phase_defaults. This affected the generation of multiple
phases when LISA tries to optimize the rt-app json file.
> lisa.wlgen.rta: Fix phase_default typo

- lisa/pelt.py
Shift the activations signal so that it describes the state of the
entity until now, rather than the state of the entity over the next
period.
> lisa.pelt: Fix simulate_pelt()

- ipynb/examples/typical_experiment.ipynb
Collect task_rename ftrace event since that is now necessary for some of
the tasks analysis.
> ipynb: Update typical_experiment.ipynb to collect task_rename

- lisa/wa.py
When filling wa_path, WAOutput is looking for the longest common path,
shared by all the WA folder path. e.g
foo/bar foo/bar2 would become respectively bar and bar2.
A problem occurs when using a path with WAOutput that is the root of a
WA folder. (e.g. foobar where foobar/__meta exists). This common path
(common_prefix) would then be PosixPath('.'). Pathlib cannot use a such
path with relative_to() and raises the following error:
ValueError: '/foo/bar/' does not start with ''
Fixing this problem by converting common_prefix to an absolute path.
> lisa.wa: Fix common prefix for wa_path

- lisa/analysis/load_tracking.py
- lisa/trace.py
Ensure it is always called with either a TraceEventCheckerBase or an
iterable of strings, that are then combined with AndTraceEventChecker.
> lisa.trace: Fix MissingTraceEventError invocations

- doc/setup.rst
Since we don't distribute a patch anymore, remove the associated
instructions.
> doc/setup.rst: Remove kernel module patch directions

- tools/batch-rebase
"f4ae7be5  lisa.generic: Rename to lisa._generic" missed one file that
needed lisa.generic renamed to lisa._generic. Fix it here.
> batch-rebase: rename to lisa._generic

- tools/exekall/exekall/_utils.py
FIX
Set attribute on parent package when importing a module. This allows
doing:
import foo
print(foo.bar)
> exekall: Set package attribute when importing submodule

- lisa/datautils.py
Integrating is usually a sign of a windowing issue and will lead to a
misleading 0 value.
> lisa.datautils: Raise in series_integrate() if less than 2 points

- lisa/analysis/thermal.py
- lisa/trace.py
FIX
Fix parsing of thermal_power_cpu_get_power and thermal_power_cpu_limit.
ipi_raise target_cpus field is also now turned into a tuple rather than
a list for memory efficiency.
> lisa.trace: Fix parsing of thermal events

- doc/man1/bisector.1
- doc/man1/exekall.1
- doc/man1/lisa.1
- tools/exekall/exekall/engine.py
PEP 604 annotation such as "int | None" raise a TypeError on older
versions of Python. Ignore such annotation by re-raising the appropriate
exception.
Fixes https://github.com/ARM-software/lisa/issues/1743
> exekall: Handle PEP 604 annotation

- lisa/utils.py
Asyncio debug logging is very verbose so turn it off in setup_logging().
> lisa.utils: Remove asyncio debug logging

- install_base.sh
VirtualBox currently does not support aarch64 machines.
> install_base: Do not install VirtualBox on aarch64 machines

- tools/exekall/exekall/_utils.py
- tools/exekall/exekall/utils.py
FIX
Fix invocations such as: exekall run lisa foo --conf target_conf.yml
where "foo" is a simple python file, not inside any specific package.
> exekall: Fix standalone module handling passed on CLI

- tools/tests.sh
For some reason some legitimate commits are touching external/, so allow
them to.
> tools/tests.sh: Add allowed commits to touch external/

- lisa/wlgen/rta.py
FEATURE
Allow letting leaf values take precedence over the values set in nodes
closer to the root.
> lisa.wlgen.rta: Add leaf_precedence()

- lisa/target.py
FIX
Remove attempt to call target.adb_root() when username is None. Devlib
API has changed and this is now a connection method. Calling that method
on the connection is not a fix as connections are created and destroyed
per thread, so applying it for the main thread is only kicking the can
down the road.
Since connecting as root can be achieved by simply using username='root'
and feeding that information into the connection settings, remove the
automatic attempt.
> lisa.target: Remove adb rooting attempt

- lisa/tests/hotplug.py
- pytest.ini
- setup.cfg
FIX
Inheriting from TestBundle should come last in order to override methods
provided by OptinalFtraceTestBundle & friends by the non-optional
variant.
> lisa.tests.hotplug: Fix HotplugRollback MRO

- lisa/target.py
FIX
Allow None to be passed so that it can be used with env vars.
> lisa.target: Allow None for target-conf/kernel/src config

- lisa/trace.py
- tools/lisa-buildroot-create-rootfs
FIX
Ensure that TraceEventCheckerBase behaves like a container, so it can be
tested for emptiness easily.
> lisa.trace: Add TraceEventCheckerBase.__bool__

- lisa/tests/base.py
- lisa/tests/hotplug.py
We tried to have an accurate filtering for IRQ related messages during
hotplug ... But more piles up. It makes it simply untestable and
none of those messages follows a pattern we could easily match. Let's
just ignore any that contains the word IRQ.
> lisa.tests.hotplug: Ignore all "IRQ" related messages in Dmesg

- .github/workflows/test.yml
- setup.py
Bump the minimum Python version to 3.7 in prevision of some changes in
devlib requiring 3.7 as well.
> setup.py: Bump minimal Python version to 3.7

- lisa/_assets/kmodules/sched_tp/sched_events.h
- lisa/_assets/kmodules/sched_tp/sched_tp.c
sched_cpu_capacity depends on a tracepoint that was added on 5.10, so
protect it with the right kernel version.
Also the tracepoint makes a call to arch_scale_freq_capacity() which
doesn't compile on x86 as it points to non-exported function. Just wrap
it with a warning until someone who cares finds a better alternative for
those archs.
> sched_tp: Handle a couple of compilation errors

- doc/setup.rst
Add a missing config that appears to be necessary according to:
https://patchwork.kernel.org/project/netdevbpf/patch/20211115191840.496263-2-memxor@gmail.com/
> doc/setup.rst: Add BTF kernel config

- lisa/_assets/kmodules/sched_tp/sched_events.h
- lisa/_assets/kmodules/sched_tp/sched_tp.c
They should work too and were accidentally omitted.
---
Only tested against arm64 still
> sched_tp: Allow sched_cpu_capacity() for arm32 platforms

- lisa/_assets/kmodules/sched_tp/sched_events.h
- lisa/_assets/kmodules/sched_tp/sched_tp.c
This is a tricky one. sched_nr_running I believe is optional, but @ionela-voinescu reported that not including sched_util_est_{se,cfs} leads to these errors.
```
[2021-11-29 21:59:22,712][EXEKALL] ERROR  ValueError: Events are missing in the kernel. Enable kmod_auto_load=True to attempt setting them up: (sched_cpu_capacity and sched_cpu_capacity and sched_util_est_cfs and sched_util_est_cfs and sched_util_est_se and sched_util_est_se)
```
It's either we fail to build the module for these required events. Or make LISA less fussy about them being missing and just skip the tests that require them.
> Fix compilation errors on android v5.4

- lisa/utils.py
FIX
Fix SimpleHash equality check. dict.values() cannot be compared for
equality in a useful manner.
> lisa.utils: Fix SimpleHash.__eq__

- lisa/wlgen/rta.py
The effect of `PeriodicWload(guaranteed_time='sleep')` can be seen with:
```
from lisa.platforms.platinfo import PlatformInfo
from lisa.wlgen.rta import *
task1 = RTAPhase(
prop_wload=PeriodicWload(
duty_cycle_pct=10,
period=16e-3,
duration=1,
guaranteed_time='sleep',
),
)
profile = {'task1': task1}
plat_info = PlatformInfo.from_yaml_map('./doc/traces/plat_info.yml')
conf = RTAConf.from_profile(profile, plat_info=plat_info)
print(conf.json)
````
> Add TimerWload

- install_base.sh
Some packages like tzdata require user input to select timezone when
installing, even with "-y". Set DEBIAN_FRONTEND=noninteractive to avoid
installation hanging in non interactive environments.
> install_base.sh: Set DEBIAN_FRONTEND=noninteractive for apt

- tools/bisector/bisector/bisector.py
FIX
Raise an exception rather than returning None, which will only lead to
an exception in the caller.
> bisector: Do not return None in Report.load()

- lisa/_kmod.py
FIX
Previously, PATH was not set/reset to any specific value when running a
command in the Alpine chroot. This lead to PATH being inherited from the
user, even though it did not specifically make sense inside the chroot.
Fix that by running "source /etc/profile" to provide a sane default for
basic env var.
> lisa._kmod: Fix PATH in Alpine chroot

- lisa/trace.py
FEATURE
Optional events are currently ignored if the kernel does not provide
them. Instead, attempt to build the module if the kernel does not
provide a missing event. This is especially important as the user's
events from the user-provided FtraceConf are treated as optional.
> lisa.trace: Try building the kmod for optional events

- lisa/_kmod.py
FIX
Fix conflicting description of defaults for KernelTree(build_env=...)
> lisa._kmod: Fix KernelTree docstring

- lisa/fuzz.py
- lisa/monad.py
- lisa/utils.py
- lisa/wlgen/rta.py
- pytest.ini
Example taken from `lisa.wlgen.rta` doc:
```python
from lisa.wlgen.rta import RTA, RTAPhase, PeriodicWload, RunWload, SleepWload, override, delete, WithProperties, task_factory, RTAConf
from lisa.fuzz import Float, Int
from lisa.platforms.platinfo import PlatformInfo
from lisa.target import Target
#
@task_factory
async def make_task(run_duration):
async with WithProperties(name='first', uclamp=(256, 512)):
await RunWload(run_duration)
sleep_duration = await Float(min_=1, max_=5)
sleep_duration = round(sleep_duration, 2)
async with WithProperties(name='second'):
await (
SleepWload(sleep_duration) +
PeriodicWload(
duty_cycle_pct=20,
period=16e-3,
duration=2,
)
)
task = make_task(run_duration=1)(seed=1)
task = task.with_props(uclamp=(300, 800))
task = task.with_props(uclamp=override((400, …
```
> Async wlgen API (2)

- lisa/trace.py
BREAKING CHANGE
Trace.df_event() used to set a .name attribute on dataframes it returns.
This is unfortunately problematic, as it will also set the value of a
column named "name" if it exists.
The replacement is df.attrs['name'] and has been there for a while now.
It's also the recommended way of doing it by pandas documentation
itself.
> lisa.trace: Drop df.name attribute

- lisa/notebook.py
FEATURE
Replace the panel.widgets.DataFrame widget by Tabulator, which has more
features.
Note: scrolling into the dataframe from clicking on plot is currently a bit annoying since that leaves the selected row one past the end of the viewable part. This PR fixes that:
https://github.com/holoviz/panel/pull/3288
> lisa.notebook: Use Tabulator panel widget

- .github/workflows/test.yml
FIX
Ubuntu seems to have changed the permissions of debugfs at
/sys/kernel/debug to remove all permissions except for the root user.
This unfortunately breaks (among other things) the CPU capacities
reading, which is necessary to generate rt-app workloads.
Workaround the problem by restoring permissions until a better fix is
found.
> .github: Add read permissions to debugfs

- lisa/analysis/frequency.py
- lisa/datautils.py
FIX
Add SignalDesc for clk_set_rate, clk_enable, clk_disable so that
requesting the dataframe for one of these will always provide the
occurence before the beginning of the trace window for each clock name.
> lisa.datautils: Add SignalDesc for clk_* events

- lisa/analysis/rta.py
- lisa/datautils.py
- lisa/notebook.py
- lisa/tests/scheduler/load_tracking.py
FIX
Pandas currently recommands replacing uses of the deprecated
Index.get_loc(x) by Index.get_indexer([x]).
https://github.com/pandas-dev/pandas/issues/46763
This is unfortunately not accurate and results in breakages:
* get_loc(x) returns an integer
* get_indexer([x]) returns an array of integer
Using DataFrame.iloc[] on the output of get_indexer() will therefore
give a single-row dataframe instead of a series, which leads to various
issues.
Replace get_indexer([x]) by get_indexer([x])[0] instead.
> lisa: Fix uses of Index.get_indexer()

- lisa/_kmod.py
FIX
Fix path in _do_compile() that was not returning a tuple as expected.
> lisa._kmod: Fix DynamicKmod._do_compile()

- doc/plot_conf.yml
- lisa/analysis/frequency.py
- lisa/datautils.py
@Leo-Yan I made a few changes to plot_peripheral_frequency/df_peripheral_clock_effective_rate, let me know if everything still works for you.
Wrt to the trace for the documentation plot, it seems that `juno:uartclk` does not have any event for `clk_set_rate`, so I switched to `aplclk` to get a more interesting plot.
The plot can be quickly viewed (with that PR) using:
```
lisa-plot doc/traces/trace_peripheral_clk.dat --plot frequency:peripheral-frequency interactive -X clk_name aplclk
```
> Fix plot_peripheral_frequency

- lisa/tests/base.py
- lisa/trace.py
FIX
Detect tracefs location automatically.
relies on devlib PR: https://github.com/ARM-software/devlib/pull/590
~~LISA branch that comes with the devlib change as well for testing: 
remote: `https://github.com/douglas-raillard-arm/lisa.git`
branch: `detect_tracefs`~~
The devlib PR is merged and subtree in lisa repo updated, so this PR can be used directly
> lisa.trace: De-hardcode tracefs location

- lisa/_assets/kmodules/sched_tp/Makefile
Use --show_only_data_members to avoid having useless anonymous type
declaration in the middle of e.g. a struct.
Consider the following type:
struct foo {
struct { int a; } bar;
};
GCC emits DWARF info looking this way:
DW_TAG_structure_type
DW_AT_name "foo"
DW_TAG_member
DW_AT_name "bar"
DW_AT_type "struct "
DW_AT_data_member_location <0x42 - curr_loc>
NULL
0x42:
DW_TAG_structure_type
DW_TAG_member
DW_AT_name "a"
DW_AT_type "int "
DW_AT_data_member_location ...
NULL
Clang emits:
DW_TAG_structure_type
DW_AT_name "foo"
DW_TAG_member
DW_AT_name "bar"
DW_AT_type "struct "
DW_AT_data_member_location 0x0
DW_TAG_structure_type
DW_TAG_member
DW_AT_name "a"
DW_AT_type "int "
DW_AT_data_member_location ...
NULL
NULL
When pahole sees clang's output, it will emit something like that:
struct foo { …
> lisa/_assets/kmodules/sched_tp/Makefile: Improve pahole output

- lisa/_kmod.py
FIX
The log entry claimed the user did not set CROSS_COMPILE
unconditionally. Rephrase to avoid that, since CROSS_COMPILE is read and
chewed by LISA anyway.
> lisa._kmod: Fix misleading log

- lisa/trace.py
FIX
Parse the "pid" field as a int32 instead of uint32, as -1 is used when
the described entity is not a task.
> lisa.trace: Fix parsing of sched_pelt_se/sched_util_est_se

- lisa/utils.py
- tests/test_wlgen_rtapp.py
FIX
Logging directly or indirectly inside a destructor (__del__) is
problematic as they are invoked when the world is breaking down around
them, which can trigger some harmless exceptions. For this reason,
get_logger() was returning a dummy logger if __del__ was found in the
stack.
inspect.stack() is unfortunately really slow (150ms to get a stack frame
of depth 25), which is enough to really slowdown the import of some
modules and runtime code as well.
Fix that by returning a wrapped logger object that will only inpsect the
stack if an exception is raised.
> lisa.utils: Speedup Loggable.get_logger()

- tools/batch-rebase
FIX
Fix tag action that were resulting in an exception: KeyError: 'tip'
> tools/batch-rebase: Fix tag action

- lisa/_kmod.py
FIX
Turn make variables into strings early in the processing to avoid any
issues if they come from Python or YAML as other types.
> lisa._kmod: Handle non-str make variables

- doc/man1/lisa.1
- shell/lisa_shell
FEATURE
Setting LISA_UPGRADE_VENV=1 env var will make lisa-install upgrade any
existing venv that would have been setup with LISA_USE_VENV=1 and
LISA_VENV_PATH=... instead of destroying it and creating it afresh.
> shell/lisa_shell: Allow lisa-install to upgrade venv

- lisa/_kmod.py
- lisa/trace.py
FEATURE
Mention that FtraceCollector will attempt to build the kernel module if
some events are missing and that it will require proper configuration to
succeed.
> lisa.trace: Improve FtraceCollector docstring

- lisa/tests/scheduler/load_tracking.py
FIX
RqInvariance tests predict rq signals by looking at the test task signal
only. This means it's susceptible to interferences if another task in
the system wakes up.
Add the noisy task check to ensure the trace is free of unwanted
activations.
> lisa.tests.scheduler.load_tracking: Add missing noise check

- lisa/tests/scheduler/load_tracking.py
FIX
Decorate the inner test methods using the noise check rather than the
user-facing one. This fixes the issue of decorating a method of a
subclass of InvarianceBase instead of InvarianceItemBase.
> lisa.tests.scheduler.load_tracking: Fix noise check usage`o

- lisa/wa.py
Some workloads in workload-automation (e.g. jankbench) include a field
in their results called 'classifiers'. It may contain the number of
repetitions, the name of the subtest being ran or other information.
Currently, Lisa completely ignores this field leading to situations such
as jankbench results not including the name of the test as it
uses 'metric' for the data type (e.g. mean, std_dev etc.) and
classifiers['test_name'] to keep the actual subtest name.
This patch includes classifiers expanded to separate columns in the df
containing WAOutput results when they are present. When classifiers are
not present or are empty, e.g. with pcmark, speedometer etc.,
the resulting df will not be affected by the change.
> lisa.wa: Include classifiers in WAResultsCollector

- lisa/_assets/kmodules/sched_tp/Makefile
- lisa/_assets/kmodules/sched_tp/main.c
FIX
Some kernels require importing namespaces before using a symbol. An
example is some Android kernels that will refuse to load the module:
[ 3357.743660] lisa: module uses symbol (filp_open) from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
[ 3357.756891] lisa: Unknown symbol filp_open (err -22)
[ 3357.761935] lisa: module uses symbol (kernel_write) from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
[ 3357.775399] lisa: Unknown symbol kernel_write (err -22)
[ 3357.780702] lisa: module uses symbol (kernel_read) from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
[ 3357.794067] lisa: Unknown symbol kernel_read (err -22)
Fix the issue by adding an …
> lisa._assets.kmodules.sched_tp: Add MODULE_IMPORT_NS()

- lisa/_assets/kmodules/sched_tp/Makefile
FIX
Avoid using xargs -P as this leads to mixing the stdout of multiple
commands, resulting in corrupted output.
> lisa._assets.kmodules.sched_tp: Fix symbol namespace extraction

- lisa/conf.py
FIX
Exceptions pickling is broken when they are passed keyword arguments, so
pass positional only.
This matters for that exception as it can be raised in a subprocess when
compiling the kernel module.
> lisa.conf: Avoid kwargs in exceptions

- lisa/tests/staging/utilclamp.py
By design, migration margin shouldn't be considered when comparing uclamp with capacities as explained in this series:
https://lore.kernel.org/lkml/20220804143609.515789-1-qais.yousef@arm.com/
It is considered a bug - that the above series fixes it.
Integration branch was failing with this series applied because of this margin.
Fix the test to ignore the margin to reflect the actual uclamp design.
Older kernels without the series might fail now, which is the correct result.
The series should trickle to stable kernels once merged in mainline Linux. The failure should signal to any user that they need to backport this series.
> utilclamp.py: Don't consider migration margin in test_placement

- lisa/analysis/notebook.py
- lisa/datautils.py
- lisa/utils.py
FIX
iteritems() has been deprecated in favor of items()
> lisa.analysis.notebook: Avoid using DataFrame.iteritems()

- lisa/tests/scheduler/eas_behaviour.py
commit 487e1ac46ea6 ("lisa.tests.scheduler.eas_behaviour: Add big-task-duty-cycle platform parameter")
modified the prototype of _get_rtapp_profile(), but an implementation was left with the initial prototype, triggering errors. Fix that.
Notes:
- Another mistake was made in the initial commit: the platform where this can be seen is not a rb5, but a db845c.
- The value for big-task-duty-cycle for the db84c should be set to 50.
- It seems that on a rb5, get_big_duty_cycle() normally selects a duty cycle of ~73%. The capacity of the medium CPU is ~870. This means that a big task cannot fit in a medium CPU. Maybe a custom value should be set for this platform aswell.
> lisa.tests.scheduler.eas_behaviour: Fix _get_rtapp_profile() prototype

- lisa/trace.py
FIX
Update HRTxtTraceParser skeleton regex to allow for a (---) TGID field, which is part of recent systrace files.
> lisa.trace: Update HRTxtTraceParser skeleton regex

- lisa/_kmod.py
FEATURE
Pass path to module and kernel path instead of relying on Kbuild's $(src) and $(srctree) variables, as they seem to be broken on some android's kernel.
> lisa._kmod: Explicitly pass module/kernel path when building module

- lisa/trace.py
A Systrace generated by the Perfetto's `traceconv` tool has records with this format:
```
<idle>-0     (-----) [000] .... 608397.919018: sched_wakeup: comm=traced pid=403293 prio=120 target_cpu=000
```
which timestamp gets parsed as `7.919018`, i.e. by ignoring all the digits but one before the second.
Fix the timestamp regexp by ensuring that, after the `__cpu` filed has been
parsed, we skip all and only the non digit chars following it.
> lisa.trace: Fix HRTxtTraceParser regex for timestamp parsing

- lisa/_kmod.py
FIX
Older kernels do not have this folder and also do not suffer from the broken sha1 in the /sys/kheaders.tar.xz headers, so ignore them.
> lisa._kmod: Ignore non-existing include/linux/atomic

- doc/man1/bisector.1
- doc/man1/exekall.1
- doc/man1/lisa.1
- lisa/utils.py
- tools/lisa-build-asset
Since Python 3.7, nullcontext is provided by contextlib directly so there is no need to pull that from lisa.
> tools/lisa-build-asset: Remove lisa.utils import

- lisa/analysis/latency.py
Latency-related functions such as df_latency_wakeup and df_latency_preemption at the moment do not return any information about which CPUs the latency ocurred on.
Add a 'cpu' column to df_latency_preemption along with 'cpu' & 'target_cpu' columns to df_latency_wakeup.
> lisa.analysis.latency: Include CPUs in latency DFs

- .github/workflows/test.yml
- pytest.ini
Github actions jobs have been plagued recently by failure to install packages using apt due to flaky mirrors. Make apt retry a number of times before giving up.
> .github: Make apt retry downloads

- install_base.sh
FIX
firefox-geckodriver does not exist as of Ubuntu 22.04 as it now is part of the firefox snap package.
> install_base.sh: Do not install selenium geckodriver on recent Ubuntu

- lisa/target.py
FIX
The devlib/max-async key was wrongly registerd as a list of int instead of an optional int.
> lisa.target: Fix TargetConf max-async key type

- lisa/_assets/kmodules/sched_tp/Makefile
Remove the use of --expanded_prefix so that we can use a pahole version closer to mainstream (we still require --expand_types_once, but it should be easier to finish upstreaming).
Replace the effect of that option by a sed regex to rename all types, then rename back the types we did not want to rename in the first place (the ones listed in private_types.txt)
> lisa._assets.kmodules.sched_tp: Avoid using pahole --expanded_prefix

- .gitignore
FIX
Update gitignore to exclude git cache that can be generated inside the directory and slow down git commands inside the lisa directory.
Also exclude some of the artifacts that can be generated by building the Lisa kernel module.
> .gitignore: Add cache/ and kernel module artifacts

- lisa/wlgen/sysbench.py
- lisa/wlgen/workload.py
FIX
Document "target" parameter and the variable keyword arguments that are forwarded to the base class.
> lisa.wlgen.sysbench: Fix docstring

- lisa/target.py
FIX
Pass max_async to devlib's Target.connect() method which is where it is actually used, rather than just to the constructor.
> lisa.target: Pass max_async to devlib Target

- .readthedocs.yml
- doc/doc_requirements.txt
- setup.py
FIX
readthedocs uses an old version of sphinx for projects created before 2020:
https://github.com/mgeier/sphinx-last-updated-by-git/issues/1
So force a newer version.
> setup.py: Force Sphinx > 2 for readthedocs

- doc/contributors_guide.rst
* Add details on expectations of docstrings.
* State pylint expectations (or lack of).
* Cleanup the self test section.
* Add section on how to update binary tools.
> doc: Improve contributors guide

- lisa/utils.py
- lisa/wa.py
This PR allows acessing a list of jobs in the WAOutput through
wa_output.jobs along with a LazyMapping of raw Trace objects in WATraceCollector
through wa_output['trace'].traces.
Additionally, add deprecation warnings for creating WAOutputs containing multiple different WA runs. This is meant to determine whether any of the existing workflows or use cases rely on the feature with the ultimate goal of removing it and achieving the same functionality in a cleaner, less error-prone way.
> Expose jobs in WAOutput & traces in WATraceCollector

- lisa/trace.py
FIX
Using named ring buffer in ftrace makes trace-cmd report display the name of the buffer at the beginning of each event. Adjust the parsing regex to ignore it.
> lisa.trace: Fix TxtEventParser regex for named ring buffer

- lisa/_kmod.py
FIX
Module building fails with modpost error due to undefined symbols unless KBUILD_MODPOST_WARN=1 is enabled, which turns the errors into warnings. This is because modpost cannot know the list of symbols if Module.symvers is missing, which is the case since we don't have a built Image to work with.
> lisa._kmod: Enable KBUILD_MODPOST_WARN=1

- lisa/_kmod.py
Mismatching split BTF loading issue:
https://lore.kernel.org/all/YfK18x%2FXrYL4Vw8o@syu-laptop/t/#md877c45455918f8c661dc324719b91a9906dc7a3 https://bugzilla.opensuse.org/show_bug.cgi?id=1194501
has been fixed in:
https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=5e214f2e43e4
When that config is enabled: MODULE_ALLOW_BTF_MISMATCH=y
Unfortunately, that is not the default so keep LISA's current behavior.
> lisa._kmod: Add info on split BTF issue

- lisa/tests/staging/utilclamp.py
DataFrame.pivot(index=None) seems to have changed behavior: https://github.com/pandas-dev/pandas/issues/52436
Remove index=None so that it works across pandas versions.
> lisa.tests.starting.utilclamp: Fix for pandas 2.0.0

- setup.py
Avoid breakage of published package at the next major pandas release, since pandas more or less follows semantic versionning.
> setup.py: Add <3.0 pandas version bound

- lisa/wa.py
FIX
The 'self' in WACollectorBase refers to the WACollectorBase and not the parent WAOutput, currently causing get_collector to crash because it can't find the _jobs property.
This looks like an omission from the recent wa.py changes so this commit just fixes the property being accessed.
> lisa.wa: Fix getting jobs in WACollectorBase

- lisa/_assets/kmodules/sched_tp/ftrace_events.h
- lisa/_assets/kmodules/sched_tp/parsec.h
- lisa/_assets/kmodules/sched_tp/pixel6.c
- lisa/analysis/pixel6.py
This PR adds support for the Pixel 6 emeter GPU channel in Lisa. It involves expanding the lisa sched_tp module to support passing private data down the parser chain. This functionality is then used to distinguish between the two different power meter devices when outputting trace events. Then, the pixel6_emeter parser logic is extended to parse both the power meter files (`device0` and `device1`), covering all the channels in the process. Finally, a `GPU` power channel is included in Lisa's pixel6 analysis to make use of the newly added functionality in trace analysis.
> Add support for the Pixel 6 emeter GPU channel

- doc/conf.py
Apply Workaround for broken flyout menu.
Bug report: https://github.com/readthedocs/readthedocs.org/issues/10242
Workaround: https://github.com/readthedocs/sphinx_rtd_theme/issues/1452#issuecomment-1490504991
> doc: Workaround broken flyout menu

- lisa/trace.py
- tests/test_trace.py
FIX
Trace.get_task_pid_names() returns the list of task names in chronological order. We currently use the __comm and __pid columns of some events as part of the data source. However, the __comm column is the result of the lookup of __pid in a table stored in trace.dat, that contains the latest comm known for a task. That effectively brings information from the future and breaks the chronological order.
Instead, ignore those columns and focus on actual event fields.
> lisa.trace: Fix task comm extraction

- .github/workflows/preview.yml
- tools/lisa-make-preview
FIX
Ensure the remote name is unique to each branch by using the head commit's sha1.
> tools/lisa-make-preview: Use branch sha1 for remote name

- .github/workflows/mirror.yml
- .github/workflows/preview.yml
Serialize jobs so that we don't have any ordering issues when updating branches.
> .github/workflows: Use concurrency group

- .github/workflows/test.yml
- lisa/trace.py
FIX
Fix event validation when using FtraceCollector with some events that ftrace does not allow to configure.
> lisa.trace: Fix FtraceCollector(events=['print'])

- tools/bisector/bisector/bisector.py
FIX
Recent versions of ruamel.yaml changed DEFAULT_MAPPING_TAG from a string to a new non-hashable object. Ensure we use the tag name to avoid any exception.
> tools/bisector: Fix ruamel usage of DEFAULT_MAPPING_TAG

- tools/lisa-make-preview
FIX
If there is no preview PR, the preview branch should be pointed at the base branch.
> tools/lisa-make-preview: Fix case where there is no preview PR

- .github/workflows/autobranch.yml
Now that we have transitioned from "master" to "main" branch, add a "master" autobranch that will track "main" with extra warnings in the doc, the code and the shell scripts.
> .github/workflows/autobranch.yml: Add "master" autobranch

- lisa/trace.py
FIX
Avoid undefined variable error when getting the cpus-count on trace-cmd parser.
> lisa.trace: Fix cpus-count metadata on trace-cmd parser

- lisa/_assets/kmodules/lisa/Makefile
FIX
The VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver namespace is necessary to have access to kernel_read() on some Android kernels. That function is required to be able to read the energy measurements exposed in sysfs by Pixel 6 builtin energy meter driver.
> lisa/_assets/kmodules/lisa: Add symbol namespace for kernel_read()

- lisa/_assets/kmodules/lisa/Makefile
- lisa/_kmod.py
FIX
Add a way for the LISA module to be compiled with some module-specific make variables.
Also ensure Makefile contains proper quoting.
> lisa._assets.kmodules.lisa: Allow module-specific make variables

- lisa/_kmod.py
FIX
When the user asks for e.g. clang-14, we need to map that to the "clang14" package in Alpine linux. Otherwise, we will simply end up with the "clang" package, which might be e.g. clang-16
> lisa._kmod: Fix Alpine clang package name

- .readthedocs.yml
- doc/conf.py
- lisa/notebook.py
- lisa/stats.py
- lisa/utils.py
- lisa/wa.py
- tools/lisa-doc-build
FIX
Sphinx nitpicky mode is required to detect broken references, so re-enable it and fix the currently broken refs and warnings.
> doc: re-enable Sphinx nitpicky mode

- tools/lisa-build-asset
FIX
--build-dir folder was emptied before being used. In case of previous build failure, we might still have bind mounts that we absolutely not want to remove recursively as it might empty e.g. LISA_HOME
> tools/lisa-build-asset: Avoid emptying --build-dir

- lisa/_cli_tools/lisa_load_kmod.py
Avoid logging the dmesg output twice now that lisa._kmod does it already.
> lisa._cli_tools.lisa_load_kmod: Avoid double dmesg logging

- lisa/utils.py
Fix indentation in docstring to avoid accidentally creating a definition list item.
> lisa.utils: Fix Serializable docstring indentation

- lisa/wa.py
FIX
WATraceCollector.traces property creates all Trace instances with the same path, which is the path of the trace of the last job.
Fix that by ensuring each Trace is created from the trace path associated with its job.
> lisa.wa: Fix WATraceCollector.traces

- setup.py
- shell/lisa_shell
Use pip-audit to scan for known vulnerability in lisa-install, and attempt to upgrade packages if LISA_USE_VENV=1, which gives ownership of the venv to lisa-install.
> lisa: Use pip-audit in lisa-install

- .github/workflows/autobranch.yml
Ensure that the failure to update one autobranch does not prevent the other branches from being built.
> .github/workflows/autobranch.yml: Ensure all autobranches are built

- doc/conf.py
Allow disabling the plot generation in the documentation to save time. This env var is considered unstable and as such is not documented.
> doc/conf.py: Add undocumented env var to disable plots in doc

- lisa/utils.py
FEATURE
lisa's cache folder is found based on LISA_HOME and then XDG_CACHE_HOME as a fallback.
Add an extra level where LISA_CACHE_HOME will be checked first, allowing the user to override the folder used for cache.
> lisa.utils: Read LISA_CACHE_HOME env var

- setup.py
Ensure that the platform used is Linux, as we do not support other platforms.
> setup.py: Check that we are running on Linux

- lisa/_kmod.py
- lisa/target.py
FIX
Pass approriate parameters to devlib to connect to an adb server over IP instead of trying to build a device string ourselves (which probably worked in the past but not in recent adb versions).
> lisa.target: Fix adb-over-ip connection

- lisa/_kmod.py
FEATURE
If rmmod failed, try -f. This is currently necessary as failure to initialize some features will make the module init return a non-zero exit code. This unfortunately requires an rmmod -f to unload.
> lisa._kmod: Use rmmod -f if rmmod failed

- doc/setup.rst
- lisa/_assets/kmodules/lisa/Makefile
- lisa/_assets/kmodules/lisa/main.c
- lisa/_assets/kmodules/lisa/pixel6.c
- lisa/_assets/kmodules/lisa/sched_helpers.h
- lisa/_assets/kmodules/lisa/tp.c
- lisa/_kmod.py
- tools/kmodules/lisa-in-tree/android/0002-arm-vh-Include-Lisa-module-in-the-vendor-modules.patch
- tools/kmodules/lisa-in-tree/android/abi/0001-abi-Allow-GKI-restricted-symbols.patch
- tools/kmodules/lisa-in-tree/fetch_lisa_module.py
- tools/kmodules/lisa-in-tree/linux/0001-arm-vh-Include-Lisa-module-stub.patch
FEATURE
Modify the Makefile for the lisa module to distinguish between in-tree and out-of-tree building. Adjust the imports and definitions in the source files accordingly.
With this change, the module can now be copy-pasted into a kernel tree and built with kbuild like any other kernel module. The default, out-of-tree build method with Lisa should work unchanged as before.
> lisa/_assets/kmodules/lisa: Support in-tree builds

- doc/setup.rst
- tools/kmodules/lisa-in-tree/fetch_lisa_module.py
- tools/kmodules/lisa-in-tree/linux/0001-arm-vh-Include-Lisa-module-stub.patch
1. Add a usage example to the section in doc/setup.rst
Because we removed the default value for --module-kernel-path, it may not be clear to the user what the argument should actually look like. Add a usage example in the documentation to account for that.
2. Change the default remote from ssh to https
Defaulting to accessing the GitHub repo over ssh is prone to failing if ssh is not set up on the machine. Https does not have that issue and so is probably a more reasonable default.
3. Fix an omission in the kernel stub patch
The kernel stub patch still had `lisa-module-git` in the gitignore where it should be `lisa-git`.
> tools/kmodules/lisa-in-tree: Adjust defaults and documentation

- doc/setup.rst
The current order runs a git fetch prior to moving into the repository directory. Fix this by changing the order of commands.
> [docs/setup] Fix order of commands when installing LISA from github

- install_base.sh
FEATURE
Add kernel build dependencies (and to --install-all) so that LISA kernel module build can succeed.
> install_base.sh: Add --install-kernel-build-dependencies

- doc/setup.rst
Since having build dependencies missing can lead to non-obvious issues, add the requirement to the documentation.
> doc/setup.rst: Add a note on kernel module build prerequisite.

- lisa/_assets/kmodules/lisa/Makefile
```The $(src) variable contains either the path to the module on its own in out-of-tree builds or the path relative to $(srctree) in in-tree builds. Fix the definition of MODULE_SRC to account for that discrepancy.```
> lisa/_assets/kmodules/lisa: Fix MODULE_SRC definition

- lisa/_assets/kmodules/lisa/pixel6.c
- lisa/_assets/kmodules/lisa/sched_helpers.h
Fold including internal kernel headers required for the in-tree build into sched_helpers.h. This way including sched_helpers.h will work on its own in both workflows instead of requiring duplicated defines wherever it is used.
> lisa/_assets/kmodules/lisa: Include in-tree headers in sched_helpers.h

- install_base.sh
FIX
On some distributions /usr/lib/jvm will only contain symlinks that points outside that directory, therefore we must make sure to follow the symlinks.
> install_base.sh: follow symlink when trying determining JAVA_HOME

- lisa/_assets/kmodules/lisa/Makefile
- lisa/_assets/kmodules/lisa/main.c
- lisa/_assets/kmodules/lisa/sched_helpers.h
- lisa/_kmod.py
- tools/recipes/busybox.recipe
FIX
Refactor DynamicKmod.install() to abstract over how the kernel module makes its way to the target and fix loading of an existing lisa.ko module.
Also fix module checksum so that Python compuation matches what the Makefile computes.
> lisa._kmod: Fix pre-existing .ko loading

- .github/workflows/test.yml
The packaging situation of firefox-geckodriver on Ubuntu 20.04 is a mess and leads to broken packages:
The following packages have unmet dependencies:
firefox-geckodriver : Depends: firefox (= 116.0.2+build1-0ubuntu0.20.04.1) but 116.0.3+build1-0ubuntu0.20.04.1~mt1 is to be installed
E: Unable to correct problems, you have held broken packages.
Therefore, use Ubuntu 22.04 where the firefox package includes the selenium driver so no more version mismatch.
> .github/workflows/test.yml: Use Ubuntu 22.04

- .github/workflows/autobranch.yml
- .github/workflows/test.yml
It is useful to run the tests when the main branch is updated, but not in other circumstances.
> .github/workflows/test.yml: Do not run tests on push events beyond main

- tools/lisa-combine-pr
FIX
Avoid stdout/stderr ordering issues by using logging modules.
> tools/lisa-combine-pr: Use logging module

- lisa/_kmod.py
- lisa/conf.py
- lisa/target.py
- lisa/utils.py
- tools/lisa-whatsnew
Example conf:
```
target-conf:
kernel:
modules:
modules:
lisa:
overlays:
main.c: !call:lisa._kmod.PatchOverlay
overlay: !call:lisa._kmod.FileOverlay.from_content
content: "diff --git a/lisa/_assets/kmodules/lisa/main.c b/lisa/_assets/kmodules/lisa/main.c\nindex a3d1b3942..67192ecda 100644\n--- a/lisa/_assets/kmodules/lisa/main.c\n+++ b/lisa/_assets/kmodules/lisa/main.c\n@@ -26,6 +26,7 @@ static void modexit(void) {\n static int __init modinit(void) {\n \tint ret;\n \n+\tpr_info(\"HELLO WORLD!\");\n \tpr_info(\"Loading Lisa module version %s\\n\", LISA_MODULE_VERSION);\n \tif (strcmp(version, LISA_MODULE_VERSION)) {\n \t\tpr_err(\"Lisa module version check failed. Got %s, expected %s\\n\", version, LISA_MODULE_VERSION);\n"
```
Note the 2 levels of "modules:", this is not a typo
> Allow patching the module

- lisa/_assets/kmodules/lisa/Makefile
FIX
Do not change current directory as it changes the effective location of $@ when it is a relative path. Instead, use cd in a subshell.
> lisa._assets.kmodules.lisa: Fix sha1sum invocation

- lisa/_assets/kmodules/lisa/Makefile
- lisa/_assets/kmodules/lisa/ftrace_events.h
- lisa/_assets/kmodules/lisa/introspect_header.py
- lisa/_assets/kmodules/lisa/kernel_features.json
- lisa/_kmod.py
FIX
Remove capacity from events if arch_freq_scale symbol is not exported by the kernel.
> lisa._assets.kmodules.lisa: Shield against missing arch_freq_scale

- lisa/_kmod.py
- lisa/target.py
FEATURE
If the kernel seem to have been compiled with a given toolchain according to /proc/version, try that toolchain first.
> lisa._kmod: Give priority to toolchain that was used for the kernel

- lisa/_kmod.py
FIX
The kernel can need perl to build modules, so ensure it's part of the dependencies.
> lisa._kmod: Add missing "perl" chroot kernel build dependency

- lisa/conf.py
FIX
Forward the "memo" parameter to nested copy.deepcopy()
> lisa.conf: Forward memo in __deepcopy__

- lisa/_assets/kmodules/lisa/ftrace_events.h
- lisa/_assets/kmodules/lisa/kernel_features.json
- lisa/_assets/kmodules/lisa/sched_helpers.h
FIX
Ensure the current CPU capacity computation can be reliably compiled, with only a direct dependency on introspectable symbols instead of some API that could break at any time and is not introspectable.
> lisa._assets.kmodules.lisa: Harden current CPU capacity computation

- doc/setup.rst
FEATURE
Manual and in-tree builds for the LISA modules are not supported and will not work as it stands. Therefore, remove the associated documentation.
> doc/setup.rst: Remove manual and in-tree module build doc

- lisa/wlgen/rta.py
FIX
Fix invocation of plat_info.get_key() to pass a key name and not a string.
Fixes https://github.com/ARM-software/lisa/issues/2114
> lisa.wlgen.rta: Fix PeriodicWload.unscaled_duty_cycle_pct()

- lisa/target.py
FIX
It has been reported that rs.media.module process is necessary for the
mount command to work on Android, so add it to the list of critical
tasks to not freeze.
> lisa.target: Allow mount to work on Android

- tools/exekall/exekall/_utils.py
FIX
Ensure that a str is provided where an str is expected instead of a pathlib.Path.
> tools/exekall: Fix use of Path as str

- lisa/tests/staging/utilclamp.py
FIX
Fix UtilClamp._plot_phases() error location red lines to be vertical and increase the width of the signal plot to be responsive.
> lisa.tests.staging.utilclamp: Fix debug plot

- shell/lisa_shell
FIX
Install location for git hooks is relative to $LISA_HOME, so prepend "$LISA_HOME" to the path.
> shell: Fix git hook install location

- lisa/_cli_tools/lisa_load_kmod.py
- lisa/_kmod.py
- lisa/trace.py
- lisa/wa/plugins/_kmod.py
FEATURE
Since this kernel module is meant to host more than just ftrace events, rename it to a more general name.
> lisa._kmod: Rename LISAFtraceDynamicKmod to LISADynamicKmod

- lisa/_kmod.py
FIX
__pycache__ is sometimes created around Python sources which later can affect the checksum of the module.
Ensure that the __pycache__ folders and all their contents are ignored when gathering module sources.
> lisa._kmod: Do not include __pycache__ in kmodule sources

- lisa/_kmod.py
FIX
Caching of the compilation artifact was keyed on the compiler name so far. This breaks if the user manipulates PATH and swaps different binaries under the same name, e.g. multiple versions of clang all called "clang".
Fix that by calling "cc --version" and caching based on the result. This ensures we will not reuse artifacts created with a different toolchain.
> lisa._kmod: Cache compilation on cc --version

- lisa/_assets/kmodules/lisa/tp.h
- lisa/_assets/kmodules/lisa/utils.h
- lisa/_kmod.py
Misc kernel module build fixes
>   Misc kernel module build fixes

- lisa/_assets/kmodules/lisa/introspection.json
- lisa/_assets/kmodules/lisa/sched_helpers.h
The kernel commit 7bc263840bc3 ("sched/topology: Consolidate and clean up access to a CPU's max compute") removed rq->cpu_capacity_orig so we can't use it anymore to retrieve the original CPU capacity nor for setting the FREQ_INVARIANCE kernel feature in LISA.
Replace rq->cpu_capacity_orig with arch_scale_cpu_capacity(cpu) in Lisa trace module's rq_cpu_orig_capacity() and remove the HAS_MEMBER(struct, rq, cpu_capacity_orig) check from the FREQ_INVARIANCE test.
Since arch_scale_cpu_capacity(cpu) exists in the kernel for a long time we don't have to take care of activating this only for newer Linux kernel versions.
> lisa._assets.kmodules.lisa: Don't rely on rq->cpu_capacity_orig anymore

- lisa/trace.py
It looks like the appearance of userspace generated ftrace events has changed. What appears to be memory address has been added to the event meta data breaking the prefiltering of trace data in _select_userspace().
The event used contain the keyword 'tracing_mark_write:', but now has the format: 'tracing_mark_write.<address>:'.
Example:
rt-app-21908 [001] 4470442.464974: print:
tracing_mark_write.10e87ffbd993ed977ebcbff93a794b6d: rtapp_main: event=end
Fix the event filtering to handle new format without breaking backwards compatibility.
> lisa/trace: Fix dataframe prefiltering for userspace ftrace events

- tools/recipes/trace-cmd.recipe
FIX
Avoid using install_libs which attempts to build a shared object, when we only want a static binary.
> tools/recipes/trace-cmd.recipe: Avoid building shared object

- tools/lisa-build-asset
FIX
Use lazy umount of chroot folders to avoid failing if a process is still accessing it. There seems to be some processes alive for a short duration after we finished building that otherwise intermittently make cleanup fail.
> tools/lisa-build-asset: Use lazy umount

- lisa/trace.py
FIX
Specify that meta event field names must be unique.
> lisa.trace: Update Trace.df_event() docstring

- lisa/trace.py
FEATURE
Do not show the full set of available events as it typically is very large and makes the output hard to read. Instead, only show the closest matches for the events that are missing.
> lisa.trace: Only show closest matches in MissingTraceEventError

- lisa/analysis/idle.py
- lisa/analysis/tasks.py
- lisa/datautils.py
- lisa/pelt.py
- lisa/stats.py
FIX
Avoid a FutureWarning related to inplace operation on view objects that will not work anymore in pandas 3.0
> lisa: Address some pandas FutureWarning

- lisa/analysis/pixel6.py
- lisa/datautils.py
FIX
Pandas 2.2.0 GroupBy.apply() no longer includes the group column by default. It must be explicitly selected.
> Fix a couple of GroupBy.apply() deprecations

- lisa/_assets/kmodules/lisa/ftrace_events.h
- lisa/_assets/kmodules/lisa/introspection.json
- lisa/_assets/kmodules/lisa/tp.c
FEATURE
Upstream has now removed struct util_est and effectively merged util_est.enqueued and util_est.ewma in a single int field. Provide a new trace event for it so the new kernel can trace it.
This also fixes LISA not being able to compile and load the module on the new kernel. We detect whether struct util_est exists to decide if the new signal should be used.
> lisa._kmod: Add util_est_unified trace events
