ARM-software/lisa

libs/utils/energy.py, tests/eas/rfc.py
OK, I got rid of patch 'libs/utils/energy.py: Remove unnecessary replace in HWMon::sample()'
=> Fixes em cpu freq

tests/eas/rfc.py
An initial test for sched tune, more to come.
=> Initial stune test

libs/utils/energy.py
This patch integrates the initial version of the ARM Energy Probe AEP
Energy Meter class.
The AEP delivers sample voltage, power and current values (10Khz). The
AEP Energy Meter uses only the power sample values and calculates the
energy value by multiplying the average power value with the time
difference value between the call of the reset() and the report()
method.
Current limitations:
- The AEP Energy Meter class is tailored to measure DIE energy on the
Hikey board for now.
- It implements only the reset() and report()(sample()) method (e.g.
used by the eas rfc test: tests/eas/rfc.py).
- It uses only AEP channel 1 (hardcoded).
- It uses a hardcoded value for shunt resistor (33 mOhm).
- It uses 'LITTLE' channel tag to let the existing tooling work with
the Hikey board even though we …
=> libs/utils/energy.py: Initial integration of AEP Energy Meter:

libs/utils/env.py, tests/eas/rfc.py
This series should fix both #30 and #10
=> Fixups support for testing multiple kernels

libs/utils/env.py, libs/utils/trace.py, libs/utils/trace_analysis.py, tests/eas/rfc.py
A couple of feature patches which adds capacity thresholds representation as well as tracking of kernel configuration and build version.
=> Few features additions

libs/utils/trace.py, libs/utils/trace_analysis.py
This series adds an initial support to parse the sched_overutilized event which is used to report EAS entering/exiting from overutilized mode.
The sched_overutilzied event is used to build "ESA-mode" intervals which are conveniently overdrawn to some plots thus marking when events are happening in EAS or non-EAS mode.
=> Add support to sched_overutilized plotting

libs/utils/executor.py, libs/wlgen/wlgen/rta.py
A couple of fixes to executor.py.
@deggeman 9c284b4 should address #60 in a more generic way. Could you give it a try?
@derkling 4e98ca3 is a fixup for your rtapp refactoring.
=> Executor fixes

tests/stune/smoke_test_ramp.py
Update to trappy v5.2.0 and use it's improvements to simplify the schedtune boost margin test.
=> Schedtune boost margin improvements

LisaShell.txt
The lisa-shell has a lisa-test command.  It's in its early stages but
it's useful in its current form so start advertising it.
=> shell: advertise lisa-test

src/shell/lisa_shell
lisa-update fails to update submodules when they change their remote:
---8<---
$ git clone git@github.com:ARM-software/lisa.git
Cloning into 'lisa'...
remote: Counting objects: 2058, done.
remote: Total 2058 (delta 0), reused 0 (delta 0), pack-reused 2058
Receiving objects: 100% (2058/2058), 16.44 MiB | 3.61 MiB/s, done.
Resolving deltas: 100% (1266/1266), done.
Checking connectivity... done.
$ cd lisa
$ source init_env
[...]
[LISAShell lisa] \> ls libs/devlib
[LISAShell lisa] \> lisa-update
*** Update LISA installation
Developer mode ENABLED, updating local libraries...
Submodule 'libs/bart' (https://github.com/ARM-Software/bart.git) registered for path 'libs/bart'
Submodule 'libs/devlib' (https://github.com/derkling/devlib.git) registered for path 'libs/devlib'
Submodule 'libs/trappy' …
=> lisa_shell: use git submodule sync to update the remote of the submodules

ipynb/thermal/ThermalSensorCharacterisation.ipynb
This section is intended for storing IPython Notebooks for running thermal-related experiments.
=> ipynb: add thermal section for thermal-related notebooks

ipynb/android/benchmarks/Android_PCMark.ipynb, ipynb/android/workloads/Android_Recents_Fling.ipynb, ipynb/android/workloads/Android_YouTube.ipynb
=> ipynb: add Android workloads section for Android-related notebooks

Vagrantfile
Add a simple vagrant file that sets up a VM to use with lisa.
=> Vagrantfile: initial version

ipynb/tutorial/05_TrappyUsage.ipynb, src/shell/lisa_shell
These are the (I hope) uncontroversial changes I needed to make to get started after the recent hacking session.
=> Minor improvements to the out-of-box experience

ipynb/android/benchmarks/Android_PCMark.ipynb, ipynb/android/workloads/Android_Recents_Fling.ipynb
This series:
- simplifies launching PCMark by exploiting `monkeyrunner` tool
- adds function to launch `n` apps for the Recents Flinger workload
=> Android wloads

target.config
=> target.config: add description for tools

ipynb/android/workloads/Android_Recents_Fling.ipynb
This patch adds these updates:
1. ANDROID_HOME setup
2. Simplified TestEnv configuration
3. Open apps support for Android N
4. Fling coords based on display resolution based
=> ipynb: android: update recent fling to be more generic

libs/utils/trace_analysis.py
Here are some fixes for issues related to the trace analysis plotting functions I've discovered mainly while parsing a systrace on a new Android device. Some events missing and the usage of absolutes timestamps triggered some corner cases which should now be fixed.
=> Trace analysis fixes

libs/utils/energy.py, libs/utils/env.py
This is an updated version of #110
=> Aep updates

src/shell/lisa_shell
Teach lisa-update to update itself.  As requested in #103
=> lisa-update all

libs/utils/android/system.py, libs/utils/android/workloads/jankbench.py
Initial small version of a new Android module to collect all system related tuning.
For the time being: just a toggle for AIRPLANE mode ;-)
=> Add android system utils

libs/utils/android/system.py
=> libs/utils/android: add more system utility functions

libs/utils/trace.py
Usually we work under the assumption that every CPU in a cluster runs at the
same frequency, i.e. frequency changes per-cluster and not per-CPU.
This adds a simple check to prove this assumption true.
=> Cluster frequency coherency check

Vagrantfile
This package is required by the tutorial notebooks.
=> Vagrantfile: Add 'tree' to installed packages

libs/utils/trace_analysis.py
Version 3 of frequency residency. Follows #130 and #87 
Close #130 
Close #87
=> Freq residency v3

ipynb/chromeos/ChromeOS_TestThat.ipynb
=> ipynb: add ChromeOS-related notebook section

libs/utils/android/system.py
This also updates the `start` method in such a way to split between launching an app using an action and using a component name (i.e. `start_activity` and `start_action`).
=> [Android Sys Utils] add new utility functions

tests/stune/smoke_test_ramp.py
=> tests/stune: fix boost value for smoke test

libs/wlgen/wlgen/rta.py
This is a simple series which should fix RTApp calibration on systems with Android >=N as well as add some sanity checks on calibration values computed on big/LITTLE systems.
=> Fix rtapp calibration

tests/stune/smoke_test_ramp.py
Trappy 5.7 knows how to filter traces.  We can get rid of the `.add_parsed_event()` workaround and let the grammar filter the event for us.
=> tests: simplify stune's boosted utilization signal test

libs/utils/analysis/cpus_analysis.py, libs/utils/analysis/frequency_analysis.py, libs/utils/analysis/tasks_analysis.py
This series provides a set of fixes and improvements for some of the trace analysis modules.
=> [Analysis] fixes for some of the trace analysis modules

ipynb/energy/EnergyModel_ClusterEnergy.ipynb, ipynb/energy/EnergyModel_SystemEnergy.ipynb
This series adds two notebooks that describe the energy model building flow that will be part of LISA in the near future.
These two notebooks target two reference platforms:
- one where energy can be measured at cluster level
- the other one where energy can only be measured at system level, which means either at battery level or as near as possible to the cores
=> [Energy Model] notebooks with energy model building flow

libs/utils/analysis/cpus_analysis.py
=> [TasksAnalysis] add per-CPU task context switch count

ipynb/examples/trace_analysis/TraceAnalysis_IdleStates.ipynb, libs/utils/analysis/frequency_analysis.py, libs/utils/analysis/idle_analysis.py, libs/utils/trace.py
=> [Analysis] add IDLE STATES analysis module

ipynb/releases/ReleaseNotes_v16.10.ipynb, libs/utils/android/system.py, libs/utils/android/workloads/youtube.py, libs/utils/env.py
A small series with various fixes for Android related APIs
=> Android fixups

tests/eas/acceptance.py
Some minor documentation fixes xoming from the EAS 1.1 integration guide.
=> test/eas/acceptance: documentation fixes

ipynb/scratchpad/.gitignore
This is somewhere to put your own notebooks that you don't want to
pollute the git repo with, in order to reduce the stash/checkout/unstash
dance needed.
Signed-off-by: Chris Redpath <chris.redpath@arm.com>
=> Add a scratchpad folder for your own notebooks which will be ignored

Vagrantfile
**Don't merge yet**, I haven't tested this on a clean box, will do tonight. Just putting this here in case anyone has hit the same issue.
=> Vagrant: Fix Pandas installation

src/shell/lisa_shell
- Add some examples and explanation to the usage string.
- Rename variables and pseudo-variables to clarify meaning
=> lisa_shall: Improve lisa-test documentation

libs/utils/test.py
- Require root connection on Android targets
- Add `get_sched_assert`. Currently no users for this - should we merge it anyway (since I've written it) or wait until we need it?
- Add `get_end_time` and `get_window`. Also no users yet.
=> Miscellaneous new features for LisaTest

libs/utils/env.py
Do people find this style easier to read? If you find the existing style easier then just close this PR.
=> libs/utils/env: Simplify check for rt-app requirement

libs/utils/test.py
It's a good idea to unify the creation of Traces in one place, because
passing a different sent of events will result in different time
indexes due to the time normalization being based on the time of the
first event.
This is also a nice convenience method.
=> LisaTest: Add get_trace method

libs/utils/executor.py
This is to be used for https://github.com/bjackman/lisa/blob/fie-test/tests/eas/load_tracking.py which I will submit as a separate PR once the dependencies are sorted.
I appreciate that there are some piles of documentation for the config dicts piling up here.. I will have to spend some time on it soon.
=> executor: Add freqs param to confs['cpufreq']

ipynb/examples/utils/executor_example.ipynb
Add "freeze_userspace" conf flag. Log output is not updated.
=> ipynb/examples: Update Executor example

libs/utils/analysis_register.py, libs/utils/trace.py
This PR is just `s/self._log.info/self._log.debug/` in certain places.
If anyone finds these log messages useful then feel free to just NAK this PR.
=> Hush logging for trace parsing

libs/utils/conf.py, libs/utils/env.py, libs/utils/executor.py, libs/utils/trace.py
Some docstrings I wrote on the train. I'll submit infrastructure to actually build this in the future.
I also got halfway through documenting `Executor` but it's still rather messy so I'll try to get round to submitting it properly.
=> Some Sphinx autodoc compatible docstrings

libs/utils/android/workloads/youtube.py, tests/benchmarks/android_youtube.py
Modify YouTube benchmark to make use of the new android benchmark API and provide an example of an android YouTube benchmark test.
=> Android YouTube

libs/utils/android/workloads/uibench.py, tests/benchmarks/android_uibench.py
Modify UiBench to make use of the new android benchmark API and provide an example of an android UiBench benchmark test.
=> Android UiBench

libs/utils/android/screen.py, libs/utils/android/workloads/vellamo.py, tests/benchmarks/android_vellamo.py
Add Vellamo benchmark and provide an example of an android Vellamo benchmark test.
=> Android Vellamo

libs/utils/android/workloads/geekbench.py, tests/benchmarks/android_geekbench.py
Add Geekbench benchmark and provide an example of an android Geekbench benchmark test.
=> Android Geekbench

src/shell/lisa_shell
=> lisa_shell: Check for missing submodules and update them

libs/utils/energy_model.py
- Improve a docstring
- Add an error condition
=> EnergyModel tweaks

tests/eas/capacity_capping.py
Two fixes, both issues can be summarised as: the code currently assumes that target operations (starting the workload, capping the frequency) take 0 time. 
@JaviMerino "requesting a review" from you because you wrote this originally, but DW I'm not expecting you to spend your time on this unless you really feel like it :)
=> Fixes for Capacity Capping EAS test

libs/utils/energy.py
=> libs/utils/energy: Slightly improve error for missing hwmon channel

tests/eas/preliminary.py
The default rate limits for schedutil are currently 1000 * the transition
latency reported by the cpufreq driver, so it's necessary to manually set these
tunables to a sensible value from init.rc or similar.
Add a test to highlight if this isn't being done.
=> tests/eas/preliminary: Check schedutil tunables are sensible

tests/eas/preliminary.py
EAS silently does nothing if SD_SHARE_CAP_STATES isn't set on any sched_domains.
=> tests/eas/preliminary: Add test for required sched_domain flags

libs/wlgen/wlgen/rta.py
Governor was set to "performance" for all cpus during the rtapp
calibration, but the previous governors weren't restored after
that.
=> libs/wlgen: Fix governor save/restore in rtapp calibration

.travis.yml, install_base_ubuntu.sh
=> Use IPython 5.x to avoid Python 3.3 requirement

libs/utils/analysis/frequency_analysis.py, libs/utils/analysis/tasks_analysis.py
This adds a per-CPU frequency plotter and extend the capabilities of plotTasks() to represent additional "custom" signals available in sched_load_avg_task.
=> New analysis features

libs/utils/android/screen.py, libs/utils/android/system.py, libs/utils/android/workloads/gmaps.py, libs/utils/android/workloads/jankbench.py, libs/utils/android/workloads/uibench.py, libs/utils/android/workloads/vellamo.py, libs/utils/android/workloads/youtube.py
- Add Screen on/off and unlock support
- Use it in uibench to unlock and turn on screen
=> android: add automatic display on and use in benchmarks

libs/utils/analysis/latency_analysis.py
I didn't understand this line of code, hopefully this comment will help next
time I read it.
=> latency_analysis: Add comment to clarify code

libs/utils/energy.py
Marking this as RFC until I have tested it a little more thoroughly but I have been using it and it looks good so far. Also, nice red patch.
Basically:
- Remove some code that does a load of computation we don't seem to use (I need to double check this).
- Add a `data_frame` field to `EnergyReport` that lets you see the samples directly. (CC @joelagnel)
=> AEP simplifications/enhancements

tests/eas/load_tracking.py
This event may change in format in the near future so for now let's allow
ourselves to keep adding to the block marked with a TODO. Once the event is in
mainline we can attempt to move this functionality into the Trace class,
analysis modules, or Trappy.
=> tests/eas/load_tracking: Add support for WIP sched_load_se event

libs/utils/energy.py
- Clean up some naming and use of the devlib API 
- Simplify configuring the channels (remove conf['conf'])
- Update devlib for bugfix used by subsequent commit
- Improve default channel_map so you don't need to specify it.
=> Improvements for HwMon support

ipynb/examples/energy_meter/EnergyMeter_Monsoon.ipynb, libs/utils/energy.py
=> energy: Add Monsoon Power Monitor Support

tests/eas/preliminary.py
I wrote with a version of schedutil in mind that was
hacked by the EAS project to have two separate rate limiting
tunables, up_rate_limit_us and down_rate_limit_us. I forgot that the
mainline version only has rate_limit_us.
Just check each tunable that `endswith` rate_limit_us to make this
generic across schedutil versions.
=> tests/eas/preliminary: Make TestSchedutilTunables mainline-friendly

libs/utils/android/system.py, libs/utils/android/workload.py
Small updates and additions for the Android APIs
=> Android updates

libs/utils/android/system.py
=> android: Add support to set volume

ipynb/examples/android/benchmarks/Android_Geekbench.ipynb
Adds a notebook to run Geekbench & parse the .gb4 results
=> examples/android/benchmarks: Add Geekbench parsing notebook

libs/utils/android/benchmark.py, tests/benchmarks/android_geekbench.py, tests/benchmarks/android_gmaps.py, tests/benchmarks/android_jankbench.py, tests/benchmarks/android_uibench.py, tests/benchmarks/android_vellamo.py, tests/benchmarks/android_youtube.py
Pushing some benchmark clean ups, please take a look, thanks.
=> Benchmark cleanup

ipynb/examples/android/workloads/Android_Viewer.ipynb, libs/utils/android/__init__.py, libs/utils/android/system.py, libs/utils/android/viewer.py, libs/utils/android/workload.py
This workload uses the action.VIEW intent. It will use the
most appropriate package for a given URI, e.g. Gmaps app for
a Gmaps location url. If the device doesn't have Google services,
it will open Gmaps in the browser, and so on.
=> Viewer workload

libs/utils/env.py, libs/utils/platforms/hikey960.json
Haven't created a hikey960_energy file yet since it can be read from the device. I still want to do that for post-processing things without the device at hand, but that's less important/likely.
=> Hikey960 integration

ipynb/tutorial/00_LisaInANutshell.ipynb, libs/utils/perf_analysis.py, libs/utils/platforms/odroid-xu4.json
This is a set of tiny changes:
- Change color of the perf graph to make life easier for color blind people
- Platform description for the Odroid XU4 (which I'm currently using the Cape energy probe)
- Additional information in the tutorial (how to specify interface/port for lisa-ipython; where platforms descriptions are located; how to run custom rt-app json files).
=> Tiny changes

libs/utils/platforms/cros-elm.json, libs/utils/platforms/cros-kevin.json
These are called 'cros-kevin' and 'cros-elm', respectively.
=> add kevin and elm chromebook platform files

tests/lisa/test_wlgen_rtapp.py
Wrote this test while changing the Step class. Turns out I don't need to make that change but might as well merge the test anyway.
=> Bonus RTA test coverage

ipynb/energy/EnergyModel_ClusterEnergy.ipynb, ipynb/energy/EnergyModel_SystemEnergy.ipynb
Fixes https://github.com/ARM-software/lisa/issues/476
=> ipynb/energy: Note requirement for scipy

.travis.yml, libs/utils/analysis/cpus_analysis.py, libs/utils/analysis/frequency_analysis.py, libs/utils/analysis/idle_analysis.py, libs/utils/analysis/tasks_analysis.py, libs/utils/analysis_module.py, libs/utils/trace.py, tests/lisa/test_trace.py
This should be considered an RFC, I haven't very carefully checked what else this might break. However we need to get this sorted so I'm sending a PR to highlight it.
=> Trace: allow platform=None

libs/utils/env.py
https://github.com/ARM-software/lisa/pull/490 was basically nonsense, I merged it in a rush. Revert its contents. One of the commits does sort of make sense but it's debatable, let's delay it until a need arises again.
=> Revert PR #490

libs/utils/wa_results_collector.py
This is left over from when this was temporary debug code
=> utils/wa_results_collector: Remove unnecessary check for cpu_wakeups dfg

ipynb/wltests/sched-evaluation-full.ipynb, tools/wltests/agendas/sched-evaluation-full-traced.yaml, tools/wltests/agendas/sched-evaluation-full.yaml, tools/wltests/agendas/sched-evaluation-small.yaml
Few small fixes and updates for the default wltest configuration.
=> Various WLTest fixes

tests/eas/generic.py
When running generics.py and trying to troubleshoot task_placement
failures, it can sometime be difficult to understand what was the
expected placement.
This commit adds a `plot_expected_util` method that will plot the
per-CPU utilization that was expected. It is called by default during
the test post-processing, and the plot will be saved as a .png file
in the test results output directory.
An example of how this plot looks like can be found here: https://gist.github.com/valschneider/b8f15ce92c3581a0e7928ae80c8cf306
=> tests/eas/generic: Add plot_expected_util

.travis.yml, ipynb/tutorial/00_LisaInANutshell.ipynb, libs/utils/analysis/tasks_analysis.py
These fixes aren't 100% necessary now but they fix real issues and later PRs will need them for the CI to pass.
=> Misc fixes to help CI

libs/utils/env.py, tests/lisa/test_wlgen.py, tools/wa_user_directory/config.yaml, tools/wltests/agendas/sched-evaluation-full-traced.yaml, tools/wltests/agendas/sched-evaluation-full.yaml, tools/wltests/agendas/sched-evaluation-small.yaml, tools/wltests/build, tools/wltests/platforms/hikey620_android-4.4/flash_images, tools/wltests/platforms/hikey960_android-4.4/flash_images, tools/wltests/platforms/wahoo_android_v4.4/build_images, tools/wltests/platforms/wahoo_android_v4.4/definitions, tools/wltests/platforms/wahoo_android_v4.4/flash_images, tools/wltests/test_series
This series refactor a bit test_series and extends it to support Pixel 2 devices.
Thanks to @credp for the identification of a stable sequence to flash update a Pixel device with a new kernel and modules.
The first couple of patches progress also submodules dependencies, although they can go into a different PR I've kept them here just because that's the most advanced stack I've used to test the integration on pixel devices.
=> Wltests pixel2 support

libs/utils/env.py, libs/utils/executor.py, tests/eas/capacity_capping.config, tests/eas/capacity_capping.py
Lazarus version of https://github.com/ARM-software/lisa/pull/376
=> Futuristic userspace freezer

libs/utils/android/workloads/uibench.py
Lazarus version of https://github.com/ARM-software/lisa/pull/328
=> uibench actions

libs/wlgen/wlgen/__init__.py, libs/wlgen/wlgen/rta.py, tests/lisa/test_wlgen_rtapp.py
Pretty much unchanged https://github.com/ARM-software/lisa/pull/461 - resolved merge conflict and applied some nitpicking.
=> rta-barrier

libs/utils/energy.py
Based on https://github.com/ARM-software/lisa/pull/509
=> utils/energy: Logging QoL

libs/utils/wa_results_collector.py
This is a cleanup version of #546 which addresses all my comments to the original @credp  PR.
Tested on my machine, seems to work and still give the pretty nice speedups of the original series.
Please give them a try, and if you are happy, just press the merge button to also close #546
=> Wa collector speedup

tests/eas/load_tracking.py
The class _PELTTaskGroupsTest(LisaTest) has been updated to
freeze the userspace as expected by the new syntax.
Namely, the userspace is freezed in a "with" statement to
catch error and unfreeze correctly in this case.
Signed-off-by: Elieva Pignat <Elieva.Pignat@arm.com>
=> Loadtracking.py: Cgroups test userspace freezing update

libs/utils/env.py, libs/utils/platforms/juno_r0_energy.py, tests/lisa/test_energy_model.py
1) Fix Juno R2 energy model.
2) Change the optimal task placement algorithm used by LISA to better match EAS behavior.
EDIT: removed 2)
=> Fix Juno R2 energy model

libs/utils/wa_results_collector.py
Hi,
These 2 patches fix the support of the computation of statistic for total_frame_duration
Regards,
=> Fix jankbench wa support

libs/utils/wa_results_collector.py
To map a WA run with a kernel commit sha1, we currently read whatever
__meta/target_info.json reports for "kernel_release" (which should be
the equivalent of uname -r).
However, there are cases where this doesn't seem to be reported. For
instance, a HiKey960 built with hikey960_defconfig will not report the
commit sha1 in its version data, which will cause an exception in the
results collector code.
Since the sha1 is included in the results directory name anyway, use
that instead as a more reliable source.
=> utils/wa_results_collector: Change sha1 acquisition method

libs/utils/energy_model.py
Since we have the new EM in the android-mainline-tracking branch, I figured we should be able to read it from the target. Here's a go at adding it to LISA.
=> RFC: Load from simplified em

libs/utils/wa_results_collector.py
Hi these, patches are few changes that helps to use the .ipnb like sched-full-evaluation.ipnb as a python script for post processing.
=> Some changes proposal and fixes

tests/eas/generic.py
Couple of fixes from @deggeman , one of them is maybe temporary but necessary to be able to test the simplified energy model. Both commits have already been used for a few integrations.
=> tests fixes

libs/utils/wa_results_collector.py
Hi guys, this is what I'm using right now for Monsoon energy meter support. It's slightly ahead of the one we merged already. I think I need to rebase and push again before we merge this.
=> Wltest monsoon composite energy

.travis.yml, doc/conf.py, doc/internals.rst, doc/kernel_tests.rst, doc/lisa_tests.rst, doc/pedantic_build.sh, doc/wlgen.rst, lisa/energy_model.py, lisa/env.py, lisa/tests/kernel/scheduler/eas_behaviour.py, lisa/tests/kernel/scheduler/load_tracking.py, lisa/tests/kernel/test_bundle.py, lisa/trace.py, lisa/utils.py, lisa/wlgen/rta.py, lisa/wlgen/sysbench.py, lisa/wlgen/workload.py, setup.py
Posting this as a PR to make sure it works.
=> travis: Update configuration

lisa/env.py
This uses Python's argparse library.
I couldn't find a  way to make subparsers work the way I want them to work (I want to be able to specify `--kind=android` or `--kind=linux`, not just `android`/`linux`), so I had to make do.
With this baby it's easy to write a script `dummy.py`:
```python
#!/usr/bin/python3
from lisa.env import TestEnv
te = TestEnv.from_cli()
print(te.target.echo("42"))
```
```bash
./dummy.py 
usage: dummy.py [-h] --kind {android,linux,host}
dummy.py: error: the following arguments are required: --kind/-k
```
```bash
./dummy.py -k android
usage: dummy.py [-h] --kind {android,linux,host} --device DEVICE
dummy.py: error: the following arguments are required: --device/-d
```
```bash
./dummy.py -k linux
usage: dummy.py [-h] --kind {android,linux,host} --hostname HOST …
```
=> env: TestEnv: Add a from_cli() alternative constructor

lisa/env.py, lisa/tests/kernel/scheduler/eas_behaviour.py
=> env: Remove ArtifactPath

doc/pedantic_build.sh
Allow investigation issues not reproducible locally
=> doc: Show sphinx log

doc/overview.rst, install_base_ubuntu.sh
Just a bunch of minor things I found out while installing Lisa next on my (relatively fresh) Ubuntu 18.04 setup.
=> [next] Minor setup improvements

lisa/energy_model.py, lisa/exekall_customize.py, lisa/utils.py, tools/bisector/bisector/bisector.py, tools/exekall/exekall/customization.py, tools/exekall/exekall/engine.py, tools/exekall/exekall/main.py
Most visible change: 
* `TargetConf` have been renamed to `TestEnvConf` to match its actual usage. Top-level key in YAML file has changed accordingly to 'testenv-conf'
* Target connection settings are now located under a "target" subkey in `TestEnvConf`:
```
testenv-conf:
target:
name: foo
host: foobar
password: mypassword
username: foobar
```
The same changes applies to the dictionary passed to `TestEnvConf.__init__`
=> Misc improvements/fixes

init_env, install_base_ubuntu.sh
Small fixes to get proper Android SDK support and make devlib happy
=> Next install sdk build tools

lisa/utils.py
Add docstrings to all methods and classes related to configuration
management.
=> utils: Add MultiSrcConf docstrings

tools/bisector/bisector/bisector.py, tools/bisector/bisector/xunit2json.py
* removal of usage of pathlib
* allow ignoring a testcase
* small cleanups
=> bisector cleanup

lisa/utils.py, tools/exekall/exekall/engine.py
Since the ruamel.yaml issue #244 has been solved, remove the workaround
in LISA
https://bitbucket.org/ruamel/yaml/issues/244
=> Remove workaround for ruamel.yaml issue #244

doc/overview.rst, shell/lisa_shell, tools/check-setuppy, tools/post-checkout
Check that setup.py files have not been modified since last time
lisa-install was run.
Also provide a post-checkout hook for git to carry out the check on each
branch checkout.
=> shell: Add check updates to setup.py files

lisa/platforms/platinfo.py
Add details on some key format and remove some deprecation message.
=> platinfo: Update description of keys

doc/conf.py, doc/kernel_tests.rst, lisa/exekall_customize.py, lisa/tests/kernel/scheduler/eas_behaviour.py, lisa/tests/kernel/scheduler/load_tracking.py, lisa/tests/kernel/test_bundle.py, shell/README.txt, shell/lisa_shell, target_conf.yml, tools/exekall/exekall/_utils.py, tools/exekall/exekall/customization.py, tools/exekall/exekall/engine.py, tools/exekall/exekall/main.py, tools/exekall/exekall/utils.py, tools/exekall/setup.py
* Deep refactoring/cleanup of exekall
* rework of lisa-test, so it's slightly easier to use than exekall directly (see update to shell/README.txt)
* Generate the list of kernel tests in the Sphinx documentation using exekall. This allows tying things together as ID components are clickable.
=> exekall's (early) spring cleanup

lisa/tests/kernel/staging/load_tracking.py, lisa/tests/kernel/test_bundle.py
=> Make CPUMigrationBase available to exekall

lisa/tests/kernel/staging/load_tracking.py
=> lisa: staging: load_tracking: fix from_testenv

.travis.yml, Vagrantfile, init_env, install_base_ubuntu.sh, setup.py, shell/lisa_shell
Here are the few changes I've found useful to enable ipywidgets in JupyterLab.
If they are installed/enabled correctly, this notebook should just work:
https://github.com/jupyter-widgets/ipywidgets/blob/e27c7a81fd7ff96ea74726575845b61e81c5c855/docs/source/examples/Using%20Interact.ipynb
=> Add ipywidgets

external/devlib/devlib/bin/scripts/shutils.in
Make sure to pull https://github.com/ARM-software/devlib/pull/363
=> [Next] pull devlib

install_base_ubuntu.sh
The caller of the script decides which under which user it has to run,
and which tool is used to accomplish that.
=> install_base_ubuntu: remove use of sudo

tools/bisector/bisector/bisector.py, tools/exekall/exekall/engine.py, tools/exekall/exekall/main.py
To have multiple iterations of the same set of tests, sharing the TestEnv so that LISA connects only once to the target to avoid multiple RTapp calibrations:
```
exekall run lisa/tests/ --conf target_conf.yml -n10 --share '*TestEnv'
```
Also add -odelete-artifact in bisector.
=> exekall: support multiple iterations

tools/bisector/bisector/bisector.py
Only show pass rates when explicitely asked for or when all iterations
are passing. Otherwise, only show the issues to minimize the number of
lines displayed.
Also fix ignore-non-issue to handle skipped and undecided.
=> bisector: Fix rates display

tools/exekall/exekall/main.py
Allow running the tests in a random order.
=> exekall: add --random-order

shell/README.txt
=> shell: Updated README lisa-ipython -> lisa-jupyter

lisa/tests/scheduler/misfit.py
This test is just a subtest of test_throughput(), and was only added
because we initially had high failure rates. With the proper scaling
of the allowed idle time, both tests have a near identical pass rate,
so let's remove the subtest.
=> lisa/tests: misfit: Remove test_migration_delay()

tools/bisector/bisector/bisector.py
Yield step has now a more sensible behavior when running for a fixed
number of iterations
=> bisector: Fix yield step

lisa/tests/scheduler/load_tracking.py
I somehow missed that the "signals" parameter is unused, and sort of
broke the plotting (we plot the whole df). The assertions themselves
do fetch the right signal from the df however.
Remove that parameter and cleanup the remaining places where we didn't
do df[signal_name].
=> lisa/tests: load_tracking: Fix get_task_sched_signals uses

libs/utils/energy_model.py
Since commit 9001b8f1a,
"ANDROID: sched: Add support for frequency/power energy model"
android-4.14 has been able to load a frequency-based energy model.
Adding this extended the capacity_state structure in
sched_group_energy with a new frequency member. This is automatically
reflected in the energy model tuples printed in procfs and so Lisa can
no longer load sensible Energy models from any target running
android-4.14 later than the above commit, although the error is not
detected so you do get an EnergyModel object which contains junk
capacity and power values.
We can figure out which kind of kernel we have by reading the number
of capacity states for a cpu and check how many items are in the
cap_state tuples so that we can handle 2 or 3 values per state
transparently.
Signed-off-by: …
=> utils/energy_model: Fix loading EM from recent android-4.14 targets

tools/bisector/bisector/bisector.py
Pass a class when expected instead of an instance.
=> bisector: Fix parameter type

lisa/energy_meter.py
Fix missing HideExekallID import
=> lisa.energy_meter: fix import

lisa/exekall_customize.py
=> lisa: Fix exekall_customize

tools/bisector/bisector/bisector.py
* Python 3.4 is not supported by LISA and is not really relevant anymore, since Ubuntu Xenial 16.04 LTS ships with 3.5.
* small refactoring of YAML management, to make it similar to how it is done in lisa.utils
=> bisector: various cleanups

tools/exekall/exekall/_utils.py
Truncate the source location of classes and functions to the path from
their top level package (including the package name itself). That
removes some clutter from all generated artifacts containing these
locations.
=> exekall: Report shorter source location

tools/bisector/bisector/bisector.py
Should have tested better the recent changes ...
This fixes `bisector run` and the `-ouse-systemd-run` step option.
=> bisector: Fix recent additions

lisa/conf.py, lisa/target.py, lisa/utils.py
* Avoid showing internal helpers of lisa.conf
* Log calls to `add_src` the same way key usage is logged.
=> Improve conf key access logging

lisa/conf.py
Fix union between sets and avoid showing derived keys that cannot be
computed due to missing prerequisites.
=> lisa.conf: Fix autocompletion hint for MultiSrcConf keys

lisa/conf.py
Fix a previous rebase indentation issue.
=> lisa.conf: Fix indentation

doc/kernel_tests.rst, doc/pedantic_build.sh, lisa/utils.py
Fix ignored warning patterns, and make more obvious why a warning is ignored or not
=> doc: Fix ignored warning pattern

lisa/analysis/frequency.py, lisa/analysis/idle.py, lisa/analysis/latency.py, lisa/analysis/load_tracking.py, lisa/analysis/status.py, lisa/analysis/tasks.py, lisa/analysis/thermal.py, lisa/tests/base.py, lisa/tests/scheduler/eas_behaviour.py, lisa/tests/scheduler/load_tracking.py, lisa/tests/scheduler/misfit.py, lisa/trace.py, tests/test_trace.py
This is based on top of https://github.com/ARM-software/lisa/pull/779
This involved me losing many brain cells fighting with trace.py. Details in the commits logs.
=> lisa/tests: Handle noisy tasks

lisa/tests/scheduler/eas_behaviour.py, lisa/trace.py
* Make sure we have a private copy of the event list, to avoid modifying things that are supposed to be read-only (like ftrace_conf)
* Minor improvement to a docstring in eas_behaviour
=> Fix events param handling in lisa.trace.Trace

tools/batch-rebase
Allow creating a branch that is composed of multiple other topic
branches, rebased on top of each other.
=> tools: Introduce batch-rebase

.travis.yml, doc/conf.py, doc/kernel_tests.rst, install_base_ubuntu.sh, lisa/tests/base.py, lisa/tests/hotplug/torture.py, lisa/tests/scheduler/eas_behaviour.py, setup.py
Output can be previewed here: https://my-lisa.readthedocs.io/en/lisa-next/kernel_tests.html
=> Doc: class diagrams

tools/bisector/bisector/bisector.py
Make sure there is a header line for each list of iteration details.
=> bisector: Fix -oshow-details

tools/batch-rebase
Allow setting the topic branch tags suffix
=> batch-rebase: Add --tags-suffix option

tools/exekall/exekall/engine.py
ExprData is supposed to be different for each expression, but ended up
being shared. Make sure it is not by cloning the expressions.
=> exekall: Fix wrong ExprData sharing

lisa/wlgen/rta.py, tests/assets/mp3-short.json
Recurse into the nested mapping instead of doing text-based tricks on
the JSON representation. That ensures we don't need to manage any kind
of quoting and allows better control to what path in the JSON file we
would allow updating.
=> lisa.wlgen.rta: Cleanup RTA.by_str()

lisa/trace.py
To remove the ambiguity about what delta it exactly returns.
=> trace.py: improve add_events_deltas() docs

doc/conf.py, lisa/analysis/base.py, lisa/analysis/cpus.py, lisa/analysis/frequency.py, lisa/analysis/functions.py, lisa/analysis/idle.py, lisa/analysis/latency.py, lisa/analysis/load_tracking.py, lisa/analysis/rta.py, lisa/analysis/status.py, lisa/analysis/tasks.py, lisa/analysis/thermal.py
All plotting functions now take both filepath and axis/axes parameters
with the same semantic everywhere. In a few of them, the parameter "pct"
has been moved before filepath for consistency.
This was only tested so far with the self-tests, so it would need some more coverage.
EDIT: also tested with:
* ipynb/examples/typical_experiment.ipynb
* ipynb/tests/synthetics_example.ipynb
=> lisa.analysis: Align plotting functions

lisa/exekall_customize.py
Rename "changed" => "significant".
=> exekall: compare: Update output column name

doc/man1/exekall.1, shell/lisa_shell, tools/exekall/exekall/main.py, tools/lisa-test
Update $LISA_HOME/results_latest symlink to point to exekall artifact
folder when running lisa-test.
=> lisa-test: Create latest_results symlink

shell/README.txt, shell/lisa_shell
Add a command to log the squashed commits of subtrees:
$ lisa-log-subtree external/devlib --oneline
=> shell: Add lisa-log-subtree

tools/bisector/bisector/bisector.py
Sort numbers contained in the string as numbers instead of pure strings.
This allows this kind of ID to be sorted as one would expect:
invariance[board=XXX]:iter_invariance_items[cpu=0@2]
invariance[board=XXX]:iter_invariance_items[cpu=0@10]
=> bisector: Use natural sort for testcase ID

doc/conf.py
source init_env from conf.py, since it is the only place we can hook
into to execute code for RTD. This allows getting all environment
variable defined as on a regular setup, which is needed to generate
parts of the documentation.
=> doc: source init_env for ReadTheDocs setup

doc/man1/exekall.1, lisa/tests/scheduler/load_tracking.py, tools/exekall/exekall/engine.py, tools/exekall/exekall/main.py, tools/exekall/exekall/utils.py
This allows easier debugging, when we need to run the invariance test on one CPU and frequency.
=> Expose InvarianceItem.from_target

tools/exekall/exekall/engine.py
--restrict can be used in conjunction with --forbid and will win.
=> exekall: --restrict has priority over --forbid

README.md, doc/lisa_shell/man/man.rst, doc/man1/lisa.1
Make the online doc link more visible in the lisa man page.
=> doc: Move up doc link in lisa man page

lisa/wlgen/sysbench.py
=> wlgen.sysbench: Cleanup command line building.

lisa/analysis/tasks.py
This provides a new convenient task analysis API to generate a stacked
plot of CPUs residency time for a list of specified tasks.
Such an analysis could be useful to identify where a bunch of important
tasks (e.g. top-app tasks) spend most of their time. The generated
dataframe and plots sorts tasks by increasing running time, thus making
it even more simple to identify the most active tasks.
=> tasks_analysis: Add a multiple-tasks CPUs residency plot

lisa/exekall_customize.py, lisa/regression.py, lisa/tests/base.py, lisa/tests/scheduler/load_tracking.py, lisa/tests/staging/sched_android.py, lisa/utils.py
Introduce AggregatedResultBundle to be used in load_tracking Invariance aggregated tests and #829
=> AggregatedResultBundle

lisa/analysis/base.py, lisa/analysis/cpus.py, lisa/analysis/frequency.py, lisa/analysis/functions.py, lisa/analysis/idle.py, lisa/analysis/latency.py, lisa/analysis/load_tracking.py, lisa/analysis/rta.py, lisa/analysis/status.py, lisa/analysis/tasks.py, lisa/analysis/thermal.py
Pass down kwargs to do_plot() to simplify adding new common plot
parameters and potential decorator implementation.
=> lisa.analysis: Use **kwargs in all plot functions

tools/exekall/exekall/_utils.py
Handle None without exceptions.
=> exekall: Fix utils.get_name()

tools/bisector/bisector/bisector.py
Since GLib can decide to abort the whole application for still unknown reasons, disable DBus by default until the issue is either fixed or confirmed to be caused by some buggy interaction with graphical things. Unfortunately, it seems impossible to use GLib without trying to connect to X server unless DISPLAY is unset, which is not very practical and still gives some warnings anyway.
=> bisector: disable DBus interface by default

lisa/analysis/tasks.py
With `overlay=True`, it will adapt to data already plotted on the given ``axis``, with 1/4 of the height and alpha=0.5 . This allows quick overlaying over an existing plot, to see how rtapp activations are impacting whatever signal is being looked at:
=> kernelshark-like activation plot

lisa/analysis/base.py, lisa/tests/base.py, lisa/trace.py, lisa/utils.py
* Fix events checker decorator unwrapping optimization
* Fix the bbox of save_plot()
* Add update_wrapper_doc() to factor out the docstring fixups wanted when writing "invasive" decorators
=> misc fixes

tests/test_trace.py
Trace.squash_df has been moved to datautils.df_squash
=> tests: Fix references to Trace.squash_df

doc/conf.py, lisa/datautils.py
Also use mathjax for rendering equation in Sphinx since we mainly target HTML doc rather than Latex
=>  lisa.datautils: Fix docstring math syntax

ipynb/examples/typical_experiment.ipynb
Update links to match new documentation.
=> ipynb: Fix broken links

ipynb/profiling/kernel_functions_profiling.ipynb, lisa/analysis/frequency.py, lisa/analysis/functions.py, lisa/analysis/idle.py, lisa/analysis/status.py, lisa/energy_model.py, lisa/tests/scheduler/eas_behaviour.py, lisa/tests/scheduler/load_tracking.py, lisa/trace.py, tests/test_trace.py
Various cleanup to prepare the ground for future changes around trace parsers.
=> cleanup lisa.trace.Trace

lisa/trace.py
MissingTraceEventError provides better reporting when it comes to
events.
Make MissingTraceEventError inherit from ValueError to avoid a
compatibility break.
=> lisa.trace: Raise MissingTraceEventError from Trace.df_events()

tools/kmodules/sched_tp/0001-sched-add-a-module-to-convert-tp-into-events.patch, tools/kmodules/sched_tp/sched_tp.c
Kbuild test robot says it can be made static, so make it static :-)
=> sched_tp: make sched_tp_finish() static

shell/lisa_shell
Remove references to _lisa-jupyter-usage now that its content has been moved to
man lisa.
=> lisa-shell: fix lisa-jupyter

lisa/tests/base.py
List all the sources of information used to build the FtraceConf object.
=> lisa.tests.base: Clarify RTATestBundle.ftrace_conf building flow

lisa/target.py
Some Android userspaces may not set the sys.boot_completed property, breaking
the connection to the target. Make the wait optional, so that Target can be used
swiftly with these devices.
=> lisa.target: Make the "wait boot completed" feature optional

lisa/tests/scheduler/load_tracking.py, lisa/wlgen/rta.py
* Fix wlgen run parameter handling
* Make sure the workload can execute at the target OPP
=> Fix load_tracking InvarianceItem workload

doc/conf.py, doc/plot_conf.yml, doc/traces/plat_info.yml, lisa/analysis/base.py, lisa/doc/helpers.py, tools/lisa-plot
A built documentation with the example plots can be found at:
https://htmlpreview.github.io/?https://raw.githubusercontent.com/douglas-raillard-arm/lisa/_pr228_build/doc/_build/html/trace_analysis.html
=> Add example plots to documentation

lisa/analysis/frequency.py, lisa/analysis/load_tracking.py, lisa/analysis/thermal.py, lisa/datautils.py
Steps-post plots usually lack the last segment.
Fix that by making sure the plotted series contain index values at the beginning and end of the time range of interest.
=> Fix steps-post plots

lisa/datautils.py
Avoid unnecessary conversion of Index to Series.
=> lisa.datautils: Optimize _data_window()

lisa/energy_meter.py, lisa/tests/scheduler/eas_behaviour.py, lisa/tests/scheduler/load_tracking.py, lisa/wa_results_collector.py
=> lisa: use series_integrate and series_mean from datautils

lisa/wlgen/rta.py
Also update some docstrings to match better the parameter list
=> Fix RTATask.__add__

doc/man1/lisa.1, init_env, shell/lisa_shell, tools/wltests/README.md, tools/wltests/test_series
* cleanup ANDROID_HOME path-related bits
* give priority to binaries shipped in LISA over the ones from the distribution
=> Update PATH management

lisa/analysis/base.py, lisa/target.py
Allow registering extra command line parameters, allowing to easily
create a script that takes some domain-specific parameters, to share a
reproducer for example.
=> lisa.target: Add Target.from_custom_cli()

setup.py
Use a dict(str, list(str)) instead of dict(str, str).
=> setup.py: Fix package_data format

lisa/tests/scheduler/load_tracking.py, lisa/wlgen/rta.py
* Fix the CPU rq util expected mean
* cleanup CPUMigrationBase
* Generalize to N-tasks on N-CPUs
=> Fix CPUMigrationBase

lisa/utils.py
Since showing that URL requires downloading the inventory, avoid doing it at
import-time in the general case. It is still done when a deprecation warning is issued.
=> lisa.doc: Only include the URL in deprecation warnings

lisa/tests/base.py
Add a couple of information in the docstring about FtraceConf building flow.
=> lisa.tests.base: Slight improvement of FtraceTestBundleMeta docstring.

tools/exekall/exekall/engine.py
This allows programmatic access to the tags of the FrozenExprVal.
=> exekall: Expose tag dictionary on FrozenExprVal

tools/exekall/exekall/engine.py
=> exekall: Fix PrunedFrozVal() super().__init__ call

lisa/wlgen/workload.py
RTApp requires a JSON description and generates log files.
Let's ensure all these assets are confined withing a dedicated folder so that
when we pull stuff we are sure to not get leftovers from previous executions.
This allows also to do a proper cleanup of the target once a test has completed.
=> wlgen/workload: Keep all assets into a dedicated folder

lisa/utils.py
Deprecated parameters will emit a warning when used, and the docstring will be
updated in right spot at the end of the relevant :param: block.
=> lisa.utils.deprecate: Allow deprecating a parameter

doc/index.rst, doc/lisa_shell/man/man.rst, doc/man1/lisa.1, tools/lisa-doc-build, tools/travis_tests.sh
* Move doc/pedantic_build.sh to tools/lisa-doc-build
* Update the documentation/man page to reference lisa-doc-build
* Slightly improve lisa-doc-build by allow running it from anywhere
=> tools: Add lisa-doc-build

lisa/conf.py, lisa/utils.py
TODO: cli tool/online doc generating default conf for all SimpleMultiSrcConf subclasses in one file.
=> Add key documentation to YAML conf output

lisa/tests/staging/scheduler/util_tracking.py, lisa/utils.py
Respin of https://github.com/ARM-software/lisa/pull/1085
Changes compared to initial PR are left as extra commits on top.
TODO: decide on how kernel version should be checked.
=> Test util est

.readthedocs.yml
This should make the build process faster since we seem to be hitting some
timeout.
=> doc: Only build HTML doc in ReadTheDocs

lisa/analysis/rta.py
Namedtuple types defined inside a class get a broken __qualname__.
Instead, move it out of the class so that it gets the right name.
=> lisa.analysis.rta: Move namedtuple out of class

lisa/analysis/tasks.py
Allow easily knowing where the task was running.
=> lisa.analysis.tasks: Add 'cpu' column to df_task_activations()

lisa/target.py, lisa/wa_results_collector.py, lisa/wlgen/rta.py
Use logging.warning() instead.
=> lisa: Avoid using deprecated logging.warn()

doc/conf.py, doc/workflows/ipynb/examples/typical_experiment.ipynb, doc/workflows/ipynb/tests/synthetics_example.ipynb, doc/workflows/notebook.rst, install_base.sh, ipynb/examples/typical_experiment.ipynb, ipynb/tests/synthetics_example.ipynb, setup.py
This allows showcasing all LISA capabilities in a single location, so that people can discover and see what can be done by just browsing the doc without installing anything.
This requires the nbsphinx Sphinx extension, itself needing pandoc in order to generate some restructured text output (just like nbconvert)
=> include notebook in Sphinx doc

tools/lisa-plot
Create the folder indicated by the dirname of the path, not the path itself.
=> tools: lisa-plot: Fix folder creation

lisa/conf.py
Only compute the deferred values for the sources that will actually be used.
=> lisa.conf: Add MultiSrcConf.eval_deferred(resolve_src=True) parameter

lisa/conf.py
Replace half-written sentence by an actual description.
=> lisa.conf: Fix DeferredValue docstring

lisa/tests/staging/schedutil.py
Match new version of the kernel patch series
=> Update schedutil ramp boot test

tools/bisector/bisector/bisector.py
Gracefully handle empty config files.
=> bisector: Handle empty config files

lisa/analysis/idle.py, lisa/analysis/tasks.py, lisa/datautils.py, lisa/wlgen/rta.py
Wrote that thing to test out some wakeup change, it's proven useful.
=> Helper to get idle CPUs at a given timestamp

lisa/analysis/idle.py, lisa/analysis/tasks.py, lisa/datautils.py, lisa/wlgen/rta.py
Accidentally merged ARM-software/lisa#1131 so revert it until review is done.
=> Revert "Helper to get idle CPUs at a given timestamp"

lisa/analysis/tasks.py, lisa/datautils.py
Depends on https://github.com/ARM-software/lisa/pull/1167
=> lisa.analysis.tasks: Get rid of non-rolling windowing

doc/plot_conf.yml, lisa/analysis/base.py, lisa/analysis/frequency.py, lisa/analysis/tasks.py, lisa/datautils.py, lisa/energy_model.py, lisa/tests/scheduler/eas_behaviour.py
Allow changing the colors of the plots done by a plot method, by temporarily
updating the color cycler on the axis in use.
Add active/sleep durations in `plot_task_activations(duration=True)`:
EDIT: Updated to also be able to plot the task duty cycle in [0...1], computed for each pair of activation and its following sleep.
=> lisa.analysis: Add plot_foo(colors=[...]) parameter

lisa/analysis/rta.py
Show the CPUs each phase ran on in labels of color bands drawn by
RTAEventsAnalysis.plot_phases().
=> lisa.analysis.rta: Display on which CPU each rta phase ran

lisa/analysis/rta.py
Use df_task_states() in order to get the CPUs the task ran on.
=> lisa.analysis.rta: Improve accuracy of plot_phases()' CPUs reporting

lisa/utils.py
YAML parser instances seem to not be reentrant anymore on Python 3.8.
Fix the reentrance issue by creating a new fresh parser instance each
time it is needed rather than recycling an existing one.
=> lisa.utils: Setup YAML parser on demand

lisa/conf.py
Cleanup the output so that unused levels are not shown.
=> lisa.conf: Prune empty mapping of SimpleMultiSrcConf.to_yaml_path()

lisa/datautils.py
=> lisa.datautils: Fix series_align_signal()

lisa/utils.py
Reentrant use of ruamel.yaml parsers are now failing, so make sure to create a
fresh parser for processing the !include-ed files.
=> lisa.utils: Fix Serializable._yaml_include_constructor() on Python 3.8

tools/bisector/bisector/bisector.py
Display the overall average iteration run time and the average run time per
step.
=> bisector: Add average run time of steps

lisa/datautils.py
Use :: for code blocks to avoid warnings in some versions of Sphinx.
=> lisa.datautils: Fix some docstrings

lisa/conf.py
Avoid printing very large sources in full, and improve pretty printing.
=> lisa.conf: Limit the amount of debug log when setting a new source

Vagrantfile
Allow using kernelshark from the VM.
=> Vagrantfile: Enable X11 forwarding

doc/plot_conf.yml, lisa/analysis/base.py, lisa/analysis/frequency.py, lisa/analysis/tasks.py, lisa/datautils.py, lisa/energy_model.py, lisa/tests/scheduler/eas_behaviour.py, tools/audioshark
=> Add audioshark

lisa/analysis/base.py, lisa/notebook.py, setup.py
=> Add mplcursors

tools/travis_tests.sh
Avoid issues with variable length sha1
=> tools/travis_tests.sh: Fix forbidden commit check

lisa/datautils.py
Simpler use of Pandas' groupby.
=> lisa.datautils: Simplify df_split_signals

lisa/tests/base.py, lisa/wlgen/rta.py
Pin the phase on the same CPUs as the following phase, to allow CPU signals
to converge if they are going to be monitored in the test.
=> lisa.tests.base: Improve rtapp buffer phase

lisa/wlgen/rta.py, tests/test_wlgen_rtapp.py
Properly assign the right CPU affinity to the rtapp phases.
=> lisa.wlgen.rta: Fix CPU affinity

lisa/tests/staging/util_tracking.py
Make sure all items in the tuples are int so they can be compared, instead of
(5, 5, None).
=> lisa.tests.staging.util_tracking: Misc fixes

lisa/analysis/rta.py
Use a simple get_loc() to select the right row.
Also fixes the events decorator to use the events from the right method.
=> lisa.analysis.rta: Speedup and fix RTAEventsAnalysis.df_phase_at()

lisa/analysis/tasks.py
Avoid this pattern:
values = df.col.unique()
for value in values:
sub_df = df[df.col == value]
...
Instead, use pandas groupby through df_split_signals:
for cols, sub_df in df_split_signals(df, [col]):
...
=> lisa.analysis.tasks: Use lisa.datautils.df_split_signals()

lisa/conf.py, lisa/wlgen/rta.py
Instead, raise an exception derived from KeyError so that user code will see
that the key is "missing".
=> lisa.conf: Avoid recursion error while computing DerivedKey

tools/batch-rebase
topics:
-
name: foo
remote: bar
base: foo-base
tip: foo
-
action: tag
name: mytag
suffix: ""
-
name: foo2
remote: bar
base: foo-base2
tip: foo2
=> tools/batch-rebase: Allow adding tags between topics:

lisa/platforms/platinfo.py
Since it's not used that often but uses a fair amount of memory and disk storage
when serialized, avoid fetching the symbols address unless needed.
=> lisa.platforms.platinfo: Make kernel/symbols-address deferred

doc/transition_guide.rst, lisa/doc/helpers.py, lisa/git.py, lisa/trace.py, lisa/utils.py
List git commits introducing breaking changes in the documentation, for quick reference.
Also add a table for deprecated APIs.
The result can be seen at:
https://lisa-linux-integrated-system-analysis.readthedocs.io/en/test-rtd/transition_guide.html#breaking-changes
=> doc: list breaking changes

lisa/analysis/tasks.py
Used when the task state is unknown. pandas.NA would have been a great fit,
except that there is seemingly no way to make enum.Enum play with it.
=> lisa.analysis.tasks: Add TASK_UNKNOWN state

lisa/datautils.py
Functions in datautils will now be available like this:
x = df_foobar(df, ...)
x = df.lisa.foobar(...)
=> lisa.datautils: Add a "lisa" custom namespace for Series and DataFrame

lisa/analysis/base.py
Allow setting any of the matplotlib rcParams:
https://matplotlib.org/tutorials/introductory/customizing.html
=> lisa.analysis.base: Add rc_params parameter to all plot method

doc/misc_utilities.rst, lisa/analysis/frequency.py, lisa/analysis/functions.py, lisa/analysis/idle.py, lisa/analysis/latency.py, lisa/analysis/load_tracking.py, lisa/analysis/notebook.py, lisa/analysis/rta.py, lisa/analysis/tasks.py, lisa/analysis/thermal.py, lisa/trace.py, lisa/typeclass.py, lisa/utils.py, tools/lisa-plot
Python implementation of typeclasses as found in Scala, Haskell, and Rust (known
as traits). They bring the ability to implement a given API for an arbitrary
set of types, without modifying the types themselves.
=> lisa.typeclass: Implement functional-style typeclasses

tools/lisa-plot
=> tools/lisa-plot: Add --xkcd

lisa/notebook.py
Actually take into account the parameter.
=> lisa.notebook: Fix axis_link_dataframe(follow_cursor=True)

lisa/tests/scheduler/eas_behaviour.py
Restrict 'big' duty cycle to a value that ensures migration to
bigs while it does not go high enough to cause potential thermal or
power throttling.
=> eas_behaviour: restrict bigs duty cycle

tools/lisa-plot
If the file path passed to --plot is "interactive", a matplotlib interactive
window will be used rather than creating a file.
=> tools/lisa-plot: Add interactive plot

tools/bisector/bisector/bisector.py
Setup the parser every time it's going to be used as it requires modifying a
global mutable singleton. That means that the setup would be overridden by other
libraries using ruamel.yaml.
=> bisector: Setup the YAML parser when needed rather than once and for all

lisa/wa_results_collector.py
This intends to drastically improve the parsing speed, especially with energy_measure data.
e.g. 50 PCMark runs on a Pixel4
Before: 20min
After: 1min
=> Wa results collector/parsing optimizations

lisa/target.py
Equivalent to OpenSSH's StrictHostKeyChecking option.
=> lisa.target: Add Target(strict_host_check=True) parameter

lisa/analysis/rta.py, lisa/datautils.py, lisa/tests/base.py
Use Series.array or Series.to_nump() instead. When just iterating over
values, iterate on the bare Series.
=> lisa: Avoid using deprecated pandas.Series.values

lisa/analysis/load_tracking.py, lisa/trace.py
Catch the exception rather than pre-check
=> Remove explicit check fo event availability

lisa/datautils.py
Use pandas categorical dtype as an intermediate type to deduplicate the
strings to decode. Since decoding is expensive, this is faster, and the
result is also less memory hungry since strings are deduplicated.
=> lisa.datautils: Speed up the conversion from strings to bytes

tools/batch-rebase
Fix handling of cherry pick conflicts in batch-rebase
=> Fix batch-rebase

lisa/energy_model.py
* Refactor from_target() to expose better the layout of the structure,
so that the origin of each piece of data is obvious.
* Remove the reliance on debugfs perf domain folder names that can
change from one kernel to another. Instead, use all the folders
containing the cost, frequency and capacity files.
* Ensure internal consistency of data by only using the strictly
necessary information from sysfs (capacities) and debugfs (everything
else). Specifically, do not use the CPU count from devlib since the EM
from debugfs already provides the information about available CPUs.
=> lisa.energy_model: Refactor LinuxEnergyModel.from_target

install_base.sh
This is required to build pyarrow
=> install_base.sh: Add cmake as a dependency for arm64

lisa/target.py
* Log debug things at debug level rather than info
* Remove duplicated code
=> lisa.target: Reduce amount of logging

lisa/conf.py, lisa/platforms/platinfo.py
If an exception is raised when keys are populated from a target, log an
error and wrap it in a DeferredExcep value. This way, the exception will
actually be raised only when the key is actually used.
=> lisa.platforms.platinfo: Defer exceptions raising

lisa/analysis/functions.py
Avoid clash with FunctionsAnalysis
=> lisa.analysis.functoins: Change JSONStatsFunctionsAnalysis.name

tools/lisa-plot
BREAKING CHANGE
Rename --platinfo into --plat-info to align with other tools.
=> tools: lisa-plot: Rename --platinfo into --plat-info

lisa/conf.py, lisa/exekall_customize.py, lisa/trace.py
Same issue and fix as for:
https://github.com/ARM-software/devlib/pull/439
=> Fix exception unpickling 

lisa/conf.py
Since we do not rely anymore on super().__init__(), explicitly list all
the keyword arguments that are allowed.
=> lisa.conf: Fix ConfigKeyError.__init__()

lisa/energy_model.py
Expose clearly what is the structure of the EnergyModel being built by
expanding the list comprehensions.
=> lisa.energy_model: LegacyEnergyModel: Expand list comprehensions

lisa/analysis/base.py
Passing positional parameters to plot methods when they have a default
values leads to passing it twice to the method, once as a positional and
then again as a keyword.
Solve the issue by factoring the positional parameters in the keyword
arguments, which simplifies the task and avoids that issue.
=> lisa.analysis.base: Fix plot_method() positional parameters

tools/batch-rebase
Allow suffixing both the new branch and the tags in one go.
Also make --tags-suffix imply --tags.
=> tools: batch-rebase: Add --refs-suffix

doc/trace_analysis.rst, lisa/trace.py
Since it's using a const char* field, raw format does not work as it
will display a string pointer rather than the actual string.
=> lisa.trace: Add ipi_entry event desc

lisa/trace.py
If the given parser is an object that does not have a __module__ and
__qualname__ attributes (such as types and functions), add a random UUID
to the trace state so that dataframes produced with it will not be
reloaded by another Trace instance.
This ensures that dataframes will be evicted as they should when another
parser with potentially custom event parsers will be used.
=> lisa.trace: Ensure cache eviction for custom parsers

lisa/trace.py
pyarrow cannot handle integers larger 2**64. When this happens, there is
not much other choice than skipping writing to swap.
=> lisa.trace: Handle OverflowError when writing to parquet

lisa/datautils.py
Allows using a "pointer" column to point at values in other columns, to
achieve some sort of index-aware join.
=> lisa.datautils: Add {df,series}_dereference()

lisa/wlgen/rta.py
Once the devlib commits are merged:
* remove them from this branch
* merge the remaining part of the branch
=> Fix target globbing

lisa/analysis/frequency.py
* Only require one of cpu_frequency, userspace@cpu_frequency_devlib
* Fix typo in reference to userspace@cpu_frequency_devlib
* Fix wrong column names
=> lisa.analysis.frequency: Fix df_cpu_frequency()

lisa/analysis/frequency.py
Return the dataframe of cpu_frequency event, augmented by
userspace@cpu_frequency_devlib but only if the devlib event came before
the cpufreq one for each CPU (to provide an initial value).
=> lisa.analysis.frequency: Avoid duplicated index in df_cpus_frequency()

lisa/target.py
Allow executing remotely a python function, provided the python
intepreter is installed on the target.
Also provide a Target.target_func decorator to turn a regular function
into a remote one transparently.
note: the remote functions are not allowed to depend on anything else
than standard library.
=> lisa.target: Add Target.execute_python()

lisa/analysis/tasks.py, lisa/utils.py
* Avoid DataFrame.append() building anti pattern
* Simplify some code
=> lisa.analysis.tasks: cleanup task residency computation

lisa/tests/scheduler/misfit.py, lisa/trace.py
One misfit fix looking at the TC2 failures, and one collateral fix to trace.py, fresh out of the oven.
=> TC2 misfit fix

tools/lisa-plot
Handle all kind of exceptions rather than just missing config keys
=> tools: lisa-plot: Fix --best-effort

lisa/datautils.py
Convert correctly series of b'0'/b'1' to True/False, rather than the
former True/True.
=> lisa.datautils: Fix series_convert(..., 'bool')

lisa/wa.py
Add missing ".stats" to get a Stats object.
=> lisa.wa: Fix WAOutput docstring

lisa/analysis/base.py, lisa/notebook.py, lisa/trace.py
Enable interactive mode by default when running under IPython, as
documented.
=> lisa.analysis.base: Fix default for setup_plot(interactive)

lisa/analysis/base.py
Match the documentation and forward variable keyword arguments to
matplotlib Figure() in setup_plot()
=> lisa.analysis.base: Forward kwargs to Figure() in setup_plot()

lisa/tests/scheduler/misfit.py
The stagger computation uses a flooring division, which doesn't really mix
with the expected range of the computation (ms i.e. 1e-3).
One could use a true division instead, but the original ratio doesn't make
much sense anyway, so let's just make it scale against the load balance
interval.
=> lisa.tests.scheduler.misfit: Fix stagger delay computation

lisa/analysis/tasks.py
When preempted_value is set to a non-NaN value, take it into account when:
* computing the duty_cycle
* combining consecutive rows that have the same active state
=> lisa.analysis.tasks: Improve df_task_activation(preempted_value != NaN)

lisa/wa.py
Allow artifact collectors to declare which workload name they expect,
and swallow any exception if the expected name is set and does not match
the given JobOutput.
=> lisa.wa: Avoid error logging for mixed WA workloads

devmode_requirements.txt, lisa/datautils.py, setup.py
Since lisa.wa dependens on the wa package provided by the
workload-automation PyPI package, add it to setup.py.
=> setup.py: Add "wa" optional dependency set

lisa/trace.py
Properly fuse OptionalTraceEventChecker when they appear inside an
AssociativeTraceEventChecker.
=> lisa.trace: Fix OptionalTraceEventChecker composition

lisa/tests/hotplug/torture.py
Allow checking for dmesg warning errors etc while doing hotplug torture,
since hotplug is very prone to triggering problems in various kernel
subsystems.
=> lisa.tests.hotplug.torture: Add dmesg_test() to HotplugTorture

.github/workflows/test.yml, .travis.yml, README.rst, Vagrantfile, doc/contributors_guide.rst, install_base.sh, tools/tests.sh
Run the self tests on github actions.
=> .github: Configure github actions

lisa/trace.py
Events without a parser already in LISA will now default to parsing the
raw output of trace-cmd, since the human readable one will either be
identical or impossible to parse without a handcrafted parser.
=> lisa.trace: Use trace-cmd raw report for unknown events

lisa/datautils.py
The df_delta function merges two dataframes of events
that are intended to be consecutive, e.g. the first 'pre'
event is emitted as the entry of a function, and a'post'
event is emitted at the exit.
The function keeps all the columns of the 'pre' and 'post'
dataframe. It adds an additional 'delta' column containing
the duration between the emission of a 'pre' event and its
consecutive 'post' event.
Signed-off-by: Pierre Gondois <Pierre.Gondois@arm.com>
=> lisa.datautils: Add df_delta() function

lisa/conf.py, lisa/tests/base.py
Use the Python >= 3.6 dependency opportunity to remove metaclasses where possible and replace them by `__init_subclass__`.
=> Remove some metaclasses

lisa/trace.py
This reverts commit 9f2980fdfa3bcced14b480c891b900650bf126fe.
Revert this commit as filtering at trace-cmd level breaks global
timestamp deduplication that is necessary to manipulate with pandas.
=> Revert "lisa.trace: Workaround trace-cmd report bug"

tools/exekall/exekall/engine.py
Attempt to work around this bug by just restoring exceptions' __dict__:
https://bugs.python.org/issue40917
=> exekall: Workaround broken exception unpickling

lisa/utils.py
Allow using dict(groupby(...)) directly.
=> lisa.utils: Improve groupby()

lisa/pelt.py
Compute the step response of PELT.
=> lisa.pelt: Add pelt_step_response()

lisa/target.py
Expose devlib's `use_scp` parameter to utilise scp
for file transfer on targets that do not support SFTP.
=> lisa.target: Add Target(use_scp=False) parameter

lisa/conf.py
Fix MultiSrcConfABC.from_yaml_map_list() to not hide ValueError raised
when loading a file.
=> lisa.conf: Avoid hiding ValueError when loading a conf file

lisa/utils.py
Properly handle keyword arguments for curried functions.
=> lisa.utils: Fix curry() for keyword arguments

install_base.sh, tools/recipes/rt-app.recipe
WIP
wait to merge until various changes required in rt-app are merged to avoid inflating the cloned size too much
=> assets: update json-c versions to link with rt-app

install_base.sh
Attempt to find JAVA_HOME after the java packages had a chance to be
installed.
=> install_base.sh: Detect JAVA_HOME after installing the package

lisa/tests/scheduler/eas_behaviour.py
Workloads that will not have any valid placement (satisfying the util of
each task and the capacity of each CPU) are unsuitable to test EAS, so
catch this case and raise CannotCreateError.
=> lisa.tests.scheduler.eas_behaviour: Detect unsuitable workloads

lisa/utils.py
Avoid infinite recursion in SimpleHash.HASH_COERCE.
=> lisa.utils: Handle recursion in SimpleHash.HASH_COERCE

lisa/analysis/tasks.py, lisa/datautils.py, lisa/trace.py, tests/test_trace.py
Ensure the plot will not extend to the left of the window.
=> lisa.analysis.tasks: Fix plot_task_activation on trace windows

lisa/pelt.py
Fix pelt_swing for 0% and 100% duty cycles.
=> lisa.pelt: Fix pelt_swing for extreme duty cycles

lisa/tests/base.py
s/TestBundle.raise_skip/ResultBundle.raise_skip/
=> lisa.tests.base: Fix typo

lisa/tests/base.py
=> lisa.tests.base: Improve hotplugged CPUs exception message

tools/exekall/exekall/engine.py, tools/exekall/exekall/utils.py
Allow a method to refer to a TypeVar class attribute by name, such as:
class X:
T = TypeVar('T')
def f(self) -> 'T':
pass
=> exekall: Fix annotation resolution in methods

lisa/stats.py, lisa/wa.py
Add a wa_folder column to the dataframes so that we can correctly
discriminate between data comming from different folders, even if they
share the same set of tags (e.g. iteration might not be enough if the
output was done with separate invocations of WA).
=> lisa.wa: Add a wa_path column to the dataframes

lisa/wa.py
Ensure path trimming will always work no matter how many folders are
given.
=> lisa.wa: Fix wa_path trimming logic

lisa/analysis/base.py
Mimic what is done in holoviews codebase for the default color cycle.
=> lisa.analysis.base: Use hv.Cycle() for the default color cycle

external/devlib/devlib/module/sched.py, external/devlib/devlib/utils/ssh.py, external/workload-automation/wa/workloads/pcmark/__init__.py
Generated with lisa-update-subtrees.
=> Update subtrees to fetch PCMark 3 support from workload-automation

doc/workflows/ipynb/examples/analysis_plots.ipynb, doc/workflows/notebook.rst, lisa/analysis/base.py
Ensure the panel's width stretches to the plots width.
=> lisa.analysis.base: Fix plot UI layout

install_base.sh
Assume --install-all if no option is given.
=> install_base.sh: Default to --install-all

tools/lisa-doc-build
The shebang must be the first line in the file.
=> tools: lisa-doc-build: Fix shebang

tools/kmodules/sched_tp/sched_events.h, tools/kmodules/sched_tp/sched_tp.c, tools/kmodules/sched_tp/sched_tp_helpers.h
Updates with the following:
* Add update_time field to pelt_irq/cfs
* Add new cpu_capacity event
* Add some guards to protect against compilation errors when some configs are disabled
=> Sched tp updates

lisa/target.py, lisa/wlgen/rta.py
FIX
Avoid accidentally re-entering the calibration function while running
it.
=> lisa.wlgen.rta: Fix recursive calibration

lisa/wlgen/rta.py
The code snippet cannot be interpreted.
=> lisa.wlgen.rta: Fix module import in the documentation

lisa/trace.py
Detect when the trace buffer got overwritten and raise an exception to
avoid ending up with a broken trace that does not show events for some
CPUs.
=> lisa.trace: Detect dropped events

tools/exekall/exekall/_utils.py
=> exekall: Add missing import

doc/man1/bisector.1, doc/workflows/automated_testing.rst, tools/bisector/bisector/bisector.py
This adds support for ArtifactoryService and modifies or adds to the documentation about uploading and downloading artifacts.
=> Support for Artifactory in bisector

lisa/_kmod.py
FIX
Fix the issue reported at [1] by removing the vmlinux from the kernel
tree before building modules, so that Kbuild will not be tempted to
create a broken split .BTF section.
[1] https://lore.kernel.org/all/YfK18x%2FXrYL4Vw8o@syu-laptop/t/#md877c45455918f8c661dc324719b91a9906dc7a3
=> lisa._kmod: Avoid broken split .BTF section in .ko

lisa/wa.py
WA has a sysfs-extractor which copies the content of a folder before, after
and generates a diff of it. The collector 'sysfs-extractor' leverages those
artifacts.
Here's an example for the Pixel6 energy meters:
def pixel6_energy_meter(df):
df = df[df.value.str.contains('S4M_VDD_CPUCL0|S3M_VDD_CPUCL1|S2M_VDD_CPUCL2')]
df[['variable', 'value']] = df.value.str.split(', ', expand=True)
df['unit'] = "bogo-joules"
return df
df = WAOutput('pixel6/wa_output').get_collector(
'sysfs-extractor',
path='/sys/bus/iio/devices/iio:device0/energy_value',
df_postprocess=pixel6_energy_meter
).df
=> lisa.wa: Add collector for sysfs-extractor

lisa/trace.py
=> lisa.trace: Ensure Trace.trace_path is a string or None

doc/plot_conf.yml, lisa/analysis/frequency.py, lisa/trace.py
This patch set is to fixing peripheral clock analysis and support plotting the frequency.
The first two patches are to fix the clock event analysis, so that we can get the correct data frame for peripheral clocks.  The third patch adds method for plotting the peripheral clock frequency.
=> Fixes for peripheral clock

external/devlib.manifest.yaml
Remove topics that have been merged upstream.
=> external/devlib.manifest.yaml: Remove merged topics

lisa/analysis/base.py, lisa/analysis/load_tracking.py, lisa/analysis/tasks.py, lisa/datautils.py, lisa/energy_meter.py, lisa/energy_model.py, lisa/fuzz.py, lisa/trace.py, lisa/version.py, lisa/wa_results_collector.py, lisa/wlgen/rta.py, lisa/wlgen/workload.py, setup.py
Prepare release
TODO:
Split misc part in:
https://github.com/ARM-software/lisa/pull/1824
=> Prepare v3.0.0

.github/ISSUE_TEMPLATE/bug_report.md
Add questions reporters should include the answer of in bug reports
about how LISA was installed.
=> .github/ISSUE_TEMPLATE/bug_report.md: Add questions

lisa/_kmod.py
=> lisa._kmod: Bump Alpine to v3.16

lisa/trace.py
FIX
multiprocessing.Pool cannot nest as daemonic threads are not allowed to
have children.
=> lisa.trace: Avoid nested multiprocessing.Pool

lisa/datautils.py
FIX
Fix inplace=False behavior so that it does not modify the input.
Also speedup considerably the function by assuming most duplicated
values are not clustered. This is the common case and it avoids very
costly iteration of duplicated values.
=> lisa.datautils: Speedup and fix df_update_duplicates()

lisa/datautils.py, lisa/trace.py, pytest.ini
Rebuild the man pages with the latest sphinx version.
=> Fix tests 

lisa/_doc/helpers.py, lisa/_git.py, tools/check-setuppy, tools/git-hooks/post-merge, tools/lisa-whatsnew
To install the post-merge git hook:
```
lisa-install
cp tools/git-hooks/* .git/hooks/
```
=> Add lisa-whatsnew

lisa/trace.py
FIX
Change expected output for very recent versions of trace-cmd.
=> lisa.trace: Add compatiblity with recent trace-cmd

lisa/analysis/tasks.py
FIX
Using a trace window can remove all activations for a given task. That leads to <NA> values in dataframes, that bokeh chokes on. Avoid creating such <NA> values in the first place fixes that.
=> lisa.analysis.tasks: Fix plot_tasks_activation() with trace window

lisa/target.py
FEATURE
Expose devlib's max_async Target parameter. It is used to limit the max number of in-flight async commands at any point in time.
=> lisa.target: Expose devlib's Target(max_async=...)

lisa/notebook.py
FIX
Ensure hv.extension() is done after all imports, otherwise plots are not displayed in some circumstances:
https://github.com/holoviz/holoviews/issues/5491
=> ipynb: Update hv.extension() calls

tools/exekall/exekall/engine.py, tools/exekall/exekall/tests/suite.py
FEATURE
Recognize PEP 673 Self return annotation on classmethods as being a factory class method.
=> tools/exekall: Support PEP 673 Self return annotation

.github/workflows/test.yml, pytest.ini, tools/exekall/exekall/engine.py
Add Python 3.11 to the tested versions
=> .github/workflows/test.yml: Add Python 3.11

lisa/analysis/rta.py, pytest.ini, tools/lisa-doc-build
=> pytest.ini: Ignore internal deprecation warnings in holoviews

.github/workflows/test.yml
Adding extra mirrors will not make a difference as explained by: https://github.com/actions/runner-images/issues/675#issuecomment-1382027536
=> .github: Remove modifications to /etc/apt/sources.list

lisa/_kmod.py
FEATURE
Use Alpine v3.17 as kernel module compilation environment.
=> lisa._kmod: Update Alpine to v3.17.1

lisa/wa.py
FIX
WACollectorBase._get_job_df() should not be cached if the result depends on user input. Disable the cache in those cases.
=> lisa.wa: Fix caching of _get_job_df()

lisa/target.py
FIX
None is not acceptable for max_async so pass an integer default value.
=> lisa.target: Fix max_async=None

.readthedocs.yml
=> .readthedocs.yml: Bump Python version

lisa/trace.py
FEATURE
Report kernel module build error reporting in FtraceCollector: it will always raise a MissingTraceEventError() along with an error-level log stating that the module build was attempted because of unavailable events.
=> lisa.trace: Improve FtraceCollector kmod build error error reporting

doc/plot_conf.yml, doc/trace_analysis.rst, lisa/analysis/pixel6.py, lisa/notebook.py
Add a file for Pixel 6-specific analysis.
Include methods df_power_meter() for getting power meter readings in mW and plot_power_meter() for plotting out the meter readings from different channels.
=> lisa.analysis: Add Pixel 6 analysis

lisa/_kmod.py
FEATURE
from_sysfs_headers() uses both /proc/config.gz and /sys/kernel/kheaders.tar.xz to patch the user-provided tree. If that results in a build failure, the fallback is from_user_tree() that just asssumes the tree is ready.
If the tree is almost ready but the config is wrong, the module build using from_user_tree() might error if e.g. a config option such as CONFIG_SCHED_AUTOGROUP is enabled in the .config but not on the board, leading to trying to access to a non-existant struct member that will still be defined from BTF blob.
Instead of falling back to from_user_tree() straight away, fall back first to from_proc_config() that will use /proc/config.gz, which is very likely to be successful and has much higher chances of producing a working module.
=> lisa._kmod: Add a from_proc_config() kernel tree loader

lisa/tests/scheduler/sanity.py
FIX
CapacitySanity._from_target() was reusing the passed collector multiple times, leading to only the last trace being saved.
Instead, use the collector once and do all the work while collecting.
=> lisa.tests.scheduler.sanity: Fix use of collector

lisa/pelt.py
FIX
pelt_settling_time() was quite broken as the curve it implemented was rotated 180 degrees from what it should.
Fix it with correct support for non-zero initial condition and support for init > final.
=> lisa.pelt: Fix plet_settling_time()

lisa/trace.py
FIX
When all events are already provided by the kernel, FtraceCollector will skip loading the kernel module. In that circumstance, a None value was assumed to be a kernel module instance.
=> lisa.trace: Fix FtraceCollector when all events are already available

lisa/_assets/__init__.py, lisa/_kmod.py
FEATURE
Add a constant with the path to the binary tools for each ABI.
=> lisa._assets: Add ABI_BINARIES_FOLDER

lisa/_kmod.py
Add missing import for ABI_BINARIES_FOLDER
=> lisa._kmod: Add missing import

lisa/_kmod.py
Check that the possible events are a superset of the events actually defined.
=> lisa._kmod: Check FtraceDynamicKmod.possible_events property

.github/workflows/preview.yml, setup.py, tools/lisa-make-preview
lisa-make-preview creates a "preview" branch from the opened pull request with the "preview" tag, using batch-rebase to stack them on top of each other.
=> tools/lisa-make-preview: Add tool to make a preview branch

tools/batch-rebase, tools/lisa-make-preview
FEATURE
Allow defining the base of a topic as a number of commits behind the tip.
=> tools/batch-rebase: Add topics/*/nr-commits key

.github/workflows/test.yml
Cancel current test workflow if a new set of tests is triggered.
=> .github/workflows/test.yml: Cancel running tests when PR is updated

.github/workflows/preview.yml
When a PR is merged, we want the preview to be automatically updated.
=> .github/workflows/preview.yml: Ensure preview is recreated on PR merges

.github/workflows/mirror.yml, .github/workflows/preview.yml, .github/workflows/test.yml
Use actions/checkout@v3 and actions/setup-python@v4
=> .github/workflows: Update action versions

lisa/trace.py
FIX
Allow passing from_dat(events=None) to indicate all events are to be parsed, as in TxtTraceParser.__init__
This reverts commit 0411f4d02cb8ac1b0fc986975ff40697c502fbdb.
=> lisa.trace: Ensure TxtTraceParser.from_data(events=None) works

lisa/target.py
Make Target.__getattr__ work with lazy module loading in devlib directly, independently of the version.
Until there is a published version of devlib that supports lazy loading, LISA code must work with all possible behaviors.
This PR is made in preparation of that devlib PR and needs to be merged first so LISA module exclusion system keeps working across devlib versions:
https://github.com/ARM-software/devlib/pull/634
=> lisa.target: Shuffle around code in Target.__getattr__

lisa/_kmod.py
FEATURE
Capture dmesg output when loading kmod to provide more context in case of error.
=> lisa._kmod: Capture dmesg output when loading kmod

tools/batch-rebase
FIX
Remove use of classes removed from lisa._generic
=> tools/batch-rebase: Use typing instead of lisa._generic

target_conf.yml
Update comments on build-env settings.
=> target_conf.yml: Update comments

lisa/_kmod.py
FIX
Do not rely on system insmod, use busybox instead.
=> lisa._kmod: Use busybox insmod

lisa/_assets/kmodules/lisa/Makefile, lisa/_assets/kmodules/lisa/introspect_header.py, lisa/_assets/kmodules/lisa/introspection.h, lisa/_assets/kmodules/lisa/private_types.c, lisa/_assets/kmodules/lisa/requirements.txt, lisa/_assets/kmodules/lisa/sched_helpers.h, lisa/_assets/kmodules/lisa/tp.c, lisa/_kmod.py, setup.py, tools/kmodules/lisa/introspect_header.py, tools/kmodules/lisa/introspection.h, tools/kmodules/lisa/requirements.txt
FEATURE
For each type defined in vmlinux.h, allow compile-time introspection on struct/union/enum members.
=> lisa._assets.kmodules.lisa: Allow C type introspection

doc/setup.rst, lisa/_kmod.py
FIX
Give clear exception message and warning log about unsupported pre-installed kernel module setup.
=> lisa._kmod: Make it clear that some module setup are unsupported

lisa/_assets/kmodules/lisa/Makefile
Ensure that people actually read the doc or listened to warnings.
=> lisa._assets.kmodules.lisa: Gate in-tree building

lisa/wlgen/rta.py
FIX
Add missing new line between class description and parameters documentation.
=> lisa.wlgen.rta: Fix docstring of PeriodicWload

tools/recipes/pycparserext.manifest.yaml
Add a batch-rebase manifest for pycparserext so that we can easily refresh the lisa branch.
=> tools/recipes: Add pycparserext batch-rebase manifest

lisa/_cli_tools/lisa_load_kmod.py, lisa/_cli_tools/lisa_platinfo_extract.py, lisa/conf.py, lisa/platforms/platinfo.py, lisa/target.py, tests/test_conf.py
FEATURE
Returns a context manager that will disconnect the target automatically.
=> lisa.target: Add Target.closing()

lisa/analysis/frequency.py, lisa/analysis/idle.py, lisa/analysis/tasks.py, lisa/datautils.py, lisa/tests/scheduler/eas_behaviour.py
FIX
fillna(method=...) parameter has beeen deprecated, so use the ffill()/bfill() equivalent instead.
=> lisa: Remove use of pandas.Series.fillna(method=...)

lisa/_btf.py
FIX
BTFForwardDecl should not be considered when deduplicating type names, as it will always "conflict" with the actual type definition. That is not a big problem though, as forward declarations are never useful (they are created as needed when dumping C code, we never rely on the BTF ones)
=> lisa._btf: Fix renaming of BTFForwardDecl

setup.py
Remove the now unused pycparserext dependency
=> setup.py: Remove unused dependency

lisa/tests/staging/utilclamp.py
FEATURE
Add expected signal value to the debug plot.
=> lisa.tests.staging.utilclamp: Add expected signal plot

lisa/_assets/kmodules/lisa/Makefile
FIX
Ensure we don't include __pycache__ in the checksum.
=> lisa._assets.kmodules.lisa: Fix module checksum

lisa/_assets/kmodules/lisa/Makefile, lisa/_kmod.py
FEATURE
Allow debugging checksum issues by showing the content of the module sources.
=> lisa._assets.kmodules.lisa: Log content of module sources

lisa/_cli_tools/lisa_load_kmod.py, lisa/trace.py
FEATURE
Log the events that LISA can detect in the kernel module (note that this is a superset of what feature can actually be enabled).
=> lisa._cli_tools.lisa_load_kmod: Display events supported by the module

lisa/_kmod.py
FIX
If the base path where we look for the lisa kmod exist but no module exist, find will return an empty string without error. Handle that case and treat it as having not found the kmod.
=> lisa._kmod: Fix preinstalled kmod path when base path exists

lisa/conf.py, lisa/wlgen/rta.py
FIX
Use an f-string so that the placeholder is actually interpreted.
=> lisa.wlgen.rta: Fix rt-app calibration debug logging

lisa/_unshare.py
FIX
Ensure the environment (logging) is setup correctly before attempting to unpickle the function and its arguments. Otherwise, unpickling the arguments will trigger __init__/__new__ calls that will run with the default logging conf rather than what we want.
=> lisa._unshare: Ensure logging is setup before unpickling function

lisa/wlgen/rta.py
FIX
Require a callable rather than limiting it to types.
=> lisa.wlgen.rta: Fix PeriodicWload(run_wload=...) expected type

doc/man1/bisector.1, doc/man1/exekall.1, doc/man1/lisa.1
=> doc/man1: Update year number

tools/exekall/exekall/engine.py
FIX
Some classes like dict can now be parametrized, e.g. dict[int, str]. They do not behave exactly like their deprecated typing counterpart (e.g. typing.Dict), so ensure they are handled consistently by exekall.
=> exekall: Fix handling of parametrized classes

lisa/_kmod.py
FIX
Remove impact of set iteration order from the toolchain selection process.
=> lisa._kmod: Make toolchain selection reproducible

.gitlab-ci.yml, ci/autobranch-job-script.sh, tools/lisa-combine-gitlab-mr
This pull request contains changes to be merged on main branch to enable Gitlab CI to work similar to Github actions.
=> Migrate to gitlab.arm.com
